(function(g){var window=this;'use strict';var U3=function(a){a.oa("cardstatechange",a.Gk()&&a.So()?1:0)},V3=function(a,b){var c=g.$a(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},mib=function(a){var b=g.Yr(a);
a=g.as(a);return new g.Nr(b.x,b.y,a.width,a.height)},nib=function(a,b,c){var d=void 0===d?{}:d;
var e;return e=g.PC(a,b,function(){g.QC(e);c.apply(a,arguments)},d)},Y3=function(a){a=g.gb(a);
delete W3[a];g.kd(W3)&&X3&&X3.stop()},pib=function(){X3||(X3=new g.tu(function(){oib()},20));
var a=X3;a.isActive()||a.start()},oib=function(){var a=g.lb();
g.Vc(W3,function(b){qib(b,a)});
g.kd(W3)||pib()},Z3=function(a,b,c,d){g.Nu.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.B=a;this.N=b;this.duration=c;this.G=d;this.coords=[];this.progress=this.K=0;this.D=null},qib=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.K=1E3/(b-a.D);a.D=b;rib(a,a.progress);1==a.progress?(a.j=0,Y3(a),a.onFinish(),a.jr()):a.isPlaying()&&a.VK()},rib=function(a,b){"function"===typeof a.G&&(b=a.G(b));
a.coords=Array(a.B.length);for(var c=0;c<a.B.length;c++)a.coords[c]=(a.N[c]-a.B[c])*b+a.B[c]},sib=function(a,b){g.Bb.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.K;this.state=b.j},$3=function(a,b,c,d,e){Z3.call(this,b,c,d,e);
this.element=a},tib=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
$3.call(this,a,b,c,d,e)},uib=function(a){return Math.pow(a,3)},vib=function(a){return 3*a*a-2*a*a*a},wib=function(a){g.J.call(this);
this.B=a||window;this.j=[]},a4=function(a){return a.baseUrl||null},b4=function(a,b){return g.Rs(g.dq(a,b),function(c){return!!c})},xib=function(a,b,c){function d(ra){var ma=ra.hovercardButton;
if(!ma)return null;ma=ma.subscribeButtonRenderer;if(!ma)return null;var sa=f(ma.unsubscribedButtonText),ea=f(ma.subscribedButtonText);if(ma.subscribed){var za=f(ma.subscriberCountWithUnsubscribeText);var ba=f(ma.subscriberCountText)}else za=f(ma.subscriberCountText),ba=f(ma.subscriberCountWithSubscribeText);var Ta=null;if(ra.signinEndpoint){Ta=V3(ra,"signinEndpoint","webNavigationEndpointData","url");if(!Ta){var y,V;Ta=null==(V=g.T(null==(y=ma.signInEndpoint)?void 0:y.commandMetadata,g.M2))?void 0:
V.url}if(!Ta)return null}return sa&&(ea||Ta)?{subscribed:ma.subscribed,subscribeText:sa,subscribeCount:za,unsubscribeText:ea,unsubscribeCount:ba,enabled:ma.enabled,signinUrl:Ta,classic:ra.useClassicSubscribeButton}:null}
function e(ra){if(ra){var ma=[],sa=ra.videoId;sa&&ma.push("v="+sa);(sa=ra.playlistId)&&ma.push("list="+sa);(ra=ra.startTimeSeconds)&&ma.push("t="+ra);return"/watch?"+ma.join("&")}}
function f(ra){if(!ra)return null;var ma=ra.simpleText;return ma?ma:ra.runs?g.dq(ra.runs,function(sa){return sa.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=!1,q=null,r=null,t=null,v=null,x=!1,C=null,F=null,G=null,H=null,O=null,Q=null;if("VIDEO"===h)g.T(l,g.AG)?m=g.T(l,g.AG).url:(Q=g.T(l,g.pT),m=e(Q)),n=!1,q=a,b.thumbnailOverlays?(p=b.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,r=f(p.text),p="LIVE"===p.style):r=f(b.videoDuration);else if("PLAYLIST"===h)g.T(l,g.AG)?m=g.T(l,g.AG).url:(Q=g.T(l,g.pT),m=e(Q)),n=!1,q=a,t=f(b.playlistLength);else if("CHANNEL"===
h){if(x=V3(l,"browseEndpoint","browseId"))v=x,m="/channel/"+v;n=!1;q="new";(x=!!b.isSubscribe)?C=d(b):F=f(b.subscribersText)}else"WEBSITE"===h?((G=V3(l,"urlEndpoint","url"))&&(m=G),n=!0,q="new",G=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(H=f(b.productPrice)),b.additionalFeesText&&(O=f(b.additionalFeesText)),(n=V3(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=V3(b,"title","accessibility","accessibilityData","label");var X=b.endpoint?b.endpoint.clickTrackingParams:null,
ia="";if(b.metadata){var qa=f(b.metadata);qa&&(ia=qa)}return{id:"element-"+c,type:h,title:f(b.title),metadata:ia,callToAction:f(b.callToAction),tV:b.image,iconUrl:G,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:r,CD:p,playlistLength:t,channelId:v,subscribeButton:C,subscribersText:F,isSubscribe:x,targetUrl:m||null,v6:n,sessionData:X?{itct:X}:null,Aaa:q,eC:a?a:null,isPlaceholder:b.isPlaceholder,
impressionUrls:b4(b.impressionUrls||[],a4),j6:b4(b.hovercardShowUrls||[],a4),clickUrls:b4(l.loggingUrls||[],a4),visualElement:g.GF(b.trackingParams),productPrice:H,additionalFeesText:O,watchEndpoint:Q||null}},yib=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:b4(a.impressionUrls||[],a4),elements:b4(a.elements||[],function(d,e){return xib(b,d,e)})};
a.trackingParams&&(c.visualElement=g.GF(a.trackingParams));return c},zib=function(a){g.yV.call(this,a);
this.C=this.endscreen=null;this.j={};this.G={};this.D=this.B=null;this.N=[];this.Y=!0;this.K=0;a=a.U();this.Z=g.gS(a)||g.iS(a);this.events=new g.QK(this);g.L(this,this.events);this.events.T(this.player,g.gK("creatorendscreen"),this.onCueRangeEnter);this.events.T(this.player,g.hK("creatorendscreen"),this.onCueRangeExit);this.events.T(this.player,"resize",this.Kb);this.events.T(window,"focus",this.V9);this.load();var b=g.vf("STYLE");(g.Xe("HEAD")[0]||document.body).appendChild(b);g.wb(this,function(){g.Af(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},Aib=function(a){return a.player.getVideoData().Pd?"current":a.Z?"new":"current"},c4=function(a){return"creator-endscreen-editor"===a.player.U().playerStyle},Bib=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.C&&a.C.abort();c={method:"POST",onFinish:function(e){var f=a.C=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=yib(f,Aib(a))));d4(a,f)},
urlParams:{v:c},withCredentials:!0};a.Z&&(c.urlParams.ptype="embedded");var d=b.Px;d&&(c.postParams={ad_tracking:d});if(b=g.mRa(b))if(b=g.yn(b),b=g.de(b))a.C=g.gC(b,c)},d4=function(a,b,c){c=void 0===c?!0:c;
a.player.jf("creatorendscreen");a.B&&(a.B.dispose(),a.B=null,a.D.dispose(),a.D=null);for(var d=g.u(Object.values(a.j)),e=d.next();!e.done;e=d.next())e.value.dispose();a.j={};a.G={};0<a.N.length&&(a.N.forEach(function(l){l.dispose()}),a.N.length=0);
a.K=0;if((a.endscreen=b)&&b.elements){c&&Cib(a);c=[];d=new g.fK(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.U().B||(a.B=new g.U({I:"div",S:"ytp-ce-shadow"}),g.rU(a.player,a.B.element,4),a.D=new g.NG(a.B,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=Dib(a,e);if(f){a.j[e.id]=f;a.G[e.id]=e;g.rU(a.player,f.element,4);var h=new g.fK(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);Eib(a,f,e)}else g.MF(new g.fD("buildEndscreenElement null",
e))}a.player.wf(c);a.Kb()}},Cib=function(a){var b=g.HF(),c=g.IF();
c&&b&&a.endscreen.visualElement&&g.PB(g.SF)(void 0,c,b,a.endscreen.visualElement)},Dib=function(a,b){var c=null;
switch(b.type){case "VIDEO":a={I:"div",Ma:["ytp-ce-element","ytp-ce-video"],W:{tabindex:"0","aria-label":b.eC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-covering-image",W:e4(b)},{I:"div",S:"ytp-ce-covering-shadow-top"},{I:"a",S:"ytp-ce-covering-overlay",W:{href:f4(a,b.targetUrl),tabindex:"-1"},V:[{I:"div",Ma:["ytp-ce-video-title","ytp-webkit-ellipsis"],W:{dir:g.Su(b.title||"")},xa:b.title},{I:"div",S:b.CD?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
xa:b.videoDuration||void 0}]}]};c=new g.U(a);break;case "PLAYLIST":a={I:"div",Ma:["ytp-ce-element","ytp-ce-playlist"],W:{tabindex:"0","aria-label":b.eC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-covering-image",W:e4(b)},{I:"div",S:"ytp-ce-covering-shadow-top"},{I:"a",S:"ytp-ce-covering-overlay",W:{href:f4(a,b.targetUrl),tabindex:"-1"},V:[{I:"div",Ma:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],W:{dir:g.Su(b.title||"")},xa:b.title},{I:"div",S:"ytp-ce-playlist-count",
V:[{I:"div",S:"ytp-ce-playlist-icon"},{I:"div",S:"ytp-ce-playlist-count-text",xa:b.playlistLength||void 0}]}]}]};c=new g.U(a);break;case "CHANNEL":c={I:"div",Ma:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],W:{tabindex:"0","aria-label":b.eC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",
V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"a",Ma:["ytp-ce-channel-title","ytp-ce-link"],W:{href:f4(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.Su(b.title||"")},xa:b.title},b.subscribeButton?{I:"div",S:"ytp-ce-subscribe-container",V:[{I:"div",S:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{I:"div",S:"ytp-ce-channel-subscribers-text",xa:b.subscribersText}:"",b.metadata?{I:"div",Ma:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],xa:b.metadata}:""]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",W:e4(b)}]};c=new g.U(c);var d=g.jf(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.Bu(d,"ytp-ce-subscribe-button");if(a.player.U().B){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.jW(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,
b.channelId,!!b.subscribeButton.subscribed,e,f,a.player);d.appendChild(e.element);a.N.push(e)}break;case "WEBSITE":a={I:"div",Ma:["ytp-ce-element","ytp-ce-website"],W:{tabindex:"0","aria-label":b.eC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",
S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"div",S:"ytp-ce-website-title",W:{dir:g.Su(b.title||"")},xa:b.title},{I:"div",S:"ytp-ce-website-metadata",xa:b.metadata},{I:"a",Ma:["ytp-ce-website-goto","ytp-ce-link"],W:{href:f4(a,b.targetUrl),target:"_blank",tabindex:"-1"},xa:b.callToAction}]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",W:e4(b)},{I:"div",S:"ytp-ce-expanding-icon",W:Fib(b.iconUrl)}]};c=new g.U(a);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={I:"div",S:"ytp-ce-merchandise-price-container",
V:[{I:"div",S:"ytp-ce-merchandise-price",xa:b.productPrice}]},b.additionalFeesText&&c.V.push({I:"div",S:"ytp-ce-merchandise-additional-fees",xa:b.additionalFeesText})),a={I:"div",Ma:["ytp-ce-element","ytp-ce-merchandise"],W:{tabindex:"0","aria-label":b.eC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",
V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"div",S:"ytp-ce-merchandise-title",W:{dir:g.Su(b.title||"")},xa:b.title},c,{I:"div",S:"ytp-ce-merchandise-metadata",xa:b.metadata},{I:"a",Ma:["ytp-ce-merchandise-goto","ytp-ce-link"],W:{href:f4(a,b.targetUrl),target:"_blank",tabindex:"-1"},xa:b.callToAction}]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",W:e4(b)},{I:"div",S:"ytp-ce-merchandise-invideo-cta-container",V:[{I:"div",S:"ytp-ce-merchandise-invideo-cta",
xa:b.callToAction||void 0}]}]},c=new g.U(a)}b.isPlaceholder&&g.Bu(c.element,"ytp-ce-placeholder");return c},e4=function(a){if(a.tV)var b=a.tV.thumbnails;
return Fib(b?b[b.length-1].url:null)},Fib=function(a){return a?{style:"background-image: url("+a+")"}:{}},Eib=function(a,b,c){function d(m){m&&(b.Sa("blur",function(){"none"!=m.style.display&&a.Y&&m.focus()}),b.T(m,"focus",f),b.T(m,"blur",h))}
function e(m){a.K+=m;0<a.K?(g.Bu(b.element,"ytp-ce-force-expand"),g4(a,c.id,!0)):(g.Du(b.element,"ytp-ce-force-expand"),g.Du(b.element,"ytp-ce-element-hover"),g4(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.Sa("mouseenter",function(){Gib(a,b,c)});
b.Sa("mouseleave",function(){Hib(a,b,c)});
a.player.U().B||b.Sa("click",function(){g.Bu(b.element,"ytp-ce-element-hover")});
b.Sa("click",function(m){Iib(a,c,m)});
b.Sa("keypress",function(m){Iib(a,c,m)});
b.Sa("focus",function(){Gib(a,b,c)});
b.Sa("blur",function(){Hib(a,b,c)});
b.Sa("touchstart",function(){Gib(a,b,c)});
var l=g.lf("ytp-ce-expanding-overlay-hider",b.element);l&&b.T(l,"touchstart",function(m){m.stopPropagation();g.Du(b.element,"ytp-ce-element-hover");g.Du(b.element,"ytp-ce-force-expand")});
b.Sa("keydown",function(m){a.Y=9===m.keyCode&&!m.shiftKey});
d(g.lf("ytp-sb-subscribe",b.element));d(g.lf("ytp-sb-unsubscribe",b.element));b.Sa("focus",f);b.Sa("blur",h)},Iib=function(a,b,c){if(b.targetUrl&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.Au(d,"ytp-ce-element");){g.Au(d,"subscribe-label")&&Jib(a,b);
if(g.Au(d,"ytp-ce-channel-subscribe"))return;d=g.Ef(d)}if(!d||g.Au(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.j[b.id])Hib(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.Aaa)Jib(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.yn(f4(a,b.targetUrl)),g.mH(g.de(c),void 0,b.sessionData);else{var e=g.sS(a.player.U())||a.player.getVideoData().Pd,f=function(){var h=f4(a,b.targetUrl),l=b.sessionData,m=b.watchEndpoint,n=g.UB(h);e&&n&&(n.v||
n.list)?a.player.zo(n.v,l,n.list,!1,void 0,m||void 0):g.awa(h,l)};
Jib(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},f4=function(a,b){a=a.player.U();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.zS(a)+b}else return"";return b},Gib=function(a,b,c){g.Au(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.Bu(b.element,"ytp-ce-element-hover"):a.player.U().B?(new g.tu(function(){g.Bu(b.element,"ytp-ce-element-hover")},200)).start():g.Bu(b.element,"ytp-ce-element-hover"),h4(a,c.j6),g4(a,c.id,!0))},Hib=function(a,b,c){g.Du(b.element,"ytp-ce-element-hover");
g.Du(b.element,"ytp-ce-force-expand");g4(a,c.id,!1)},g4=function(a,b,c){a.B&&(c?a.D.show():a.D.hide());
for(var d=g.u(Object.keys(a.j)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.Fu(a.j[e].element,"ytp-ce-element-shadow-show",c)},h4=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||c4(a))c&&c();else{b=Kib(a,b);var e=0,f=!1,h=new g.tu(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.zE(b[a],d)}},Jib=function(a,b,c){h4(a,b.clickUrls,c);
(a=g.IF())&&b.v6&&g.ZF(a,b.visualElement)},Kib=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(Lib(b[d],c));return a},Lib=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},Mib=function(a){return"string"===typeof a?a:""},i4=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},Nib=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.j=d},j4=function(a){return a.value?a.value:null},k4=function(a){if(!a)return null;
var b=g.yn(Mib(a.value));b=g.de(b);if(!b)return null;var c=i4(a.target,Oib,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new Nib(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},Pib=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},Sib=function(a){if(!a)return null;
var b=i4(a.type,Qib),c=i4(a.trigger,Rib);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=k4(a?a:null);return b?new Pib(b,c,a):null},Tib=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},Uib=function(a,b){return g.Eb(a.action,b)},Vib=function(a,b){this.context=a;
this.j=b},Wib=function(a){return a.customMessage?l4("div","iv-card-message",a.customMessage):""},m4=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{I:"div",S:"iv-card-image",W:{style:a},V:c}},Xib=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.u(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(l4("li","",c.value));return{I:"ul",S:"iv-card-meta-info",V:b}},l4=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.Su(c);return{I:a,W:b,xa:c}},Yib=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.oC&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.oC+");");c.dir=g.Su(a.customMessage);var d=[{I:"span",xa:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({I:"span",S:"iv-card-link-icon"}));return{I:"div",Ma:b,W:c,V:d}},n4=function(a,b,c,d){if(d){b=g.u(b);
for(var e=b.next();!e.done;e=b.next())a.j(e.value,d,c.id,c.sessionData,c.bj.click,5)}},Zib=function(a,b){this.merchant=a;
this.price=b},$ib=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,"").split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},ajb=function(a,b){return b?b:$ib(a)?"current":"new"},o4=function(a,b){g.J.call(this);
var c=this;this.element=a;this.context=b;this.wb=!1;this.Za=new Map;this.fb=new Map;this.context.J.addEventListener(g.gK("annotations_module"),function(d){(d=c.Za.get(d))&&d.apply(c)});
this.context.J.addEventListener(g.hK("annotations_module"),function(d){(d=c.fb.get(d))&&d.apply(c)})},p4=function(a,b,c,d,e,f,h){a.context.j.Sa(b,"click",function(l){a.WK(c,d,e,f||[],h||0,l)});
a.context.j.Sa(b,"touchstart",function(){a.wb=!1});
a.context.j.Sa(b,"touchmove",function(){a.wb=!0})},bjb=function(a){var b;
return(null==(b=g.T(a,g.AG))?0:b.url)?g.T(a,g.AG).url:(a=g.T(a,g.pT))&&a.videoId?(b="/watch?v="+a.videoId,a.playlistId&&(b+="&list="+a.playlistId),a.index&&(b+="&index="+a.index),a.startTimeSeconds&&(b+="&t="+a.startTimeSeconds),b):null},q4=function(a,b,c){return{QW:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
f_:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
uK:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},cjb=function(a,b,c){o4.call(this,b,c);
var d=this;this.J=a;this.eventId=null;this.Hb=this.Na=this.Yb=this.C=this.isInitialized=!1;this.cards=[];this.yb=this.Z=this.Ka=this.G=this.Va=this.j=null;this.ma=[];this.qa=this.N=this.Zf=this.Da=null;this.K=0;this.Ea=new g.tu(function(){},c.X.Ii?4E3:3E3);
g.L(this,this.Ea);this.jb=new g.tu(function(){});
g.L(this,this.jb);this.Aa=new Vib(c,function(e,f,h,l,m,n){p4(d,e,f,h,l,m,n)});
this.Y=new g.U({I:"div",S:"iv-drawer",W:{id:"iv-drawer"},V:[{I:"div",S:"iv-drawer-header",W:{"aria-role":"heading"},V:[{I:"span",S:"iv-drawer-header-text"},{I:"button",Ma:["iv-drawer-close-button","ytp-button"],W:{"aria-label":"Masquer les fiches",tabindex:"0"}}]},{I:"div",S:"iv-drawer-content"}]});g.L(this,this.Y);this.D=this.Y.element;this.ib=new g.NG(this.Y,330);g.L(this,this.ib);this.Nb=g.lf("iv-drawer-header-text",this.D);this.B=g.lf("iv-drawer-content",this.D);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.Yb&&r4(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Yb=d.C)&&s4(d)});
this.Ra=new g.QK(this);g.L(this,this.Ra);this.J.addEventListener("videodatachange",this.Zs.bind(this))},djb=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){r4(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){s4(a)});
var c=b.headerText;g.Gf(a.Nb,c);a.Z&&a.Z.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Da=g.GF(b.trackingParams);a.N=g.GF(b.closeTrackingParams);a.Zf=g.GF(b.iconTrackingParams)},ejb=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.K,d=a.J.U().experiments.ob("enable_error_corrections_infocard_web_client");
if(!b.content&&b.teaser.simpleCardTeaserRenderer&&d){var e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"simple",teaserText:g.oG(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:{},sponsored:!1,bj:{},To:null,yk:e.trackingParams?g.GF(e.trackingParams):null,Zf:f&&f.trackingParams?g.GF(f.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,
oC:null,title:"",customMessage:"",url:null,onClickCommand:e.onTapCommand||null};t4(a,b)}else{var h;if(null==(h=b.content)?0:h.simpleCardContentRenderer){if(!b.cueRanges.length)return;f=null==(e=b.content)?void 0:e.simpleCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;var l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"simple",teaserText:g.oG(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,
sessionData:u4(a,c,b,f),sponsored:!1,bj:q4(f,e,f.command),To:f.trackingParams?g.GF(f.trackingParams):null,yk:e.trackingParams?g.GF(e.trackingParams):null,Zf:l&&l.trackingParams?g.GF(l.trackingParams):null,imageUrl:v4(f.image.thumbnails,290).url,displayDomain:f.displayDomain?g.oG(f.displayDomain):null,showLinkIcon:!!f.showLinkIcon,oC:null,title:f.title?g.oG(f.title):"",customMessage:f.callToAction?g.oG(f.callToAction):"",url:g.T(f.command,g.AG).url?k4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.T(f.command,g.AG).url}):null,onClickCommand:null};t4(a,b)}else{var m;if(null==(m=b.content)?0:m.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(f=b.content)?void 0:f.collaboratorInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"collaborator",teaserText:g.oG(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),
autoOpen:!!b.autoOpen,sessionData:u4(a,c,b,e),sponsored:!1,bj:q4(e,f,e.endpoint),To:e.trackingParams?g.GF(e.trackingParams):null,yk:f.trackingParams?g.GF(f.trackingParams):null,Zf:l&&l.trackingParams?g.GF(l.trackingParams):null,channelId:g.T(e.endpoint,g.PU).browseId,customMessage:e.customText?g.oG(e.customText):null,dZ:v4(e.channelAvatar.thumbnails,290).url,title:e.channelName?g.oG(e.channelName):"",metaInfo:[e.subscriberCountText?g.oG(e.subscriberCountText):""],url:k4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.T(e.endpoint,g.PU).canonicalBaseUrl?g.T(e.endpoint,g.PU).canonicalBaseUrl:"/channel/"+g.T(e.endpoint,g.PU).browseId}),onClickCommand:null};t4(a,b)}else{var n;if(null==(n=b.content)?0:n.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(l=b.content)?void 0:l.playlistInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"playlist",teaserText:g.oG(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:u4(a,c,b,e),sponsored:!1,bj:q4(e,f,e.action),To:e.trackingParams?g.GF(e.trackingParams):null,yk:f.trackingParams?g.GF(f.trackingParams):null,Zf:l&&l.trackingParams?g.GF(l.trackingParams):null,FF:v4(e.playlistThumbnail.thumbnails,258).url,customMessage:e.customMessage?g.oG(e.customMessage):null,playlistVideoCount:g.oG(e.playlistVideoCount),title:e.playlistTitle?g.oG(e.playlistTitle):"",metaInfo:[e.channelName?g.oG(e.channelName):
"",e.videoCountText?g.oG(e.videoCountText):""],url:k4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:bjb(e.action)}),onClickCommand:null};t4(a,b)}else{var p;if(null==(p=b.content)?0:p.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;var q;e=null==(q=b.content)?void 0:q.videoInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"video",teaserText:g.oG(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:u4(a,c,b,e),sponsored:!1,bj:q4(e,f,e.action),To:e.trackingParams?g.GF(e.trackingParams):null,yk:f.trackingParams?g.GF(f.trackingParams):null,Zf:l&&l.trackingParams?g.GF(l.trackingParams):null,FF:v4(e.videoThumbnail.thumbnails,258).url,videoDuration:e.lengthString?g.oG(e.lengthString):null,customMessage:e.customMessage?g.oG(e.customMessage):null,title:e.videoTitle?g.oG(e.videoTitle):"",metaInfo:[e.channelName?g.oG(e.channelName):
"",e.viewCountText?g.oG(e.viewCountText):""],isLiveNow:!!e.badge,url:k4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:bjb(e.action)}),onClickCommand:null};t4(a,b)}}}}}a.K++},v4=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},u4=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},gjb=function(a,b){if(b=fjb(a,b))b===a.j&&(a.j=null),a.J.removeCueRange(b.jg.id),g.Af(b.vM),g.Ib(a.cards,b),a.DG(),w4(a)},r4=function(a,b,c){if(!a.C){a.ib.show();
a.Va=new g.tu(function(){g.Bu(a.context.J.getRootNode(),g.YY.IV_DRAWER_OPEN)},0);
a.Va.start();a.Ra.T(a.B,"mousewheel",function(h){a.Ea.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.B.scrollTop+=h});
a.C=!0;var d=g.IF();d&&a.Da&&a.N&&g.XF(d,[a.Da,a.N]);b={TRIGGER_TYPE:b};for(var e=g.u(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.AX||(f.AX=!0,hjb(a.context.logger,f.jg.bj.QW,b)),d&&g.XF(d,[f.jg.To]);U3(a.J);c&&(a.G=new g.tu(function(){a.Ka=a.Z;a.yb.focus()},330),a.G.start())}},s4=function(a){a.C&&(a.ib.hide(),g.VC(a.Ra),g.Du(a.context.J.getRootNode(),g.YY.IV_DRAWER_OPEN),a.C=!1,U3(a.J),a.G&&a.G.stop(),a.G=new g.tu(function(){a.Ka&&(a.Ka.focus(),a.Ka=null)},330),a.G.start())},jjb=function(a){g.Cu(a.Db(),
[g.YY.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.rU(a.J,a.D,5);ijb(a);a.Z=g.lf("ytp-cards-button",a.J.getRootNode());a.yb=g.lf("iv-drawer-close-button",a.D);a.isInitialized=!0},ijb=function(a){var b=g.lf("iv-drawer-close-button",a.D);
a.context.j.Sa(b,"click",a.n4,a);a.context.j.Sa(a.B,"touchend",function(){a.Ea.start()});
a.context.j.Sa(a.B,"scroll",a.G4,a);a.context.B.subscribe("onHideControls",function(){a.Na=!0});
a.context.B.subscribe("onShowControls",function(){a.Na=!1});
a.context.B.subscribe("onVideoAreaChange",function(){a.Na=g.Au(a.J.getRootNode(),"ytp-autohide")});
a.ma.push(g.NE("iv-button-shown",a.J6,a));a.ma.push(g.NE("iv-button-hidden",a.I6,a));kjb(a)},kjb=function(a){a.ma.push(g.NE("iv-teaser-shown",a.N0,a));
a.ma.push(g.NE("iv-teaser-hidden",a.K6,a));a.ma.push(g.NE("iv-teaser-clicked",a.M0,a));a.Hb=!0},ljb=function(a,b){var c;
return b.onClickCommand&&"engagement-panel-error-corrections"===(null==(c=g.T(b.onClickCommand,g.Qeb))?void 0:c.targetId)?(a.qa=b,!0):!1},mjb=function(a,b){a.qa=b;
var c=a.J.getVideoData();if(!c)return!1;c=g.MPa(c);if(null==c?0:c.markersMap)for(var d,e=0;(null==(d=c)?void 0:d.markersMap.length)>e;e++){var f=void 0,h=null==(f=c)?void 0:f.markersMap[e];if("ERROR_CORRECTION_MARKERS"===h.key&&(f=void 0,(h=null==(f=h.value)?void 0:f.markers)&&0<h.length))return d=void 0,b.startMs=(null==(d=g.T(h[0],g.lYa))?void 0:d.timeRangeStartMillis)||0,a.qa=null,!0}return!1},t4=function(a,b){if(!ljb(a,b)||mjb(a,b)){var c=njb(a,b);
if(c){var d={jg:b,vM:c.element,AX:!1};if(b.onClickCommand)!a.Hb&&a.J.L("enable_wn_infocards")&&kjb(a);else{a.isInitialized||jjb(a);gjb(a,b.id);var e=ojb(a,d);g.Rb(a.cards,e,0,d);c.Fa(a.B,e);a.DG()}b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.C||(a.j=d,w4(a),pjb(a,d),r4(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.J.getCurrentTime(),5E3>c&&c>b.startMs&&qjb(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){qjb(a,d)}),w4(a))}}},njb=function(a,b){switch(b.type){case "simple":a=
a.Aa;
var c=b.displayDomain?{I:"div",S:"iv-card-image-text",xa:b.displayDomain}:void 0;var d=Yib(b);c={I:"div",Ma:["iv-card"],V:[{I:"a",S:"iv-click-target",W:{href:b.url?j4(b.url)||"":""},V:[m4(b.imageUrl,c),{I:"div",S:"iv-card-content",V:[l4("h2",void 0,b.title),d]}]}]};c=new g.U(c);n4(a,g.kf("iv-click-target",c.element),b,b.url);b=c;break;case "collaborator":a=a.Aa;c={I:"div",Ma:["iv-card","iv-card-channel"],V:[{I:"a",Ma:["iv-click-target"],W:{href:j4(b.url)||"","data-ytid":b.channelId},V:[m4(b.dZ),{I:"div",
S:"iv-card-content",V:[Wib(b),{I:"h2",S:"iv-card-primary-link",xa:b.title},Xib(b)]}]}]};c=new g.U(c);n4(a,g.kf("iv-click-target",c.element),b,b.url);b=c;break;case "playlist":a=a.Aa;c={I:"div",Ma:["iv-card","iv-card-playlist"],V:[{I:"a",S:"iv-click-target",W:{href:j4(b.url)||""},V:[m4(b.FF,{I:"div",S:"iv-card-image-overlay",V:[{I:"span",S:"iv-card-playlist-video-count",xa:b.playlistVideoCount}]}),{I:"div",S:"iv-card-content",V:[Wib(b),l4("h2","iv-card-primary-link",b.title),Xib(b)]}]}]};c=new g.U(c);
n4(a,g.kf("iv-click-target",c.element),b,b.url);b=c;break;case "productListing":a=a.Aa;var e=0!=b.offers.length;c=["iv-card"];d="";var f=Yib(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({I:"div",S:"iv-card-offer-price",xa:f.price}),f.merchant&&e.push({I:"div",S:"iv-card-offer-merchant",xa:f.merchant}),f={I:"div",V:e});e=b.url?j4(b.url)||"":"";c={I:"div",Ma:c,W:{tabindex:"0"},V:[{I:"a",Ma:["iv-card-image","iv-click-target"],W:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{I:"div",S:"iv-card-content",V:[b.sponsored?{I:"div",S:"iv-card-sponsored",V:["Lien commercial",{I:"div",S:"iv-ad-info-container",V:[{I:"div",S:"iv-ad-info",xa:"{{adInfo}}"},{I:"div",S:"iv-ad-info-icon-container",V:[{I:"div",S:"iv-ad-info-icon"},{I:"div",S:"iv-ad-info-callout"}]}]}]}:"",{I:"a",S:"iv-click-target",W:{href:e},V:[l4("h2",d,b.title),f]}]}]};c=new g.U(c);d=g.vf("span");g.Gf(d,"Vous voyez ce produit, car nous pensons qu'il est pertinent pour la vid\u00e9o. Il se peut que le marchand r\u00e9mun\u00e8re Google.");
c.le(d,"adInfo");n4(a,g.kf("iv-click-target",c.element),b,b.url);b=c;break;case "video":a=a.Aa;d=b.videoDuration?{I:"span",S:"iv-card-video-duration",xa:b.videoDuration}:void 0;f=b.isLiveNow?{I:"span",Ma:["yt-badge","yt-badge-live"],xa:"EN DIRECT MAINTENANT"}:null;e={I:"div",Ma:["iv-card","iv-card-video"],V:[{I:"a",S:"iv-click-target",W:{href:(null==(c=b.url)?void 0:j4(c))||""},V:[m4(b.FF,d),{I:"div",S:"iv-card-content",V:[Wib(b),l4("h2","iv-card-primary-link",b.title),Xib(b),f]}]}]};c=new g.U(e);
n4(a,g.kf("iv-click-target",c.element),b,b.url);b=c;break;default:return null}return b},ojb=function(a,b){if(0===a.cards.length)return 0;
a=g.Fb(a.cards,function(c){return b.jg.startMs>c.jg.startMs||b.jg.startMs===c.jg.startMs&&b.jg.timestamp>=c.jg.timestamp?!0:!1});
return-1===a?0:a+1},rjb=function(a){if(a.j)return"productListing"===a.j.jg.type;
if(a.J.L("enable_wn_infocards")){var b;return!(null==(b=a.cards)||!b.length)&&g.eq(a.cards,function(c){return"productListing"===c.jg.type})}return g.eq(a.cards,function(c){return"productListing"===c.jg.type})},w4=function(a){g.Fu(a.J.getRootNode(),"ytp-cards-shopping-active",rjb(a))},qjb=function(a,b){if(!g.Au(a.J.getRootNode(),"ytp-cards-teaser-shown")){if(a.j!==b){var c=g.IF(),d=a.j?a.j.jg.Zf:a.Zf;
c&&d&&g.YF(c,[d]);a.j=b;w4(a)}(c=a.isInitialized&&"none"==a.Db().style.display)||(c=a.context.J.getPlayerState(),d=0===c&&0===a.context.J.getCurrentTime(),c=!(1===c||3===c||d));c||b.jg.teaserDurationMs&&a.J.UA(!0,{teaserText:b.jg.teaserText,durationMs:b.jg.teaserDurationMs,onClickCommand:b.jg.onClickCommand});a.jb.isActive()||((!a.C||!a.Ea.isActive()&&a.Na)&&pjb(a,b),a.jb.start(910+b.jg.teaserDurationMs))}},pjb=function(a,b){a.Y.Gb?(b=new Z3([0,
a.B.scrollTop],[0,b.vM.offsetTop],600,vib),a.context.C.Sa(b,"animate",function(c){a.B.scrollTop=c.y}),a.context.C.Sa(b,"finish",function(c){a.B.scrollTop=c.y}),b.play()):(g.kG(a.Y,!0),a.B.scrollTop=b.vM.offsetTop,g.kG(a.Y,!1))},x4=function(a){return a.j&&a.j.jg?a.j.jg:a.cards[0]&&a.cards[0].jg?a.cards[0].jg:null},fjb=function(a,b){return g.Eb(a.cards,function(c){return c.jg.id===b})},y4=function(a,b,c){o4.call(this,a,b);
this.annotation=c;this.isActive=!1},sjb=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},z4=function(a,b,c){y4.call(this,a,b,c);
this.B=null;this.N=!1;this.C=null;this.D=!1;this.j=this.K=this.G=null},tjb=function(a,b){var c=void 0===c?0:c;
var d=mib(b).width;g.Wr(b,d);c=new tib(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,uib);g.L(a,c);a.context.C.Sa(c,"begin",function(){g.bs(b,!0)});
c.play()},wjb=function(a,b){if(b.channel_name){var c=a.createElement({I:"div",
Ma:["iv-branding-context-name"],xa:b.channel_name}),d=a.createElement({I:"div",Ma:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.j=new g.jW(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,a.context.J),a.j.Fa(d));var f=a.createElement({I:"div",Ma:["iv-branding-context-subscribe-caret"]}),h=a.createElement({I:"div",Ma:["branding-context-container-inner"]});h.appendChild(f);
h.appendChild(c);h.appendChild(d);g.bs(h,!1);var l=a.createElement({I:"div",Ma:["branding-context-container-outer"]});l.appendChild(h);g.Qr(l,"right",b.image_width+"px");g.xf(a.Db(),l);a.C=new g.tu(function(){ujb(a,h,l)},500);
g.L(a,a.C);a.context.j.Sa(a.Db(),"mouseover",function(){vjb(a,h,l,f,b.image_height)});
a.context.j.Sa(a.Db(),"mouseout",function(){a.C.start()})}},vjb=function(a,b,c,d,e){a.C.stop();
if(!a.D){var f=g.as(b);a.j||(b.style.width=g.Vr(f.width,!0),c.style.width=g.Vr(f.width,!0));g.Qr(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.Qr(d,"right","1px");a.D=!0;g.bs(b,!0);a.G=new g.tu(function(){g.Bu(this.Db(),"iv-branding-active")},0,a);
a.G.start()}},ujb=function(a,b,c){g.Du(a.Db(),"iv-branding-active");
a.K=new g.tu(function(){g.bs(b,!1);a.j||(c.style.width=g.Vr(0,!0))},250);
a.K.start();a.D=!1},xjb=function(a,b,c,d,e,f,h){this.j=a;
this.C=b;this.X=c;this.videoData=d;this.logger=e;this.J=f;this.B=h},yjb=function(a,b,c){y4.call(this,a,b,c);
var d=this;this.Z=this.isCollapsed=this.Y=!1;this.K=5E3;this.B=this.C=this.j=this.D=null;this.N=this.createElement({I:"div",Ma:["iv-promo-contents"]});this.G=new g.tu(function(){d.j.setAttribute("aria-hidden","true");g.bs(d.C,!1);g.bs(d.B,!0)},700,this);
g.L(this,this.G)},Bjb=function(a,b,c){c.stopPropagation();
zjb(a);Ajb(a,b);a.j.focus()},Cjb=function(a){a.isCollapsed||a.Z||a.D||(g.Bu(a.Db(),"iv-promo-collapsed"),a.isCollapsed=!0,a.G.start())},zjb=function(a){a.G.stop();
a.isCollapsed&&(g.Eu(a.Db(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.j&&a.j.removeAttribute("aria-hidden"),g.bs(a.B,!1),g.bs(a.C,!0))},Ajb=function(a,b){a.D||(a.D=g.og(function(){Djb(this);
Cjb(this)},b,a))},Djb=function(a){a.D&&(g.Ua.clearTimeout(a.D),a.D=null)},Ejb=function(a){this.J=a},hjb=function(a,b,c){b&&(c?A4(a,b.map(function(d){return g.hu(d,c)})):A4(a,b))},A4=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.u(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.zE(m,f);d&&(e++,0!==d&&a.J.sendVideoStatsEngageEvent(d,f))},Fjb=function(a){g.yV.call(this,a);
var b=this;this.Y=this.N=!1;this.loadNumber=0;this.K={};this.logger=new Ejb(this.player);this.D=new g.QK(this);this.G=this.kx=null;this.events=new g.QK(this);this.qh=this.Z=this.j=null;this.ma=[];g.L(this,this.D);this.D.T(this.player,"onVideoAreaChange",function(){b.oa("onVideoAreaChange")});
this.D.T(this.player,"onHideControls",function(){b.oa("onHideControls")});
this.D.T(this.player,"onShowControls",function(){b.oa("onShowControls")});
this.D.T(this.player,"resize",function(d){b.oa("resize",d)});
this.D.T(this.player,"presentingplayerstatechange",function(d){b.oa("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.O0,this);this.subscribe("resize",this.jJ,this);this.player.U().Na.subscribe("vast_info_card_add",this.IY,this);g.L(this,this.events);this.qa=this.createElement({I:"div",S:"video-custom-annotations"});this.B=new g.U({I:"div",Ma:["ytp-player-content","ytp-iv-player-content"]});g.L(this,this.B);g.rU(this.player,this.B.element,4);this.B.hide();this.C=new g.U({I:"div",Ma:["ytp-iv-video-content"]});g.L(this,this.C);a=this.createElement({I:"div",S:"video-annotations"});
a.appendChild(this.qa);this.C.element.appendChild(a);this.Vt()&&this.load();var c=this.createElement({I:"style"});(g.Xe("HEAD")[0]||document.body).appendChild(c);g.wb(this,function(){g.Af(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},Gjb=function(a){a=a.createElement({I:"div",
Ma:["annotation","annotation-type-custom"]});g.bs(a,!1);return a},Hjb=function(a,b){b=!b.isCued()&&!g.TG(b,1024);
g.kG(a.B,b);g.kG(a.C,b)},Ijb=function(a,b,c){a.N=!0;
a.G=g.gC(b,c)},Jjb=function(a,b){for(var c={},d=g.u(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.ab(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(Jjb(a,e))}return c},Njb=function(a){var b=a.player.getVideoData();
if(b.Ra){var c=a.player.U().Na.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(h=g.aC(h)&&h.responseXML?h.responseXML:null)&&Kjb(a,h)}};
g.nD()&&(d.onFinish=Ljb(a,d.onFinish));d.postParams={ic_only:"1"};Mjb(d,c);a.N=!0;g.gC(b.Ra,d)}}},Mjb=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.IG&&(a.postParams.ic_coll=b.IG);b.wM&&(a.postParams.ic_xml=b.wM);b.zK&&(a.postParams.ic_track=b.zK)},Ojb=function(a){var b=new g.U({I:"div"});
g.bs(b.element,!1);var c=new cjb(a.player,b.element,B4(a));g.L(c,b);b.Fa(a.B.element);c.tF();return c},Qjb=function(a,b){var c,d;
if(b=null==(c=b.Hd)?void 0:null==(d=c.cards)?void 0:d.cardCollectionRenderer)a.Y=!0,Pjb(a,b),b.headerText&&a.qh&&(c=g.oG(b.headerText),a.qh.setAttribute("title",c))},B4=function(a){if(!a.Z){var b=new wib(a);
g.L(a,b);var c=new g.oo(a);g.L(a,c);a.Z=new xjb(b,c,a.player.U(),a.player.getVideoData(),a.logger,a.player,a.jj)}return a.Z},Kjb=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.IF();if(e){var f=g.HF();f&&g.PB(g.xua)(void 0,e,f,[g.GF(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=Jjb(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m="string"===typeof h&&null!=l&&null!=h&&h.match(l)?h:"";var n=i4(f.type,Rjb),p=i4(f.style,Sjb),q=Mib(f.data),r=0!==q.length?JSON.parse(q):{};var t=f.action;f=Sib;if(null==t)var v=null;else if(g.$a(t)){l=[];for(var x=g.u(t),C=x.next();!C.done;C=x.next()){var F=f(C.value);
F&&l.push(F)}v=l}else{var G=f(t);v=G?[G]:[]}e=m&&n?new Tib(m,n,p,v,r):null}else e=null}catch(qa){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var H=Gjb(f),O=null;switch(l.type){case "branding":if(f.player.U().Zd)break;f.B.element.appendChild(H);O=new z4(H,B4(f),l);break;case "promotion":g.rU(f.player,H,4),O=new yjb(H,B4(f),l)}O&&O.tF();if(f=O)g.L(a,f),a.K[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.j||(a.j=Ojb(a),g.L(a,a.j));if("card"===e.type){c=a.j;var Q=e&&e.data&&e.data.card_type;
f=e.data;if(Q)switch(l=f.tracking||{},l={QW:l.impression,click:l.click,close:l.close,f_:l.teaser_impression,uK:l.teaser_click},H=f.tracking_params||{},O=null,Q){case "collaborator":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,bj:l,To:H.card?g.GF(H.card):null,yk:H.teaser?g.GF(H.teaser):null,Zf:H.icon?g.GF(H.icon):null,channelId:f.channel_id,
customMessage:f.custom_message?f.custom_message:null,dZ:f.image_url,title:f.title,metaInfo:f.meta_info,url:k4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};t4(c,e);break;case "playlist":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,bj:l,To:H.card?g.GF(H.card):null,yk:H.teaser?
g.GF(H.teaser):null,Zf:H.icon?g.GF(H.icon):null,FF:f.image_url,playlistVideoCount:f.playlist_video_count,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,url:k4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};t4(c,e);break;case "productListing":f.signin_url&&(O=k4({target:"current",value:f.signin_url}));Q=[];for(var X=f.offers||[],ia=0;ia<X.length;ia++)Q.push(new Zib(g.He(X[ia].merchant),g.He(X[ia].price)));
e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,bj:l,To:H.card?g.GF(H.card):null,yk:H.teaser?g.GF(H.teaser):null,Zf:H.icon?g.GF(H.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,oC:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?
f.custom_message:null,url:k4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),Ohb:O,Nhb:f.signin_title?f.signin_title:void 0,Mhb:f.signin_message?f.signin_message:void 0,offers:Q,onClickCommand:null};t4(c,e);break;case "simple":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,bj:l,To:H.card?g.GF(H.card):
null,yk:H.teaser?g.GF(H.teaser):null,Zf:H.icon?g.GF(H.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,oC:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:null,url:k4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};t4(c,e);break;case "video":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,
startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,bj:l,To:H.card?g.GF(H.card):null,yk:H.teaser?g.GF(H.teaser):null,Zf:H.icon?g.GF(H.icon):null,FF:f.image_url,videoDuration:f.video_duration||null,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,isLiveNow:!!f.is_live_now,url:k4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null},t4(c,e)}}else djb(a.j,e);c=!0}}c&&
(U3(a.player),a.jJ())},Pjb=function(a,b){var c=!1;
a.j||(a.j=Ojb(a),g.L(a,a.j));for(var d=g.u(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(ejb(a.j,e.cardRenderer),c=!0);if(c){var f;null!=(f=a.player.getVideoData())&&g.KT(f)||(c=a.j,d=b.headerText?g.oG(b.headerText):"",g.Gf(c.Nb,d),c.Z&&c.Z.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Da=b.trackingParams?g.GF(b.trackingParams):null,c.N=b.closeButton.infoCardIconRenderer.trackingParams?g.GF(b.closeButton.infoCardIconRenderer.trackingParams):
null,c.Zf=b.icon.infoCardIconRenderer.trackingParams?g.GF(b.icon.infoCardIconRenderer.trackingParams):null,a.jJ());U3(a.player)}},Tjb=function(a,b,c,d,e){if(!a.player.U().Zd){var f=[];
b.navigationEndpoint&&g.T(b.navigationEndpoint,g.PU)&&g.T(b.navigationEndpoint,g.PU).browseId&&f.push(new Pib("openUrl","click",new Nib("/channel/"+g.T(b.navigationEndpoint,g.PU).browseId,"new",!0,!0)));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&g.T(b.subscribeButton,
g.DT)){d.channel_id=g.T(b.subscribeButton,g.DT).channelId;var l;b=g.T(b.subscribeButton,g.DT);h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.oG(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.oG(b.subscriberCountText))):(b.subscriberCountText&&(e=g.oG(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.oG(b.subscriberCountWithSubscribeText)));var m,n=(null==(m=g.T(null==(l=b.signInEndpoint)?void 0:l.commandMetadata,g.M2))?void 0:m.url)||"";l={subscribeText:g.oG(b.unsubscribedButtonText),
subscribeCount:e||"",unsubscribeText:g.oG(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:n};d.standalone_subscribe_button_data=l}f=new Tib(c,"branding","branding",f,d);l=Gjb(a);a.B.element.appendChild(l);f=new z4(l,B4(a),f);f.tF();g.L(f,f);a.K[c]=f}},Ljb=function(a,b){return function(){var c=g.Ka.apply(0,arguments);
a.isDisposed()||a.ma.push(g.ku.Ji(function(){b.apply(null,g.pa(c))}))}},Ujb=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.jU.prototype.UA=g.ca(19,function(a,b){var c=g.PV(this.Eb());c&&c.UA(a,b)});
var W3={},X3=null;g.nb(Z3,g.Nu);g.k=Z3.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.j)this.progress=0,this.coords=this.B;else if(this.isPlaying())return!1;Y3(this);this.startTime=a=g.lb();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.bJ();this.Xl("play");this.isPaused()&&this.Xl("resume");this.j=1;var b=g.gb(this);b in W3||(W3[b]=this);pib();qib(this,a);return!0};
g.k.stop=function(a){Y3(this);this.j=0;a&&(this.progress=1);rib(this,this.progress);this.Xl("stop");this.jr()};
g.k.pause=function(){this.isPlaying()&&(Y3(this),this.j=-1,this.Xl("pause"))};
g.k.ya=function(){0==this.j||this.stop(!1);this.Xl("destroy");Z3.Pf.ya.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.VK=function(){this.Xl("animate")};
g.k.Xl=function(a){this.dispatchEvent(new sib(a,this))};
g.nb(sib,g.Bb);g.nb($3,Z3);$3.prototype.C=function(){};
$3.prototype.VK=function(){this.C();$3.Pf.VK.call(this)};
$3.prototype.jr=function(){this.C();$3.Pf.jr.call(this)};
$3.prototype.bJ=function(){this.C();$3.Pf.bJ.call(this)};
g.nb(tib,$3);tib.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.w(wib,g.J);g.k=wib.prototype;g.k.Sa=function(a,b,c,d){c=(0,g.ib)(c,d||this.B);a=g.PC(a,b,c);this.j.push(a);return a};
g.k.AI=function(a,b,c,d){c=(0,g.ib)(c,d||this.B);a=nib(a,b,c);this.j.push(a);return a};
g.k.Pc=function(a){g.QC(a);g.Ib(this.j,a)};
g.k.Nf=function(){g.QC(this.j);this.j.length=0};
g.k.ya=function(){this.Nf();g.J.prototype.ya.call(this)};g.w(zib,g.yV);g.k=zib.prototype;g.k.load=function(){g.yV.prototype.load.call(this);if(!c4(this)){var a=g.nRa(this.player.getVideoData());a?(a=yib(a,Aib(this)),d4(this,a,!1)):Bib(this)}};
g.k.unload=function(){d4(this,null);this.C&&(this.C.abort(),this.C=null);g.yV.prototype.unload.call(this)};
g.k.Gh=function(a,b){return c4(this)?"loadCustomEndscreenRenderer"===a?(a=yib(b,"new"),d4(this,a),!0):null:null};
g.k.getOptions=function(){return c4(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.Kb=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<Vjb.length;f++){var h=Math.abs(b.width-Vjb[f]);if(-1===e||d>=h)e=f,d=h}d=Wjb[e];this.B&&g.Qr(this.B.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.j[f],
h=this.G[f],e&&h){var l=h.width*c/h.aspectRatio,m=Math.round(h.width*a.width);f=Math.round(l*a.height);var n=a.left+Math.round(h.left*a.width),p=a.top+Math.round(h.top*a.height);g.$r(e.element,m,f);g.Wr(e.element,n,p);g.Eu(e.element,Xjb);256<m||256<f?g.Bu(e.element,"ytp-ce-large-round"):96<m||96<f?g.Bu(e.element,"ytp-ce-medium-round"):g.Bu(e.element,"ytp-ce-small-round");g.Eu(e.element,Yjb);m=h.left+h.width/2;h=h.top+l/2;g.Bu(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":
.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.Eu(e.element,Wjb);g.Bu(e.element,d);(e=g.jf(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.Qr(e,"height",f+"px")}}}}};
g.k.onCueRangeEnter=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())h4(this,this.endscreen.impressionUrls),(a=g.IF())&&this.endscreen.visualElement&&g.WF(a,this.endscreen.visualElement);else{a=a.getId().substring(15);var b=this.j[a],c=this.G[a];g.Bu(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.Bu(b,"ytp-ce-shown");h4(this,c.impressionUrls);(b=g.IF())&&g.WF(b,c.visualElement);this.player.U().K&&this.player.Qa("endscreenelementshown",
a)}};
g.k.onCueRangeExit=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.j[a];g.Du(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.Du(b,"ytp-ce-shown");this.player.U().K&&this.player.Qa("endscreenelementhidden",a)}};
g.k.V9=function(a){var b=this;a.target===window&&(new g.tu(function(){for(var c=g.u(Object.values(b.j)),d=c.next();!d.done;d=c.next())g.Eu(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var Vjb=[346,426,470,506,570,640,853,1280,1920],Wjb="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),Yjb=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],Xjb=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var Oib={Zqa:"current",XQa:"new"};var Qib={CLOSE:"close",yUa:"openUrl",SUBSCRIBE:"subscribe"},Rib={wpa:"click",CLOSE:"close",wCa:"hidden",FZa:"rollOut",GZa:"rollOver",o0a:"shown"};Tib.prototype.cf=function(){var a=Uib(this,function(b){return"openUrl"===b.type&&null!=b.url});
return a?a.url:null};
var Sjb={kka:"anchored",m0:"branding",CHANNEL:"channel",Pqa:"cta",zCa:"highlightText",AGa:"label",PLAYLIST:"playlist",XWa:"popup",l3a:"speech",SUBSCRIBE:"subscribe",C6a:"title",VIDEO:"video",Ocb:"website"},Rjb={m0:"branding",mna:"card",dta:"drawer",yCa:"highlight",DMa:"marker",AYa:"promotion",TEXT:"text",teb:"widget"};g.w(o4,g.J);g.k=o4.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.fK(a,b,{id:c,namespace:"annotations_module"});d&&this.Za.set(a,d);e&&this.fb.set(a,e);this.context.J.wf([a])};
g.k.tF=function(){this.context.B.subscribe("resize",this.DG,this)};
g.k.Db=function(){return this.element};
g.k.WK=function(a,b,c,d,e,f){if(this.wb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.Af(this.Db())};
g.k.DG=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=j4(a);if(f){var h=ajb(f,a.target),l=function(){a.j&&e.context.J.pauseVideo();var m=e.context.videoData.Pd||!1,n=g.UB(f||"");m&&n&&(n.v||n.list)?e.context.J.zo(n.v,b,n.list,!1):g.mH(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);A4(this.context.logger,c,l,d);$ib(f)||(c=g.IF(),d=b.itct,c&&d&&g.ZF(c,g.GF(d)))}};
g.k.ya=function(){this.Za.clear();this.fb.clear();g.J.prototype.ya.call(this)};
g.k.createElement=function(a){a=new g.U(a);g.L(this,a);return a.element};g.w(cjb,o4);g.k=cjb.prototype;g.k.Zs=function(){this.qa&&t4(this,this.qa)};
g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.J.getRootNode())?(a=g.as(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.DG=function(){var a=this.isAvailable();g.bs(this.Db(),a);g.Fu(this.context.J.getRootNode(),g.YY.IV_DRAWER_ENABLED,a);U3(this.J)};
g.k.destroy=function(){this.J.UA(!1);try{this.J.getRootNode().removeChild(this.D)}catch(a){}g.OE(this.ma);g.VC(this.Ra);this.Va&&this.Va.dispose();this.G&&this.G.dispose();o4.prototype.destroy.call(this)};
g.k.n4=function(){if(this.C){A4(this.context.logger,x4(this).bj.close);var a=g.IF();a&&this.N&&g.ZF(a,this.N);s4(this)}};
g.k.G4=function(){g.Fu(this.D,"iv-drawer-scrolled",0<this.B.scrollTop)};
g.k.J6=function(){var a=g.IF(),b=x4(this);b=b?b.Zf:this.Zf;a&&b&&g.XF(a,[b])};
g.k.I6=function(){var a=g.IF(),b=x4(this);b=b?b.Zf:this.Zf;a&&b&&g.YF(a,[b])};
g.k.N0=function(){var a=x4(this);A4(this.context.logger,a.bj.f_);var b=g.IF();if(b&&a){var c=[];a.yk&&c.push(a.yk);a.Zf&&c.push(a.Zf);0<c.length&&g.XF(b,c)}};
g.k.K6=function(){var a=g.IF(),b=x4(this);a&&b&&g.YF(a,[b.yk])};
g.k.M0=function(a){var b=x4(this),c=g.IF();this.j?a?(a=this.context.logger,A4(a,b.bj.uK),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.yk&&g.ZF(c,b.yk)):(a=this.context.logger,A4(a,b.bj.uK),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.Zf&&g.ZF(c,b.Zf)):(a=this.context.logger,A4(a,b.bj.uK),a.J.sendVideoStatsEngageEvent(4,void 0),c&&this.Zf&&g.ZF(c,this.Zf))};g.w(y4,o4);y4.prototype.tF=function(){o4.prototype.tF.call(this);sjb(this)};
y4.prototype.show=function(){o4.prototype.show.call(this);var a=g.IF(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.XF(a,[g.GF(b.itct)])};
y4.prototype.hide=function(){o4.prototype.hide.call(this);var a=g.IF(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.YF(a,[g.GF(b.itct)])};g.w(z4,y4);
z4.prototype.Mw=function(){g.Bu(this.Db(),"iv-branding");var a=this.annotation.data;this.B=this.createElement({I:"img",Ma:["branding-img","iv-click-target"],W:{"aria-label":"Filigrane de cha\u00eene",src:a.image_url,width:a.image_width,height:a.image_height}});g.bs(this.B,!1);var b=this.createElement({I:"button",Ma:["branding-img-container","ytp-button"]});b.appendChild(this.B);this.Db().appendChild(b);var c=this.annotation.cf();c&&p4(this,b,c,this.annotation.id,a.session_data);wjb(this,a)};
z4.prototype.show=function(){if(!this.isActive&&(y4.prototype.show.call(this),this.N||(this.Mw(),this.N=!0),g.bs(this.Db(),!0),this.isActive=!0,this.B)){try{tjb(this,this.B)}catch(a){}g.Bu(this.context.J.getRootNode(),"ytp-branding-shown")}};
z4.prototype.hide=function(){this.isActive&&(y4.prototype.hide.call(this),g.bs(this.Db(),!1),this.isActive=!1,g.Du(this.context.J.getRootNode(),"ytp-branding-shown"))};
z4.prototype.destroy=function(){this.j&&(this.j.dispose(),this.j=null);y4.prototype.destroy.call(this)};g.w(yjb,y4);g.k=yjb.prototype;
g.k.Mw=function(){var a=this,b=this.annotation.data;if("cta"===this.annotation.style)var c=6;else if("video"===this.annotation.style||"playlist"===this.annotation.style)c=7;this.K=b.collapsedelay_ms||this.K;var d=["iv-promo","iv-promo-inactive"];this.Db().setAttribute("aria-hidden","true");this.Db().setAttribute("aria-label","Promotion");this.Db().tabIndex=0;var e=this.annotation.cf(),f=b.image_url;if(f){var h=this.createElement({I:"div",Ma:["iv-promo-img","iv-click-target"]});f=this.createElement({I:"img",
W:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&!b.is_live?(f=this.createElement({I:"span",S:"iv-promo-video-duration",xa:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=this.createElement({I:"span",S:"iv-promo-playlist-length",xa:b.playlist_length.toString()}),h.appendChild(f));e&&p4(this,h,e,this.annotation.id,b.session_data,void 0,c)}e?(f=this.createElement({I:"a",S:"iv-promo-txt"}),g.zn(f,j4(e)),this.j=f):this.j=this.createElement({I:"div",S:"iv-promo-txt"});switch(this.annotation.style){case "cta":case "website":var l=
this.createElement({I:"p",V:[{I:"strong",xa:b.text_line_1}]});var m=this.createElement({I:"p",V:[{I:"span",S:"iv-promo-link",xa:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=this.createElement({I:"button",Ma:["iv-promo-round-expand-icon","ytp-button"]});f=this.createElement({I:"button",Ma:["iv-button","iv-promo-button"],V:[{I:"span",S:"iv-button-content",xa:f}]});var p=this.createElement({I:"div",S:"iv-promo-button-container"});p.appendChild(f);e&&p4(this,
this.Db(),e,this.annotation.id,b.session_data,void 0,c)}g.Bu(this.j,"iv-click-target");e&&p4(this,this.j,e,this.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=this.createElement({I:"p",V:[{I:"span",xa:b.text_line_1}]}),m=this.createElement({I:"p",V:[{I:"strong",xa:b.text_line_2}]}),b.is_live&&(l=m,m=this.createElement({I:"span",Ma:["yt-badge","iv-promo-badge-live"],xa:"EN DIRECT MAINTENANT"})),g.Bu(this.j,"iv-click-target"),e&&p4(this,this.j,e,this.annotation.id,b.session_data,
void 0,c),d.push("iv-promo-video")}l&&this.j.appendChild(l);m&&this.j.appendChild(m);this.N.appendChild(this.j);p&&this.N.appendChild(p);c=this.createElement({I:"div",S:"iv-promo-actions"});this.B=this.createElement({I:"button",Ma:["iv-promo-expand","ytp-button"]});this.B.title="Agrandir";this.context.j.Sa(this.B,"click",function(q){Bjb(a,5E3,q)});
c.appendChild(this.B);g.bs(this.B,!1);this.context.j.Sa(this.Db(),"mouseover",this.J5,this);this.context.j.Sa(this.Db(),"mouseout",this.I5,this);this.context.j.Sa(this.Db(),"touchend",function(q){Bjb(a,5E3,q)});
this.C=this.createElement({I:"button",Ma:["iv-promo-close","ytp-button"]});this.C.title="Fermer";this.context.j.Sa(this.C,"click","cta"===this.annotation.style&&b.text_line_3?this.E5:this.D5,this);c.appendChild(this.C);g.Cu(this.Db(),d);h&&(g.xf(this.Db(),h),n&&h.appendChild(n));g.xf(this.Db(),this.N);g.xf(this.Db(),c)};
g.k.show=function(){this.isActive||(y4.prototype.show.call(this),this.Y||(this.Mw(),this.Y=!0),g.bs(this.Db(),!0),g.og(function(){g.Du(this.Db(),"iv-promo-inactive")},100,this),this.Db().removeAttribute("aria-hidden"),this.isActive=!0,Djb(this),zjb(this),Ajb(this,this.K))};
g.k.hide=function(){this.isActive&&(g.Bu(this.Db(),"iv-promo-inactive"),this.isActive=!1,this.Db().setAttribute("aria-hidden","true"))};
g.k.WK=function(a,b,c,d,e,f){return this.isCollapsed?!1:y4.prototype.WK.call(this,a,b,c,d,e,f)};
g.k.J5=function(a){this.Z=!0;Bjb(this,500,a)};
g.k.I5=function(){this.Z=!1;Cjb(this)};
g.k.D5=function(a){a.stopPropagation();this.hide()};
g.k.E5=function(a){a.stopPropagation();Djb(this);this.isCollapsed=!0;g.Bu(this.Db(),"iv-promo-collapsed-no-delay");this.G.start()};
g.k.destroy=function(){this.G.dispose();y4.prototype.destroy.call(this)};g.w(Fjb,g.yV);g.k=Fjb.prototype;g.k.Gh=function(a,b){if(!Ujb(this.player.U().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.r2(b))&&Kjb(this,a),!0;case "removeCustomAnnotationById":return b&&this.j&&(gjb(this.j,b),U3(this.player)),!0}return null};
g.k.getOptions=function(){return Ujb(this.player.U().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.Vt=function(){var a=this.player.U(),b=this.player.getVideoData(),c=a.annotationsLoadPolicy||b.annotationsLoadPolicy;return b.Pd&&a.ma||g.cU(this.player.app)?!1:1===c&&!b.oU||a.Na.get(b.videoId)||g.LT(b)||g.oRa(b)?!0:!1};
g.k.jJ=function(){if(this.C){var a=this.player.qb().getVideoContentRect(!0);g.$r(this.C.element,a.width,a.height);g.Wr(this.C.element,a.left,a.top)}if(this.j){var b=this.player.Ok();a=this.j;b=b.width;g.Fu(a.D,"iv-drawer-small",426>=b);g.Fu(a.D,"iv-drawer-big",1280<=b)}};
g.k.O0=function(a){Hjb(this,a.state);g.TG(a.state,2)&&(this.Gk()&&this.So()&&2!==this.player.getPresentingPlayerType()&&this.VA(!1),this.UA(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.G=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.aC(h)&&h.responseXML?h.responseXML:null)&&(Kjb(b,h),g.Bu(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.yV.prototype.load.call(this);Hjb(this,this.player.Sb());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.nD()&&(a=Ljb(this,a));var e={format:"XML",onFinish:a,onError:function(){b.G=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.U().Na.get(d);f&&Mjb(e,f);f=f&&(f.wM||f.IG);if(!c.tB||f)c.Ra?Ijb(this,c.Ra,e):(this.kx=function(){if(!b.N)b.onVideoDataChange(e);var h=b.player.getVideoData();(null==h?0:g.KT(h))&&!b.Y&&Qjb(b,h)},this.player.addEventListener("videodatachange",this.kx));
g.rU(this.player,this.C.element,4);this.jJ();(f=g.LT(c))&&Pjb(this,f);(f=g.oRa(c))&&f.featuredChannel&&Tjb(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null);this.qh=g.lf("ytp-cards-button",this.player.getRootNode());g.KT(c)&&Qjb(this,c)};
g.k.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Ra&&Ijb(this,b.Ra,a)};
g.k.unload=function(){this.player.jf("annotations_module");for(var a=g.u(Object.keys(this.K)),b=a.next();!b.done;b=a.next())this.K[b.value].destroy();this.Z=null;this.j&&(this.j.destroy(),this.j=null,U3(this.player));this.N=!1;this.G&&(this.G.abort(),this.G=null);this.Y=!1;this.K={};this.B.hide();g.yV.prototype.unload.call(this);this.C.detach();this.kx&&(this.player.removeEventListener("videodatachange",this.kx),this.kx=null)};
g.k.IY=function(a){a===this.player.getVideoData().videoId&&(this.loaded?Njb(this):this.load())};
g.k.Gk=function(){var a;return(null==(a=this.j)?void 0:a.isAvailable())||this.Y};
g.k.So=function(){return!!this.j&&this.j.C};
g.k.VA=function(a,b,c){b=void 0===b?!1:b;this.Gk();this.j&&(a?c?r4(this.j,c,b):r4(this.j,"YOUTUBE_DRAWER_AUTO_OPEN",b):s4(this.j))};
g.k.UA=function(a,b){this.player.oa(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.ya=function(){this.player.U().Na.unsubscribe("vast_info_card_add",this.IY,this);g.Du(this.player.getRootNode(),g.YY.IV_DRAWER_OPEN);for(var a=this.ma,b=g.ku,c=0,d=a.length;c<d;c++)b.Jj(a[c]);this.ma.length=0;g.yV.prototype.ya.call(this)};
g.k.createElement=function(a){a=new g.U(a);g.L(this,a);return a.element};g.xV("annotations_module",Fjb);g.xV("creatorendscreen",zib);})(_yt_player);
