(function(g){var window=this;'use strict';var akb=function(a,b){return b?a.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},bkb=function(a,b){var c=new g.GS;
c.languageCode=a.languageCode;c.languageName=a.languageName;c.name=a.name;c.kind=a.kind;c.isDefault=!1;c.j=a.j;c.isTranslateable=a.isTranslateable;c.vssId=a.vssId;c.url=a.url;c.translationLanguage=b;a.xtags&&(c.xtags=a.xtags);a.captionId&&(c.captionId=a.captionId);return c},ckb=function(a,b){var c,d,e;
return g.I(function(f){if(1==f.j)return c=a+"|"+b,g.z(f,g.YD(),2);if(3!=f.j){d=f.B;if(!d)throw g.BD("gct");return g.z(f,g.VS(d),3)}e=f.B;return f.return(e.get("captions",c))})},dkb=function(a,b,c){ckb(a,b).then(function(d){d&&c(d.trackData,new g.GS(d.metadata))})},gkb=function(a){if(!ekb.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(fkb,"#$1$1$2$2$3$3"));a=a.toLowerCase();a=parseInt(a.slice(1),16);return[a>>16,a>>8&255,a&255]},hkb=function(){return g.ZC("yt-player-caption-display-settings")},C4=function(){this.segments=[]},ikb=function(a,b){var c=g.Wb(a.segments,b);
0<=c||0>c&&1===(-c-1)%2||(c=-c-1,0<c&&1===b-a.segments[c-1]&&c<a.segments.length&&1===a.segments[c]-b?(g.Hb(a.segments,c),g.Hb(a.segments,c-1)):0<c&&1===b-a.segments[c-1]?a.segments[c-1]=b:c<a.segments.length&&1===a.segments[c]-b?a.segments[c]=b:(g.Rb(a.segments,c,0,b),g.Rb(a.segments,c+1,0,b)))},jkb=function(a,b,c,d,e,f){g.J.call(this);
this.policy=a;this.player=b;this.ma=c;this.Z=d;this.G=e;this.Y=f;this.D=new C4;this.K=-1;this.C=this.B=this.j=null;this.N=new g.tu(this.wX,1E3,this);this.events=new g.QK(this);g.L(this,this.N);g.L(this,this.events);this.events.T(b,"SEEK_COMPLETE",this.rA);this.rA();this.wX()},kkb=function(a){return a.j&&a.j.D?a.j.D+a.player.Uc()<a.player.getCurrentTime():!1},lkb=function(a,b){var c=g.uMa(b,a.policy,{}).cf(),d={format:"RAW",
withCredentials:!0};if(a.policy.Ea){d.method="POST";var e=b.Xs(),f=(0,g.ZZ)([120,0]);e&&g.UO(e,g.$Ta);d.postBody=f}a.G&&(d.responseType="arraybuffer");a.C=g.jC(c,d,3,100).then(function(h){a:{h=h.xhr;a.isDisposed();if(a.B){var l=!(a.G?h.response:h.responseText)||400<=h.status,m=g.iNa(h);if(m){h=g.uMa(a.B,a.policy,{});a.B.Qk(h,m);lkb(a,a.B);break a}l?a.player.va("capfail",{status:h.status}):(a.player.gi().Ei("fcb_r"),m=a.B.gb[0].Oa,null!=a.Z&&a.K!==m&&(l=a.B.gb[0],a.G?a.Z(h.response,1E3*(l.startTime+
a.player.Uc())):a.Z(h.responseText,1E3*(l.startTime+a.player.Uc())),a.K=m))}a.B=null;a.C=null}}).zk(function(h){a.B=null;
a.C=null;var l;a.player.va("capfail",{status:null==(l=h.xhr)?void 0:l.status})});
a.B=b;ikb(a.D,a.B.gb[0].Oa)},D4=function(a,b){g.BV.call(this,b.U());
this.j=a;this.J=b;this.C=null;this.G=!1;this.K=g.JJ(this.J.U())&&!this.j.isManifestless},nkb=function(a,b){var c=[],d;
for(d in a.j.j)if(a.j.j.hasOwnProperty(d)){var e=a.j.j[d];if(g.AUa(e,b||null)){var f=e.info.id,h=f,l="."+f,m="",n="",p="";if(e=e.info.captionTrack)f=e.languageCode,h=e.displayName,l=e.vssId,m=e.kind,a.J.U().L("html5_expose_xtags_through_caption_track")&&(n=e.xtags),p=e.id;else{e=f;var q=g.Yhb.get(e);null==q&&(q=mkb[e]||mkb[e.replace(/-/g,"_")],g.Yhb.set(e,q));h=q||h}c.push(new g.GS({id:d,languageCode:f,languageName:h,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m,xtags:n,captionId:p}))}}return c},
okb=function(a,b){return null!=b&&b in a.j.j?a.j.j[b]:null},pkb=function(a,b,c){var d=[],e;
for(e in a.j.j)if(a.j.j.hasOwnProperty(e)){var f=a.j.j[e];if(g.AUa(f,c||null)){var h=f.info.captionTrack;h&&h.languageCode===b&&d.push(f)}}return d.length?d[0]:null},qkb=function(){var a=void 0;
a=void 0===a?{}:a;var b="suggest_correction"in g.lib?g.lib.suggest_correction:"Edit caption";b=b||"";var c={},d;for(d in a){c={JD:c.JD};c.JD=d;var e=function(f){return function(){return String(a[f.JD])}}(c);
b=b.replace(new RegExp("\\$\\{"+c.JD+"\\}","gi"),e);b=b.replace(new RegExp("\\$"+c.JD,"gi"),e)}return b},E4=function(a,b,c,d,e,f,h,l,m,n){var p=n.isInline()&&l.ob("web_imp_caption_window"),q=n.isInline()&&!1;
p=p||q;q={};Object.assign(q,b);Object.assign(q,a.params);Object.assign(q,c);var r={};Object.assign(r,b.We);a.params.We&&Object.assign(r,a.params.We);Object.assign(r,c.We);p&&(q.windowOpacity=.6,r.backgroundOpacity=0);q.We=r;var t=1===q.Di,v=[{I:"span",S:"captions-text",W:{style:"word-wrap: normal; display: block;"}}],x,C,F;(l=l.ob("caption_edit_on_hover")&&(null==(x=n.getVideoData().getPlayerResponse())?void 0:null==(C=x.captions)?void 0:null==(F=C.playerCaptionsTracklistRenderer)?void 0:F.openTranscriptCommand))&&
v.unshift({I:"button",S:"caption-edit",W:{tabindex:"0","aria-label":qkb()},V:[{I:"svg",W:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},V:[{I:"path",W:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});g.U.call(this,{I:"div",S:"caption-window",W:{id:"caption-window-"+a.id,dir:t?"rtl":"ltr",tabindex:"0",lang:q.lang},V:v});var G=
this;this.K=[];this.Da=!1;this.B=a;this.Na=this.Ka=null;this.playerWidth=f;this.playerHeight=h;this.N=null;this.maxWidth=.96*f;this.maxHeight=.96*h;this.j=q;this.Tc=c;this.qa=b;this.D=this.Ga("captions-text");this.kc=""!==this.D.style.getPropertyValue("box-decoration-break")||""!==this.D.style.getPropertyValue("-webkit-box-decoration-break");this.Va=rkb(d,e,f,h);this.Xc=m;l&&(this.G=this.Ga("caption-edit"),this.T(this.G,"click",function(){G.Xc()}));
this.type=0;this.fb=this.Va*skb(r);this.Hb=p;a=new g.ZU(this.element,!0);g.L(this,a);a.subscribe("dragstart",this.R0,this);a.subscribe("dragmove",this.Q0,this);a.subscribe("dragend",this.P0,this);this.jb=this.ib=this.yb=this.wb=0;a="";this.j.windowOpacity&&(a=gkb(this.j.windowColor),a="rgba("+a[0]+","+a[1]+","+a[2]+","+this.j.windowOpacity+")");b={"background-color":a,display:!1===this.j.isVisible?"none":"","text-align":tkb[this.j.textAlign]};this.kc&&(b["border-radius"]=a?this.fb/8+"px":"");(this.C=
2===this.B.params.Di||3===this.B.params.Di)&&ukb(this,this.element);g.Qr(this.element,b);if(p){var H;null==(H=this.element.parentElement)||H.style.setProperty("--caption-window-color",a)}switch(this.j.Ul){case 0:case 1:case 2:g.Bu(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.Bu(this.element,"ytp-caption-window-bottom")}},ukb=function(a,b){var c="vertical-rl";
1===a.j.GR&&(c="vertical-lr");g.nf&&(c="vertical-lr"===c?"tb-lr":"tb-rl");g.Qr(b,"-o-writing-mode",c);g.Qr(b,"-webkit-writing-mode",c);g.Qr(b,"writing-mode",c);g.Qr(b,"text-orientation","upright");g.Bu(b,"ytp-vertical-caption");3===a.B.params.Di&&(g.Qr(b,"text-orientation",""),g.Qr(b,"transform","rotate(180deg)"))},skb=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0===a.offset||2===a.offset)b*=.8;return b},vkb=function(a,b){var c={},d=b.background?b.background:a.j.We.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.j.We.backgroundOpacity;d=gkb(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.kc&&(c["box-decoration-break"]="clone",c["border-radius"]=a.fb/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.Va*skb(b)+"px";d=1;e=b.color||a.j.We.color;if(b.color||null!=b.textOpacity)e=gkb(e),d=null==b.textOpacity?a.j.We.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",
c.color=e,c.fill=e;var f=b.charEdgeStyle;0===f&&(f=void 0);if(f){e="rgba(34, 34, 34, "+d+")";var h="rgba(204, 204, 204, "+d+")";b.xM&&(h=e=b.xM);var l=a.Va/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),q=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=q;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+h);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;5>p;p++)d.push("0 0 "+
n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.tC()?
'"Carrois Gothic SC", sans-serif-smallcaps':'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.j.We.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7===b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.italic&&(c["font-style"]=
"italic");b.underline&&(c["text-decoration"]="underline");b.g6&&(c.visibility="hidden");1===b.OW&&a.C&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.vS||g.AD,3===a.B.params.Di?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(1===b.Xn||2===b.Xn||3===b.Xn||4===b.Xn||5===b.Xn)if(g.vS)c["font-weight"]="bold";else switch(c["text-emphasis-style"]="filled circle",c["text-emphasis-color"]="currentcolor",c["webkit-text-emphasis"]="filled circle",b.Xn){case 4:case 3:c["text-emphasis-position"]=
"under left";c["webkit-text-emphasis-position"]="under left";break;case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},F4=function(a){a=a.split("px");
return 0<a.length?(a=Number(a[0]))?a:0:0},wkb=function(a){a.N=g.vf("SPAN");
g.Qr(a.N,{display:"block"});g.Bu(a.N,"caption-visual-line");a.D.appendChild(a.N)},xkb=function(a,b){var c=g.vf("SPAN");
g.Qr(c,{display:"inline-block","white-space":"pre-wrap"});g.Qr(c,vkb(a,b));c.classList.add("ytp-caption-segment");a.N.appendChild(c);c.previousElementSibling&&(g.Qr(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.Qr(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},ykb=function(a,b,c){a.Da=a.Da||!!c;
var d={};Object.assign(d,a.j.We);Object.assign(d,c||b.j);Object.assign(d,a.Tc.We);(c=!a.N)&&wkb(a);for(var e=a.Ka&&a.Na&&g.pd(d,a.Na)?a.Ka:xkb(a,d),f="string"===typeof b.text,h=f?b.text.split("\n"):[b.text],l=0;l<h.length;l++){var m=0<l||!b.append,n=h[l];m&&!c?(wkb(a),e=xkb(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.wf(n):n),f||"RUBY"!==n.tagName||4!==n.childElementCount||g.vS||!g.Sr(n.children[2],"text-emphasis")||(m=a.C?"padding-right":"padding-top",g.Sr(n.children[2],"text-emphasis-position")&&(m=
a.C?"padding-left":"padding-bottom"),g.Rc?g.Qr(e,m,"1em"):g.Qr(e,m,"0.5em")))}a.Na=d;a.Ka=e;a.K.push(b)},rkb=function(a,b,c,d){var e=b/360*16;
b>=a&&(a=640,d>1.3*c&&(a=480),e=c/a*16);return e},Akb=function(){this.C=this.time=this.mode=this.B=0;
this.D=new zkb(this);this.G=new zkb(this);this.j=[];this.clear()},Ckb=function(a,b,c){if(255===a&&255===b||!a&&!b)return{Mu:a,
xs:b,result:0};a=Bkb[a];b=Bkb[b];if(a&128){var d;if(d=!(b&128))d=b,d=c.Ie()&&c.xs===d;if(d)return{Mu:a,xs:b,result:1}}else if(b&128&&1<=a&&31>=a)return{Mu:a,xs:b,result:2};return{Mu:a,xs:b,result:3}},Ekb=function(a,b,c,d){255===b&&255===c||!b&&!c?(45===++a.C&&a.reset(),a.D.B.clear(),a.G.B.clear()):(a.C=0,Dkb(a.D,b,c,d))},Fkb=function(a,b){a.j.sort(function(e,f){var h=e.time-f.time;
return 0===h?e.order-f.order:h});
for(var c=g.u(a.j),d=c.next();!d.done;d=c.next())d=d.value,a.time=d.time,0===d.type?Ekb(a,d.WU,d.XU,b):1===d.type&&a.B&496&&Dkb(a.G,d.WU,d.XU,b);a.j.length=0},G4=function(){this.type=0},H4=function(){this.state=this.xs=this.Mu=0},Gkb=function(){this.timestamp=this.j=0},I4=function(a){this.D=a;
this.B=[];this.j=this.col=this.row=0;this.style=new G4;for(a=this.C=0;15>=a;a++){this.B[a]=[];for(var b=0;32>=b;b++)this.B[a][b]=new Gkb}},J4=function(a,b){if(3===a.style.type){for(var c=0,d=0,e=a.D.time+0,f="",h="",l=e,m=1;15>=m;++m){for(var n=!1,p=d?d:1;32>=p;++p){var q=a.B[m][p];
if(0!==q.j){0===c&&(c=m,d=p);n=String.fromCharCode(q.j);var r=q.timestamp;r<e&&(e=r);q.timestamp=l;h&&(f+=h,h="");f+=n;n=!0}if((0===q.j||32===p)&&n){h="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.D(c,d,e,l,f)}else for(d=c=0,f=e=a.D.time+0,h=1;15>=h;++h)for(l="",m=1;32>=m;++m)if(p=a.B[h][m],q=p.j,0!==q&&(0===c&&(c=h,d=m),n=String.fromCharCode(q),r=p.timestamp,r<=e&&(e=r),l+=n,p.reset()),32===m||0===q)l&&b.D(c,d,e,f,l),e=f,l="",d=c=0},Lkb=function(a,b){switch(a){case 0:return Hkb[(b&127)-32];
case 1:return Ikb[b&15];case 2:return Jkb[b&31];case 3:return Kkb[b&31]}return 0},K4=function(a){return a.B[a.row][a.col]},L4=function(a,b,c){2<=b&&1<a.col&&(--a.col,K4(a).j=0);
var d=K4(a);d.timestamp=a.D.time+0;d.j=Lkb(b,c);32>a.col&&a.col++},Mkb=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++){var h=a.B[b+e][f],l=a.B[c+e][f];
h.j=l.j;h.timestamp=l.timestamp}},M4=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.B[b+d][e].reset()},Nkb=function(a){a.row=0<a.j?a.j:1;
a.col=1;M4(a,0,15)},Okb=function(a){this.C=a;
this.G=0;this.style=new G4;this.K=new I4(this.C);this.N=new I4(this.C);this.text=new I4(this.C);this.B=this.K;this.D=this.N;this.j=this.B},Pkb=function(a,b,c){var d=a.B,e=!1;
switch(a.style.get()){case 4:case 1:case 2:4===a.style.get()&&0<d.j||(J4(d,c),Nkb(a.B),Nkb(a.D),d.row=15,d.j=b,e=!0)}a.style.set(3);a.j=d;a.j.style=a.style;a.C.mode=1<<d.C;e?d.col=1:d.j!==b&&(d.j>b?(J4(d,c),M4(d,d.row-d.j,b)):d.row<b&&(b=d.j),d.j=b)},Qkb=function(a){a.style.set(1);
a.j=a.D;a.j.j=0;a.j.style=a.style;a.C.mode=1<<a.j.C},Rkb=function(a){a.style.set(4);
a.j=a.text;a.j.style=a.style;a.C.mode=1<<a.j.C},zkb=function(a){this.j=a;
this.G=0;this.C=new Okb(this.j);this.K=new Okb(this.j);this.B=new H4;this.D=this.C},Dkb=function(a,b,c,d){a.B.update();
b=Ckb(b,c,a.B);switch(b.result){case 0:return;case 1:case 2:return}var e=b.Mu;c=b.xs;if(32<=e||!e)a.j.mode&a.j.B&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.D.j,b&96&&L4(a,0,b),c&96&&L4(a,0,c),0!==b&&0!==c&&3===a.style.type&&J4(a,d));else if(e&16)a:if(!a.B.matches(e,c)&&(b=a.B,b.Mu=e,b.xs=c,b.state=2,b=e&8?a.K:a.C,a.D=b,a.j.mode=1<<(a.G<<2)+(b.G<<1)+(4===b.style.type?1:0),(a.j.mode|1<<(a.G<<2)+(b.G<<1)+(4!==b.style.type?1:0))&a.j.B))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];
a=c&16?4*((c&14)>>1):0;c=b.j;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!==c.row){if(d<c.j&&(d=c.j,d===c.row))break;var f=1+c.row-c.j,h=1+d-c.j;Mkb(c,h,f,c.j);b=f;e=c.j;h<f?(f=h+e-f,0<f&&(b+=f,e-=f)):(f=f+e-h,0<f&&(e-=f));M4(c,b,e)}}c.row=d;c.col=a+1}else switch(e&7){case 1:switch(c&112){case 32:L4(b.j,0,32);break a;case 48:57===c?(d=b.j,K4(d).j=0,32>d.col&&d.col++):L4(b.j,1,c&15)}break;case 2:c&32&&L4(b.j,2,c&31);break;case 3:c&32&&L4(b.j,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:Qkb(b);
break;case 33:d=b.j;1<d.col&&(--d.col,K4(d).j=0);break;case 36:d=b.j;b=K4(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.B[a][c]===b){for(;32>=c;c++)d.B[a][c].reset();break}break;case 37:Pkb(b,2,d);break;case 38:Pkb(b,3,d);break;case 39:Pkb(b,4,d);break;case 40:L4(b.j,0,32);break;case 41:b.style.set(2);b.j=b.B;b.j.j=0;b.j.style=b.style;b.C.mode=1<<b.j.C;break;case 42:d=b.text;d.j=15;d.style.set(4);Nkb(d);Rkb(b);break;case 43:Rkb(b);break;case 44:a=b.B;switch(b.style.get()){case 1:case 2:case 3:J4(a,
d)}M4(a,0,15);break;case 45:b:{a=b.j;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.col=1;break b}case 3:}2>a.j&&(a.j=2,a.row<a.j&&(a.row=a.j));b=a.row-a.j+1;J4(a,d);Mkb(a,b,b+1,a.j-1);M4(a,a.row,1)}break;case 46:M4(b.D,0,15);break;case 47:J4(b.B,d),b.D.updateTime(b.C.time+0),d=b.D,b.D=b.B,b.B=d,Qkb(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.j,32<(d.col+=c&3)&&(d.col=32)}}},Skb=function(){},N4=function(a,b,c,d,e,f,h){f=void 0===f?!1:f;
h=void 0===h?null:h;g.fK.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.append=f;this.j=h},Ukb=function(a,b,c,d,e,f,h){var l=f[0],m=h[l.getAttribute("p")];
if(1===m.dg){var n=f[1],p=f[2];f=f[3];l.getAttribute("t");n.getAttribute("t");p.getAttribute("t");f.getAttribute("t");l.getAttribute("p");n.getAttribute("p");f.getAttribute("p");h=h[p.getAttribute("p")];l=Tkb(l.textContent,n.textContent,p.textContent,f.textContent,h);return new N4(a,b,e,c,l,d,m)}switch(m.dg){case 9:case 10:m.Xn=1;break;case 11:m.Xn=2;break;case 12:m.Xn=3;break;case 13:m.Xn=4;break;case 14:m.Xn=5}return new N4(a,b,e,c,l.textContent||"",d,m)},Tkb=function(a,b,c,d,e){var f=g.tC(),h=
f?g.vf("DIV"):g.vf("RUBY"),l=g.vf("SPAN");
l.textContent=a;h.appendChild(l);a=f?g.vf("DIV"):g.vf("RP");a.textContent=b;h.appendChild(a);b=f?g.vf("DIV"):g.vf("RT");b.textContent=c;h.appendChild(b);c=e.dg;if(10===c||11===c||12===c||13===c||14===c)if(g.Qr(b,"text-emphasis-style","filled circle"),g.Qr(b,"text-emphasis-color","currentcolor"),g.Qr(b,"webkit-text-emphasis","filled circle"),11===e.dg||13===e.dg)g.Qr(b,"webkit-text-emphasis-position","under left"),g.Qr(b,"text-emphasis-position","under left");c=!0;if(4===e.dg||7===e.dg||12===e.dg||
14===e.dg)g.Qr(h,"ruby-position","over"),g.Qr(h,"-webkit-ruby-position","before");else if(5===e.dg||6===e.dg||11===e.dg||13===e.dg)g.Qr(h,"ruby-position","under"),g.Qr(h,"-webkit-ruby-position","after"),c=!1;e=f?g.vf("DIV"):g.vf("RP");e.textContent=d;h.appendChild(e);f&&(d=c,g.Qr(h,{display:"inline-block",position:"relative"}),f=h.firstElementChild.nextElementSibling,g.Qr(f,"display","none"),f=f.nextElementSibling,g.Qr(f,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.Qr(h.lastElementChild,"display","none"),d?(g.Qr(h,"padding-top","0.6em"),g.Qr(f,"top","0")):(g.Qr(h,"padding-bottom","0.6em"),g.Qr(f,"bottom","0")));return h},O4=function(){g.J.apply(this,arguments)},P4=function(a,b,c,d,e){g.fK.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.j=[]},Vkb=function(a){var b="_"+Q4++;
return new P4(0,0x8000000000000,0,b,a)},R4=function(a){O4.call(this);
this.D=a;this.pens={};this.Z={};this.Y={};this.G="_"+Q4++;this.N={};this.C=this.j=null;this.K=!0},S4=function(a,b){a=a.getAttribute(b);
if(null!=a)return Number(a)},T4=function(a,b){a=a.getAttribute(b);
if(null!=a)return"1"===a},U4=function(a,b){a=S4(a,b);
return void 0!==a?a:null},W4=function(a,b){a=a.getAttribute(b);
if(null!=a)return V4.test(a),a},Wkb=function(a,b){var c={},d=b.getAttribute("ws");
Object.assign(c,d?a.Y[d]:a.D);a=U4(b,"mh");null!=a&&(c.eA=a);a=U4(b,"ju");null!=a&&(c.textAlign=a);a=U4(b,"pd");null!=a&&(c.Di=a);a=U4(b,"sd");null!=a&&(c.GR=a);a=W4(b,"wfc");null!=a&&(c.windowColor=a);b=S4(b,"wfo");void 0!==b&&(c.windowOpacity=b/255);return c},Xkb=function(a,b){var c={},d=b.getAttribute("wp");
d&&Object.assign(c,a.Z[d]);a=U4(b,"ap");null!=a&&(c.Ul=a);a=S4(b,"cc");null!=a&&(c.Cs=a);a=S4(b,"ah");null!=a&&(c.dk=a);a=S4(b,"rc");null!=a&&(c.Ar=a);b=S4(b,"av");null!=b&&(c.Yn=b);return c},Ykb=function(a,b,c,d){var e={};
Object.assign(e,Xkb(a,b));Object.assign(e,Wkb(a,b));d?g.pd(e,a.D)?(d=a.G,e=a.D):d="_"+Q4++:d=b.getAttribute("id")||"_"+Q4++;a=S4(b,"t")+c;b=S4(b,"d")||0x8000000000000;if(2===e.Di||3===e.Di)c=e.Ar,e.Ar=e.Cs,e.Cs=c;return new P4(a,b,0,d,e)},X4=function(a){O4.call(this);
this.K=a;this.j=new Map;this.D=new Map;this.G=new Map;this.C=new Map},Y4=function(a){a=g.re(Math.round(a),0,16777215).toString(16).toUpperCase();
return"#000000".substr(0,7-a.length)+a},Zkb=function(a,b,c,d,e){0===d&&(d=0x8000000000000);
var f={};b.wpWinPosId&&Object.assign(f,a.D.get(b.wpWinPosId));b.wsWinStyleId&&Object.assign(f,a.G.get(b.wsWinStyleId));a=b.rcRowCount;void 0!==a&&(f.Ar=a);b=b.ccColCount;void 0!==b&&(f.Cs=b);if(2===f.Di||3===f.Di)b=f.Ar,f.Ar=f.Cs,f.Cs=b;return new P4(c,d,0,e,f)},Z4=function(a,b,c,d){g.BV.call(this,a);
this.videoData=b;this.audioTrack=c;this.Xa=d;this.D=b.tx},$4=function(a,b,c,d,e,f,h,l,m,n){E4.call(this,a,b,c,d,e,f,h,l,m,n);
this.type=1},a5=function(a,b,c){this.trackData=a;
this.K=c;this.version=this.G=this.C=this.byteOffset=0;this.j=new DataView(this.trackData);this.B=[]},b5=function(a){var b=a.byteOffset;
a.byteOffset+=1;return a.j.getUint8(b)},c5=function(a){var b=a.byteOffset;
a.byteOffset+=4;return a.j.getUint32(b)},d5=function(a,b){O4.call(this);
this.C=a;this.D=b;this.track="CC3"===this.D.languageName?4:0;this.j=new Akb;this.j.B=1<<this.track},alb=function(a){if("string"===typeof a)return!1;
a=new a5(a,8,0);return $kb(a)},$kb=function(a){if(!(a.byteOffset<a.j.byteLength)||1380139777!==c5(a))return!1;
a.version=b5(a);if(1<a.version)return!1;b5(a);b5(a);b5(a);return!0},e5=function(a,b,c,d,e,f,h,l,m,n){E4.call(this,a,b,c,d,e,f,h,l,m,n);
var p=this;this.type=2;this.Aa=[];this.ma=this.Y=this.Ra=0;this.Ea=NaN;this.Yb=0;this.qc=null;this.Za=new g.tu(this.c9,433,this);this.G&&(n.xb(this.G,this,167342),this.T(this.G,"click",function(){n.tb(p.G)}),a=new g.ZU(this.element,!0),g.L(this,a),a.subscribe("hoverstart",function(){n.Wa(p.G,!0)},this));
g.Bu(this.element,"ytp-caption-window-rollup");g.L(this,this.Za);g.Qr(this.element,"overflow","hidden")},blb=function(a,b){if(!b)return"";
a.C&&1!==a.B.params.GR&&(b*=-1);return"translate"+(a.C?"X":"Y")+"("+b+"px)"},clb=function(a){a.Aa=Array.from(document.getElementsByClassName("caption-visual-line"));
for(var b=a.B.params.Ar,c=0,d=0,e=a.Aa.length-1;c<b&&-1<e;){var f=a.Aa[e];d+=a.C?f.offsetWidth:f.offsetHeight;c++;e--}a.Y=d;b=Math;c=b.max;isNaN(a.Ea)&&((d=a.j.Cs)?(e=g.vf("SPAN"),g.Gf(e,"\u2013".repeat(d)),g.Qr(e,vkb(a,a.j.We)),a.D.appendChild(e),a.Ea=e.offsetWidth,a.D.removeChild(e)):a.Ea=0);d=a.D;a.ma=c.call(b,a.Ea,a.Yb,(a.C?d.offsetHeight:d.offsetWidth)+1)},dlb=function(a,b){clb(a);
var c=a.Aa.reduce(function(f,h){return(a.C?h.offsetWidth:h.offsetHeight)+f},0);
c=a.Y-c;if(c!==a.Ra){var d=0<c&&0===a.Ra,e=c<a.Ra;b||isNaN(c)||d||!e||(g.Bu(a.element,"ytp-rollup-mode"),g.uu(a.Za));g.Qr(a.D,"transform",blb(a,c));a.Ra=c}clb(a)},f5=function(){O4.call(this)},elb=function(a,b,c,d,e,f,h,l,m){switch(h.tagName){case "b":l.bold=!0;
break;case "i":l.italic=!0;break;case "u":l.underline=!0}for(var n=0;n<h.childNodes.length;n++){var p=h.childNodes[n];if(3===p.nodeType)p=new N4(b,c,d,e.id,p.nodeValue,f||0<n,g.kd(l)?void 0:l),m.push(p),e.j.push(p);else{var q={};Object.assign(q,l);elb(a,b,c,d,e,!0,p,q,m)}}},flb=function(a){var b=a.split(":");
a=0;b=g.u(b);for(var c=b.next();!c.done;c=b.next())a=60*a+Number(c.value);return 1E3*a},glb=function(a,b,c,d){d=Object.assign({eA:0},d);
return new P4(a,b,c,"_"+Q4++,d)},g5=function(a,b){g.J.call(this);
this.J=a;this.X=b;this.j=null;this.B=this.J.mz()},mlb=function(a,b,c,d,e){d=d||0;
e=e||0;if(a.B&&b){var f=e,h=hlb(a,b,d),l=[];try{for(var m=g.u(h),n=m.next();!n.done;n=m.next()){var p=n.value,q=p.trackData,r=p.zR;l="string"!==typeof q?l.concat(ilb(a,c,q,r,f)):"WEBVTT"===q.substring(0,6)?l.concat(jlb(a,q,r)):l.concat(klb(a,c,q,r))}var t=l}catch(v){g.LF(v),a.clear(),t=[]}if(0!==t.length)return t}b=llb(b);if(!b)return[];try{return"string"!==typeof b?ilb(a,c,b,d,e):"WEBVTT"===b.substring(0,6)?jlb(a,b,d):klb(a,c,b,d)}catch(v){return g.LF(v),a.clear(),[]}},llb=function(a){if("string"===
typeof a||alb(a))return a;
var b=new DataView(a);if(8>=b.byteLength||1718909296!==b.getUint32(4))return"";b=g.lQ(b,0,1835295092);if(!b||!b.size)return"";a=new Uint8Array(a,b.dataOffset,b.size-(b.dataOffset-b.offset));return g.zO(a)},hlb=function(a,b,c){if("string"===typeof b||alb(b))return[{trackData:b,
zR:c}];var d=new DataView(b);if(8>=d.byteLength||1718909296!==d.getUint32(4))return[];var e=g.RLa(d);if(a.B&&e){var f=g.ILa(e),h=g.JLa(e);e=e.j;f&&e&&a.B.LF(e,f,h)}a=g.sQ(d,1835295092);if(!a||!a.length||!a[0].size)return[];f=[];for(h=0;h<a.length;h++)e=a[h],e=new Uint8Array(b,e.dataOffset,e.size-(e.dataOffset-e.offset)),e=g.zO(e),f.push({trackData:e,zR:c+1E3*h});nlb(d,f,c);return f=f.filter(function(l){return!!l.trackData})},nlb=function(a,b,c){var d=g.lQ(a,0,1836476516),e=9E4;
d&&(e=g.mQ(d)||9E4);d=0;for(var f=g.sQ(a,1836019558),h=0;h<f.length;h++){var l=f[h];h<b.length&&(l=g.lQ(a,l.dataOffset,1953653094))&&(l=g.lQ(a,l.dataOffset,1952867444))&&(l=g.OLa(l)/e*1E3,0===h&&(d=l),b[h].zR=l-d+c||c*h*1E3)}},ilb=function(a,b,c,d,e){if(!alb(c))throw Error("Invalid binary caption track data");
a.j||(a.j=new d5(e,b));return a.j.B(c,d)},jlb=function(a,b,c){a.j||(a.j=new f5);
a=a.j.B(b,c);.01>Math.random()&&g.MF(Error("Deprecated subtitles format in web player: WebVTT"));return a},klb=function(a,b,c,d){if("{"===c[0])try{return a.j||(a.j=new X4(olb(b))),a.j.B(c,d)}catch(f){return g.LF(f),[]}var e=g.r2(c);
if(!e||!e.firstChild)throw a=Error("Invalid caption track data"),a.params=c,a;if("timedtext"===e.firstChild.tagName){if(3===Number(e.firstChild.getAttribute("format")))return a.j||(a.j=new R4(olb(b),a.X)),a.j.B(e,d);a=Error("Unsupported subtitles format in web player (Format2)");a.params=c;throw a;}if("transcript"===e.firstChild.tagName)throw a=Error("Unsupported subtitles format in web player (Format1)"),a.params=c,a;a=Error("Invalid caption track data");a.params=c;throw a;},olb=function(a){var b=
{};
if(a=g.JS(a))b.lang=a,g.oeb.test(a)&&(b.Di=1);return b},h5=function(a){g.yV.call(this,a);
var b=this;this.J=a;this.X=this.J.U();this.videoData=this.J.getVideoData();this.yb=this.J.qb();var c;this.jb=null==(c=this.J.getVideoData(1))?void 0:g.ST(c);this.C={We:{}};this.G={We:{}};this.Da=[];this.qa={};this.Va={};this.Y=!1;this.kc=g.TT(this.videoData);this.ib=g.BUa(this.videoData,this.J);this.Yb=!!this.videoData.captionTracks.length;this.qc=!!this.videoData.Id;this.Za="3"===this.X.controlsType;this.j=this.N=this.Z=this.Ra=this.wb=null;this.fb=new g5(this.J,this.X);this.B=null;this.Aa=new g.QK(this);
this.K=new g.U({I:"div",S:"ytp-caption-window-container",W:{id:"ytp-caption-window-container"}});this.ma={top:0,right:0,bottom:0,left:0,width:1,height:1};c=null;var d=g.kv("yt-html5-player-modules::subtitlesModuleData");d&&(c=new g.Zu(d));this.storage=c;var e;this.Nb=!(null==(e=a.yf())||!e.DF());this.D=plb(this);this.Ea=!this.D&&this.Za&&this.Nb&&this.ib;g.L(this,this.fb);this.D?this.Na=this.Ka=null:(this.Ka=new g.qu(this.UR,void 0,this),g.L(this,this.Ka),this.Na=new g.tu(this.C$,2E3,this),g.L(this,
this.Na));g.L(this,this.Aa);g.rU(this.player,this.K.element,4);g.L(this,this.K);this.D||this.Aa.T(a,"resize",this.WR);(this.Hb=g.fS(this.X)&&!g.KC()&&!this.J.isFullscreen()&&!this.D&&!this.Ea)&&this.Aa.T(a,"resize",this.k8);this.Aa.T(a,"onPlaybackAudioChange",this.A7);this.Aa.T(a,g.gK("captions"),function(f){b.onCueRangeEnter(f)});
this.Aa.T(a,g.hK("captions"),function(f){b.onCueRangeExit(f)});
this.jb&&this.Aa.T(a,"videodatachange",function(f,h){b.onVideoDataChange(f,h)});
qlb(this,hkb()||{});this.player.Qa("onCaptionsModuleAvailable")},tlb=function(a){if(1===a.X.Hb||1===a.videoData.ME||"alwayson"===g.BT(a.videoData,"yt:cc"))return!0;
if(a.videoData.captionTracks.length)var b=a.getAudioTrack().B;if(2===a.X.Hb){if(g.sS(a.X))var c=rlb(a);else if(a.storage)try{c=a.storage.get("module-enabled")}catch(e){a.storage.remove("module-enabled")}else c=null;if(null!=c)return!!c}c=akb(a.player.getAudioTrack(),g.sS(a.X));var d=g.BT(a.videoData,"yt:cc");if(void 0===slb(a)){if("CAPTIONS_INITIAL_STATE_ON_RECOMMENDED"===c)return d?"on"===d:!0;if("CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED"===c)return"on"===d}else return"on"===d;return"ON"===b||"on"===
g.BT(a.videoData,"yt:cc")},i5=function(a,b){if(a.B&&(void 0===b||!b)||!a.videoData.captionTracks.length)return!1;
a=a.getAudioTrack();return!!a.j||"FORCED_ON"===a.B},slb=function(a){var b=void 0,c=g.dD(g.cD(),65);
if(g.sS(a.X)&&null!=c){if(null!=rlb(a))return!1;b=!c}return b},ulb=function(a){var b;
a.kc?b=new Z4(a.X,a.videoData,a.getAudioTrack(),a.player):a.ib?b=new D4(a.videoData.j,a.player):a.Yb?b=new g.CV(a.X,a.videoData,a.getAudioTrack()):b=new g.HV(a.X,a.videoData.Id,a.videoData.videoId,g.wRa(a.videoData),a.videoData.Nm,a.videoData.eventId);return b},k5=function(a,b){if(a.j){if(a.N&&a.N.D)return a.N.D;
g.tT(a.videoData)&&(b=!0);b||(b=a.qc?!1:a.Yb?!1:!0);b=b||vlb(a);b=g.zV(a.j.B,b);var c=null;if(g.sS(a.X)){var d=a.J.isInline()?void 0:g.ZC("yt-player-caption-sticky-language");for(var e=[d,a.videoData.captionsLanguagePreference,a.X.captionsLanguagePreference,g.BT(a.videoData,"yt:cc_default_lang")],f=!1,h=0;h<e.length;h++){var l=e[h];if(l){f=!0;for(var m=0;m<b.length;m++)if(g.JS(b[m])===l)return b[m];for(m=0;m<b.length;m++)if(g.JS(b[m]).split("-")[0]===l.split("-")[0])return b[m]}}if(f&&a.j&&(e=a.j.D,
e.length))for(e=g.u(e),f=e.next();!f.done;f=e.next())if(f=f.value,f.languageCode===d){c=f;break}}else for(d=[a.videoData.captionsLanguagePreference,a.X.captionsLanguagePreference,g.BT(a.videoData,"yt:cc_default_lang")],e=0;e<d.length;e++)for(f=0;f<b.length;f++)if(g.JS(b[f])===d[e])return b[f];d=null;a.N&&a.N.C&&(d=a.N.C);d||(d=b.find(function(n){return n.isDefault})||null);
d||(d=b[0]||j5(a));d&&c&&g.JS(d).split("-")[0]!==c.languageCode.split("-")[0]&&(d=bkb(d,c));return d}return null},j5=function(a){return a.N&&a.N.j},l5=function(a){var b=j5(a);
return!!b&&a.B===b},wlb=function(a){var b=akb(a.player.getAudioTrack(),g.sS(a.X)),c;
"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===b?c=k5(a,a.Y):"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===b&&i5(a)?c=j5(a):slb(a)||a.Y||tlb(a)?c=k5(a,a.Y):i5(a)&&(c=j5(a));if(a.D||a.Ea){var d=g.zV(a.j.B,!0);b=[];for(var e=0;e<d.length;e++){var f=d[e],h=g.vf("TRACK");h.setAttribute("kind","subtitles");h.setAttribute("label",g.HS(f));h.setAttribute("srclang",g.JS(f));h.setAttribute("id",f.toString());a.Ea||h.setAttribute("src",a.j.Dv(f,"vtt"));f===c&&h.setAttribute("default","1");b.push(h)}c=a.J.yf();c.gC(b);c=
c.Db();a.Nb&&a.Aa.T(c.textTracks,"change",a.K9)}else!a.B&&c&&m5(a,c),a.player.Qa("onCaptionsTrackListChanged"),a.player.Qa("onApiChange")},xlb=function(a,b){var c=a.J.yf().Db().textTracks;
a=a.B.toString();for(var d=0;d<c.length;d++){var e=c[d];e.id===a&&(b?"showing"!==e.mode&&(e.mode="showing"):"showing"===e.mode&&(e.mode="disabled"))}},m5=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.Y=c,a.Y&&(g.sS(a.X)?n5(a,!!b):o5(a,!!b)));a.B=b;i5(a)&&(a.B=j5(a));var d;ylb(a,null!=(d=a.B)?d:void 0);a.load()},Alb=function(a,b){if(b instanceof P4){var c=a.qa[b.id];
c&&c.B!==b&&(c.dispose(),delete a.qa[b.id],c=null);c||(c=zlb(a,b))&&(a.qa[b.id]=c)}else c=b.windowId,a.Va[c]||(a.Va[c]=[]),a.Va[c].push(b)},zlb=function(a,b){var c=Blb(a);
if(!c)return null;var d=a.B?g.JS(a.B):null;d&&g.oeb.test(d)&&(b.params.Di=1);var e=a.yb.getPlayerSize();d=e.height*a.ma.height;e=e.width*a.ma.width;"google-live"!==a.X.playerStyle||a.C.isDefault||Object.assign(b.params,a.C);switch(null!=b.params.eA?b.params.eA:1<b.j.length?1:0){case 1:return new $4(b,a.C,a.G,c.width,c.height,e,d,a.X.experiments,a.XK.bind(a),a.J);case 2:return new e5(b,a.C,a.G,c.width,c.height,e,d,a.X.experiments,a.XK.bind(a),a.J);default:return new E4(b,a.C,a.G,c.width,c.height,e,
d,a.X.experiments,a.XK.bind(a),a.J)}},qlb=function(a,b,c){c=void 0===c?!1:c;
var d=p5.We;a.C={};Object.assign(a.C,p5);a.C.We={};Object.assign(a.C.We,d);a.G={We:{}};var e=b.backgroundOverride?a.G:a.C,f=b.background||d.background;V4.test(f);e.We.background=f;e=b.colorOverride?a.G:a.C;f=b.color||d.color;V4.test(f);e.We.color=f;e=b.windowColorOverride?a.G:a.C;f=b.windowColor||p5.windowColor;V4.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.G:a.C;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.We.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.G:a.C;f=b.fontSizeIncrement;
null==f&&(f=d.fontSizeIncrement);e.We.fontSizeIncrement=f;f=b.fontStyleOverride?a.G:a.C;e=b.fontStyle;null==e&&(e=d.bold&&d.italic?3:d.bold?1:d.italic?2:0);f=f.We;switch(e){case 1:f.bold=!0;delete f.italic;break;case 2:delete f.bold;f.italic=!0;break;case 3:f.bold=!0;f.italic=!0;break;default:delete f.bold,delete f.italic}e=b.textOpacityOverride?a.G:a.C;f=b.textOpacity;null==f&&(f=d.textOpacity);e.We.textOpacity=f;e=b.windowOpacityOverride?a.G:a.C;f=b.windowOpacity;null==f&&(f=p5.windowOpacity);e.windowOpacity=
f;e=b.charEdgeStyleOverride?a.G:a.C;f=b.charEdgeStyle;null==f&&(f=d.charEdgeStyle);e.We.charEdgeStyle=f;e=b.fontFamilyOverride?a.G:a.C;f=b.fontFamily;null==f&&(f=d.fontFamily);e.We.fontFamily=f;a.loaded&&a.WR();c&&g.YC("yt-player-caption-display-settings",b,2592E3)},Dlb=function(a,b,c){b&&!a.Z?(b=Vkb({Di:0,
lang:"fr"}),a.Z=[b,new N4(b.start,b.end-b.start,0,b.id,null!=c?c:"Aper\u00e7u des sous-titres")],a.player.wf(a.Z)):!b&&a.Z&&(Clb(a,a.Z),a.Z=null)},Clb=function(a,b){a.player.Np(b);
b=g.u(b);for(var c=b.next();!c.done;c=b.next())g.Ib(a.Da,c.value);g.ru(a.Ka)},ylb=function(a,b){a.X.L("html5_modify_caption_vss_logging")&&(a.videoData.CB=b)},Blb=function(a){var b=a.yb.getVideoContentRect(!0).height,c=a.yb.getVideoContentRect(!0).width;
if(!b||!c)return null;b*=a.ma.height;c*=a.ma.width;return{width:c,height:b}},o5=function(a,b){if(a.storage)try{a.storage.set("module-enabled",b)}catch(c){}},n5=function(a,b){a.J.isInline()||g.YC("yt-player-sticky-caption",b,2592E3)},rlb=function(a){if(!a.J.isInline())return g.ZC("yt-player-sticky-caption")},plb=function(a){var b,c=!(null==(b=a.J.yf())||!b.CF());
return a.Za&&c&&!a.ib},vlb=function(a){return a.X.L("web_deprecate_always_includes_asr_setting")&&g.sS(a.X)?!0:!!g.dD(g.cD(),66)};
g.wY.prototype.WC=g.ca(41,function(a){var b=2;this.N.has(a)?b=0:g.U_a(this,a)&&(b=1);return b});
g.Q_.prototype.WC=g.ca(40,function(a){return this.md.WC(a)});
g.wY.prototype.LF=g.ca(39,function(a,b,c){this.Ra.set(a,{Gs:b,wy:c})});
g.Q_.prototype.LF=g.ca(38,function(a,b,c){this.md.LF(a,b,c)});
g.BV.prototype.sQ=g.ca(31,function(){return!1});
g.BV.prototype.Bt=g.ca(30,function(){});
g.CV.prototype.Bt=g.ca(29,function(a,b,c){var d=this;this.isDisposed();b=this.Dv(a,b);this.Qr();this.j=g.gC(b,{format:"RAW",onSuccess:function(e){d.j=null;c(e.responseText,a)},
withCredentials:!0})});
g.HV.prototype.Bt=g.ca(28,function(a,b,c){var d=this;this.isDisposed();b=this.Dv(a,b);this.Qr();this.j=g.gC(b,{format:"RAW",onSuccess:function(e){d.j=null;c(e.responseText,a)},
withCredentials:!0})});
g.fV.prototype.Jy=g.ca(27,function(){for(var a=g.jf(document,"track",void 0,this.j),b=0;b<a.length;b++)g.Af(a[b])});
g.jY.prototype.Jy=g.ca(26,function(){this.mediaElement.Jy()});
g.fV.prototype.DF=g.ca(25,function(){return!(!this.j.textTracks||!this.j.textTracks.addEventListener)});
g.jY.prototype.DF=g.ca(24,function(){return this.mediaElement.DF()});
g.fV.prototype.CF=g.ca(23,function(){return!!this.j.textTracks});
g.jY.prototype.CF=g.ca(22,function(){return this.mediaElement.CF()});
g.fV.prototype.gC=g.ca(21,function(a){for(var b=0;b<a.length;b++)this.j.appendChild(a[b])});
g.jY.prototype.gC=g.ca(20,function(a){this.mediaElement.gC(a)});
g.I_.prototype.kD=g.ca(10,function(){return this.Y});
g.V0.prototype.kD=g.ca(9,function(){var a;return(null==(a=g.dU(this))?void 0:a.mz())||null});
g.jU.prototype.mz=g.ca(8,function(){return this.app.kD()});
g.I0.prototype.mz=g.ca(7,function(){var a;return(null==(a=this.Ba)?void 0:a.kD())||null});
g.aQ.prototype.RH=g.ca(3,function(a){return(a=this.Ym(a))?a.j:0});
g.aNa.prototype.RH=g.ca(2,function(){return 0});
var fkb=/#(.)(.)(.)/,ekb=/^#(?:[0-9a-f]{3}){1,2}$/i,mkb={aa:"Afar",ab:"Abkhazian",ace:"Achinese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",aeb:"Tunisian Arabic",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",akz:"Alabama",ale:"Aleut",aln:"Gheg Albanian",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",aro:"Araona",arp:"Arapaho",arq:"Algerian Arabic",ars:"Najdi Arabic",
arw:"Arawak",ary:"Moroccan Arabic",arz:"Egyptian Arabic",as:"Assamese",asa:"Asu",ase:"American Sign Language",ast:"Asturian",av:"Avaric",avk:"Kotava",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bar:"Bavarian",bas:"Basaa",bax:"Bamun",bbc:"Batak Toba",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bew:"Betawi",bez:"Bena",bfd:"Bafut",bfq:"Badaga",bg:"Bulgarian",bgc:"Haryanvi",bgn:"Western Balochi",
bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bjn:"Banjar",bkm:"Kom",bla:"Siksik\u00e1",bm:"Bambara",bn:"Bangla",bo:"Tibetan",bpy:"Bishnupriya",bqi:"Bakhtiari",br:"Breton",bra:"Braj",brh:"Brahui",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",chg:"Chagatai",
chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",ckb_Arab:"Central Kurdish (Arabic)",co:"Corsican",cop:"Coptic",cps:"Capiznon",cr:"Cree",crh:"Crimean Tatar",cs:"Czech",csb:"Kashubian",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",
dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",
fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fula",ff_Adlm:"Fula (Adlam)",ff_Latn:"Fula (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",
gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hi_Latn:"Hindi (Latin)",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",
ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kgp:"Kaingang",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",
kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ks_Deva:"Kashmiri (Devanagari)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",kum:"Kumyk",kut:"Kutenai",kv:"Komi",kw:"Cornish",ky:"Kyrgyz",la:"Latin",lad:"Ladino",lag:"Langi",lah:"Western Panjabi",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",lg:"Ganda",
li:"Limburgish",lkt:"Lakota",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"M\u0101ori",mic:"Mi'kmaq",
min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",ng:"Ndonga",
nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",
pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pon:"Pohnpeian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",
sah:"Yakut",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",
sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",
ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelau",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",
ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vi:"Vietnamese",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",xal:"Kalmyk",xh:"Xhosa",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yrl:"Nheengatu",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",
za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"};C4.prototype.contains=function(a){a=g.Wb(this.segments,a);return 0<=a||0>a&&1===(-a-1)%2};
C4.prototype.length=function(){return this.segments.length/2};
g.w(jkb,g.J);g.k=jkb.prototype;g.k.ya=function(){g.J.prototype.ya.call(this);this.C&&this.C.cancel()};
g.k.rA=function(){this.seekTo(this.player.getCurrentTime())};
g.k.seekTo=function(a){a-=this.player.Uc();var b=this.j;this.j=g.Cb(this.ma.Cq(a).gb);b!==this.j&&this.Y&&this.Y()};
g.k.reset=function(){this.D=new C4;this.K=-1;this.C&&(this.C.cancel(),this.C=null)};
g.k.wX=function(){this.isDisposed();var a;if(a=null!=this.j)a=this.j,a=a.j.Yr(a);if(a&&!this.C&&!(this.j&&30<this.j.startTime-this.player.getCurrentTime())){a=this.j;a=a.j.PB(a);var b=a.gb[0],c;if(null==(c=this.player.getVideoData())?0:c.enableServerStitchedDai)if(c=this.player.mz()){var d=b.j.info.id,e=b.Oa,f=a.gb[0].C;if(this.policy.Ea){if(c=c.Xs(f,e,d,3))a.D=c}else if(d=c.fz(f,e,d,3))if(c=c.WC(e),0===c)d&&(a.j=new g.UP(d));else if(2===c){this.N.start();kkb(this)&&this.seekTo(this.player.getCurrentTime());
return}}(this.policy.cC?b.j.index.tp(b.Oa):a.gb[0].duration)?(this.D.contains(a.gb[0].Oa)||lkb(this,a),this.j=g.Cb(a.gb)):kkb(this)&&this.seekTo(this.player.getCurrentTime())}this.N.start()};
g.w(D4,g.BV);g.k=D4.prototype;g.k.Bt=function(a,b,c){var d=this;this.Qr();b=okb(this,a.getId());b||(b=a.languageCode,b=this.j.isManifestless?pkb(this,b,"386"):pkb(this,b));if(b){var e=1E3*(b.index.RH(b.index.fn())-b.index.getStartTime(b.index.fn())),f=new g.xUa(this.X),h=function(){d.C&&d.C.reset();d.G=!0};
this.X.L("html5_keep_caption_data_after_seek")&&(h=null);this.C=new jkb(f,this.J,b,function(l,m){c(l,a,m,e)},this.K||g.aL(b.info),h)}};
g.k.sQ=function(){var a=this.G;this.G=!1;return a};
g.k.Sz=function(a){var b=this.K?[new g.GS({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.GS({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:this.j.isManifestless?nkb(this,"386"):nkb(this);b=g.u(b);for(var c=b.next();!c.done;c=b.next())g.AV(this.B,c.value);a()};
g.k.Qr=function(){this.C&&(this.C.dispose(),this.C=null)};
g.k.Dv=function(){return""};
var V4=/^#(?:[0-9a-f]{3}){1,2}$/i;var tkb=["left","right","center","justify"];g.w(E4,g.U);g.k=E4.prototype;g.k.R0=function(a,b){this.ib=a;this.jb=b;var c=g.Zr(this.element,this.element.parentElement);this.wb=a-c.x;this.yb=b-c.y};
g.k.Q0=function(a,b){if(a!==this.ib||b!==this.jb){g.Au(this.element,"ytp-dragging")||g.Bu(this.element,"ytp-dragging");var c=g.as(this.element);a=a-this.wb-.02*this.playerWidth;var d=b-this.yb-.02*this.playerHeight,e=(a+c.width/2)/this.maxWidth*3;e=Math.floor(g.re(e,0,2));var f=(d+c.height/2)/this.maxHeight*3;f=Math.floor(g.re(f,0,2));b=e+3*f;a=(a+e/2*c.width)/this.maxWidth;a=100*g.re(a,0,1);c=(d+f/2*c.height)/this.maxHeight;c=100*g.re(c,0,1);this.B.params.Ul=b;this.B.params.Yn=c;this.B.params.dk=
a;this.B.params.isDefault=!1;this.j.Ul=b;this.j.Yn=c;this.j.dk=a;this.j.isDefault=!1;this.qa.Ul=b;this.qa.Yn=c;this.qa.dk=a;this.qa.isDefault=!1;this.pZ()}};
g.k.P0=function(){g.Du(this.element,"ytp-dragging")};
g.k.pZ=function(){this.bB(this.K)};
g.k.getType=function(){return this.type};
g.k.bB=function(a){var b=this.Hb?0:Math.min(this.SV(),this.maxWidth),c=this.RV(),d=this.Hb;if(d){var e=getComputedStyle(this.D.parentNode);e=F4(e.borderLeftWidth)+F4(e.borderRightWidth)+F4(e.paddingLeft)+F4(e.paddingRight)}else e=0;var f=e;e="";3===this.B.params.Di&&(e="rotate(180deg)");var h=d?"calc(96% - "+f+"px)":"96%";g.Qr(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":h,"max-height":h,margin:"",transform:""});this.eM(a);e={transform:e,top:"",left:"",
width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var l=.96*this.j.dk+2;h=this.j.Ul;switch(h){case 0:case 3:case 6:(d=this.j.We.fontSizeIncrement)&&0<d&&2!==this.j.Di&&3!==this.j.Di&&(l=Math.max(l/(1+2*d),2));e.left=l+"%";break;case 1:case 4:case 7:e.left=l+"%";l=this.D.offsetWidth;b||l?(b=b||l+1,e.width=b+"px",e["margin-left"]=d?b/-2-f/2+"px":b/-2+"px"):e.transform+=" translateX(-50%)";break;case 2:case 5:case 8:e.right=100-l+"%"}d=.96*this.j.Yn+2;switch(h){case 0:case 1:case 2:e.top=
d+"%";break;case 3:case 4:case 5:e.top=d+"%";(c=c||this.element.clientHeight)?(e.height=c+"px",e["margin-top"]=c/-2+"px"):e.transform+=" translateY(-50%)";break;case 6:case 7:case 8:e.bottom=100-d+"%"}g.Qr(this.element,e);if(this.G){c=this.D.offsetHeight;d=1;for(b=0;b<a.length;b++)e=a[b],"string"===typeof e.text&&(d+=e.text.split("\n").length-1,e.append||0===b||d++);c/=d;this.G.style.height=c+"px";this.G.style.width=c+"px";this.element.style.paddingLeft=c+5+"px";this.element.style.paddingRight=c+
5+"px";a=Number(this.element.style.marginLeft.replace("px",""))-c-5;c=Number(this.element.style.marginRight.replace("px",""))-c-5;this.element.style.marginLeft=a+"px";this.element.style.marginRight=c+"px"}};
g.k.eM=function(a){var b;for(b=0;b<a.length&&a[b]===this.K[b];b++);if(this.Da||this.K.length>b)b=0,this.Da=!1,this.K=[],this.N=this.Na=this.Ka=null,g.yf(this.D);for(;b<a.length;b++)ykb(this,a[b])};
g.k.SV=function(){return 0};
g.k.RV=function(){return 0};
g.k.toString=function(){return g.U.prototype.toString.call(this)};Akb.prototype.clear=function(){this.C=this.time=this.mode=0;this.j=[];this.reset()};
Akb.prototype.reset=function(){this.mode=0;this.D.reset(0);this.G.reset(1)};
var Bkb=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];G4.prototype.set=function(a){this.type=a};
G4.prototype.get=function(){return this.type};
H4.prototype.clear=function(){this.state=0};
H4.prototype.update=function(){this.state=2===this.state?1:0};
H4.prototype.Ie=function(){return 0!==this.state};
H4.prototype.matches=function(a,b){return this.Ie()&&a===this.Mu&&b===this.xs};
Gkb.prototype.reset=function(){this.timestamp=this.j=0};
I4.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.B[b][c].timestamp=a};
I4.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.B[b][c];a=0===d.j?a+"_":a+String.fromCharCode(d.j)}a+="\n"}return a};
I4.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.B[b][c].reset();this.C=a;this.j=0;this.col=this.row=1};
var Hkb=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],Ikb=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],Jkb=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],Kkb=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];Okb.prototype.reset=function(a,b){this.G=b;this.style.set(2);this.B=this.K;this.D=this.N;this.j=this.B;var c=(a<<2)+(b<<1);this.K.reset(c);this.N.reset(c);this.text.reset((a<<2)+(b<<1)+1)};
zkb.prototype.reset=function(a){this.G=a;this.B.clear();this.D=this.C;this.C.reset(a,0);this.K.reset(a,1)};Skb.prototype.D=function(){};g.w(N4,g.fK);N4.prototype.toString=function(){return g.fK.prototype.toString.call(this)};g.w(O4,g.J);O4.prototype.B=function(){return[]};
O4.prototype.reset=function(){};g.w(P4,g.fK);P4.prototype.toString=function(){return g.fK.prototype.toString.call(this)};
var Q4=0;g.w(R4,O4);R4.prototype.reset=function(){this.N={};this.C=this.j=null;this.K=!0};
R4.prototype.B=function(a,b){a=a.firstChild;a.getAttribute("format");b=b||0;Number.isFinite(b);a=Array.from(a.childNodes);a=g.u(a);for(var c=a.next();!c.done;c=a.next())if(c=c.value,1===c.nodeType)switch(c.tagName){case "head":var d=c;break;case "body":var e=c}if(d)for(d=Array.from(d.childNodes),d=g.u(d),a=d.next();!a.done;a=d.next())if(a=a.value,1===a.nodeType)switch(a.tagName){case "pen":c=a.getAttribute("id");var f=this.pens,h={},l=a.getAttribute("p");l&&Object.assign(h,this.pens[l]);l=T4(a,"b");
null!=l&&(h.bold=l);l=T4(a,"i");null!=l&&(h.italic=l);l=T4(a,"u");null!=l&&(h.underline=l);l=U4(a,"et");null!=l&&(h.charEdgeStyle=l);l=U4(a,"of");null!=l&&(h.offset=l);l=W4(a,"bc");null!=l&&(h.background=l);l=W4(a,"ec");null!=l&&(h.xM=l);l=W4(a,"fc");null!=l&&(h.color=l);l=U4(a,"fs");null!=l&&0!==l&&(h.fontFamily=l);l=S4(a,"sz");void 0!==l&&(h.fontSizeIncrement=l/100-1);l=S4(a,"bo");void 0!==l&&(h.backgroundOpacity=l/255);l=S4(a,"fo");void 0!==l&&(h.textOpacity=l/255);l=U4(a,"rb");null!=l&&10!==l&&
0!==l&&(h.dg=10<l?l-1:l);a=U4(a,"hg");null!=a&&(h.OW=a);f[c]=h;break;case "ws":c=a.getAttribute("id");this.Y[c]=Wkb(this,a);break;case "wp":c=a.getAttribute("id"),this.Z[c]=Xkb(this,a)}if(e){d=[];e=Array.from(e.childNodes);e=g.u(e);for(a=e.next();!a.done;a=e.next())if(a=a.value,1===a.nodeType)switch(a.tagName){case "w":this.j=Ykb(this,a,b,!1);(a=this.N[this.j.id])&&a.end>this.j.start&&(a.end=this.j.start);this.N[this.j.id]=this.j;d.push(this.j);break;case "p":l=b;c=[];f=a.getAttribute("w")||this.G;
h=!!T4(a,"a");l=(S4(a,"t")||0)+l;var m=S4(a,"d")||5E3;h||(!this.K&&this.C&&this.C.windowId===f&&this.C.end>l&&(this.C.end=l),this.C&&"\n"===this.C.text&&(this.C.text=""));var n=h?6:5,p=a.getAttribute("p");p=p?this.pens[p]:null;var q=Array.from(a.childNodes);q.length&&(this.K=null!=a.getAttribute("d"));for(var r=0;r<q.length;r++){var t=q[r],v=void 0;0<r&&(h=!0);var x=void 0;1===t.nodeType&&(x=t);if(x&&"s"===x.tagName){if((t=(t=x.getAttribute("p"))?this.pens[t]:null)&&t.dg&&(1===t.dg?(t=q.slice(r,r+
4),4===t.length&&(v=Ukb(l,m,f,h,n,t,this.pens),r+=3)):v=Ukb(l,m,f,h,n,[x],this.pens)),!v){var C=x;v=l;x=m;t=f;var F=h,G=n,H=C.textContent?C.textContent:"",O=C.getAttribute("p");O=O?this.pens[O]:null;C=S4(C,"t")||0;v=new N4(v+C,x-C,G,t,H,F,O)}}else v=new N4(l,m,n,f,t.textContent||"",h,p);c.push(v);this.C=v}if(0<c.length)for(c[0].windowId===this.G&&(this.j=Ykb(this,a,b,!0),d.push(this.j)),a=g.u(c),c=a.next();!c.done;c=a.next())c=c.value,c.windowId=this.j.id,this.j.j.push(c),d.push(c)}b=d}else b=[];
return b};var Elb=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.w(X4,O4);X4.prototype.reset=function(){this.C.clear()};
X4.prototype.B=function(a,b){var c=JSON.parse(a);if(!c)return[];if(c.pens){a=0;for(var d=g.u(c.pens),e=d.next();!e.done;e=d.next()){e=e.value;var f={},h=e.pParentId;h&&Object.assign(f,this.j.get(h));e.bAttr&&(f.bold=!0);e.iAttr&&(f.italic=!0);e.uAttr&&(f.underline=!0);h=e.ofOffset;null!=h&&(f.offset=h);void 0!==e.szPenSize&&(f.fontSizeIncrement=e.szPenSize/100-1);h=e.etEdgeType;null!=h&&(f.charEdgeStyle=h);void 0!==e.ecEdgeColor&&(f.xM=Y4(e.ecEdgeColor));h=e.fsFontStyle;null!=h&&0!==h&&(f.fontFamily=
h);void 0!==e.fcForeColor&&(f.color=Y4(e.fcForeColor));void 0!==e.foForeAlpha&&(f.textOpacity=e.foForeAlpha/255);void 0!==e.bcBackColor&&(f.background=Y4(e.bcBackColor));void 0!==e.boBackAlpha&&(f.backgroundOpacity=e.boBackAlpha/255);(h=e.rbRuby)&&10!==h&&(f.dg=10<h?h-1:h,f.Xn=Elb.get(f.dg));e.hgHorizGroup&&(f.OW=e.hgHorizGroup);this.j.set(a++,f)}}if(c.wsWinStyles)for(a=0,d=g.u(c.wsWinStyles),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wsParentId)?Object.assign(f,this.G.get(h)):Object.assign(f,
this.K),void 0!==e.mhModeHint&&(f.eA=e.mhModeHint),void 0!==e.juJustifCode&&(f.textAlign=e.juJustifCode),void 0!==e.pdPrintDir&&(f.Di=e.pdPrintDir),void 0!==e.sdScrollDir&&(f.GR=e.sdScrollDir),void 0!==e.wfcWinFillColor&&(f.windowColor=Y4(e.wfcWinFillColor)),void 0!==e.wfoWinFillAlpha&&(f.windowOpacity=e.wfoWinFillAlpha/255),this.G.set(a++,f);if(c.wpWinPositions)for(a=0,d=g.u(c.wpWinPositions),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wpParentId)&&Object.assign(f,this.D.get(h)),void 0!==e.ahHorPos&&
(f.dk=e.ahHorPos),void 0!==e.apPoint&&(f.Ul=e.apPoint),void 0!==e.avVerPos&&(f.Yn=e.avVerPos),void 0!==e.ccCols&&(f.Cs=e.ccCols),void 0!==e.rcRows&&(f.Ar=e.rcRows),this.D.set(a++,f);if(c.events){a=[];c=g.u(c.events);for(d=c.next();!d.done;d=c.next()){var l=d.value;d=(l.tStartMs||0)+b;e=l.dDurationMs||0;if(l.id)f=String(l.id),d=Zkb(this,l,d,e,f),a.push(d),this.C.set(f,d);else{l.wWinId?f=l.wWinId.toString():(f="_"+Q4++,h=Zkb(this,l,d,e,f),a.push(h),this.C.set(f,h));0===e&&(e=5E3);h=this.C.get(f);var m=
!!l.aAppend,n=m?6:5,p=l.segs,q=null;l.pPenId&&(q=this.j.get(l.pPenId));for(l=0;l<p.length;l++){var r=p[l],t=r.utf8;if(t){var v=r.tOffsetMs||0,x=null;r.pPenId&&(x=this.j.get(r.pPenId));if(2===(null!=h.params.eA?h.params.eA:1<h.j.length?1:0)&&m&&"\n"===t)continue;r=null;var C=[],F;if(F=x&&1===x.dg)if(F=l,F+3>=p.length||!p[F+1].pPenId||!p[F+2].pPenId||!p[F+3].pPenId)F=!1;else{var G=p[F+1].pPenId;(G=this.j.get(G))&&G.dg&&2===G.dg?(G=p[F+2].pPenId,G=this.j.get(G),!G||!G.dg||3>G.dg?F=!1:(G=p[F+3].pPenId,
F=(G=this.j.get(G))&&G.dg&&2===G.dg?!0:!1)):F=!1}if(F)v=p[l+1].utf8,r=p[l+3].utf8,F=p[l+2].utf8,G=this.j.get(p[l+2].pPenId),t=Tkb(t,v,F,r,G),r=new N4(d,e,n,f,t,m,x),l+=3;else{if(-1<t.indexOf("<")){var H=void 0;C=x;F=q;G=d;var O=e,Q=m,X=[],ia=g.r2("<html>"+t+"</html>");if(!ia.getElementsByTagName("parsererror").length&&(null==(H=ia.firstChild)?0:H.childNodes.length))for(H=g.u(ia.firstChild.childNodes),ia=H.next();!ia.done;ia=H.next()){ia=ia.value;var qa=void 0,ra=void 0,ma=null!=(ra=null==(qa=ia.textContent)?
void 0:qa.replace(/\n/g,""))?ra:"";if(3!==ia.nodeType||ma&&null==ma.match(/^ *$/)){qa={};Object.assign(qa,C||F);ra=void 0;switch(null==(ra=ia)?void 0:ra.tagName){case "b":qa.bold=!0;break;case "i":qa.italic=!0;break;case "u":qa.underline=!0}X.push(new N4(G+v,O-v,n,h.id,ma,Q,qa))}}C=X}C.length||(C=[new N4(d+v,e-v,n,h.id,t,m,x||q)])}if(C.length)for(m=g.u(C),x=m.next();!x.done;x=m.next())x=x.value,a.push(x),h.j.push(x);else r&&(a.push(r),h.j.push(r))}m=!0}}}b=a}else b=[];return b};g.w(Z4,g.BV);Z4.prototype.Bt=function(a,b,c){dkb(this.videoData.videoId,a.vssId,c)};
Z4.prototype.Sz=function(a){if(this.audioTrack)for(var b=g.u(this.audioTrack.captionTracks),c=b.next();!c.done;c=b.next())g.AV(this.B,c.value);a()};g.w($4,E4);$4.prototype.eM=function(a){var b=this.B.j;E4.prototype.eM.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.j===e)var d=f;else{d={};Object.assign(d,c.j);Object.assign(d,Flb);var e=c.j;var f=d}ykb(this,c,d)}};
var Flb={g6:!0};g.w(a5,Skb);a5.prototype.D=function(a,b,c,d,e){if(c<d){var f="_"+Q4++;c=c/1E3-this.K;d=d/1E3-this.K;a=new P4(c,d-c,5,f,{textAlign:0,Ul:0,dk:2.5*b,Yn:5.33*a});e=new N4(c,d-c,5,f,e);this.B.push(a);this.B.push(e)}};
g.w(d5,O4);d5.prototype.B=function(a){a=new a5(a,a.byteLength,this.C);if($kb(a)){for(;a.byteOffset<a.j.byteLength;)for(0===a.version?a.C=c5(a)*(1E3/45):1===a.version&&(a.C=4294967296*c5(a)+c5(a)),a.G=b5(a);0<a.G;a.G--){var b=b5(a),c=b5(a),d=b5(a);b&4&&(b&3)===this.track&&(0===this.track||1===this.track)&&(b=this.j,b.j.push({time:a.C,type:this.track,WU:c,XU:d,order:b.j.length}))}Fkb(this.j,a);return a.B}return[]};
d5.prototype.reset=function(){this.j.clear()};g.w(e5,E4);g.k=e5.prototype;g.k.pZ=function(){g.vu(this.Za)};
g.k.c9=function(){g.Du(this.element,"ytp-rollup-mode");this.bB(this.qc,!0)};
g.k.RV=function(){return this.C?this.ma:this.Y};
g.k.SV=function(){return this.C?this.Y:this.ma};
g.k.bB=function(a,b){this.qc=a;if(this.B.params.Ar){for(var c=0,d=0;d<this.K.length&&c<a.length;d++)this.K[d]===a[c]&&c++;0<c&&c<a.length&&(a=this.K.concat(a.slice(c)));this.Yb=this.ma;this.Y=this.ma=0;E4.prototype.bB.call(this,a);dlb(this,b)}E4.prototype.bB.call(this,a)};g.w(f5,O4);
f5.prototype.B=function(a,b){var c=[];a=a.split(Glb);for(var d=1;d<a.length;d++){var e=a[d],f=b;if(""!==e&&!Hlb.test(e)){var h=Ilb.exec(e);if(h&&4<=h.length){var l=flb(h[1]),m=flb(h[2])-l;l+=f;var n=(h=h[3])?h.split(" "):[];h={};var p=null;var q="";var r=null,t="";n=g.u(n);for(var v=n.next();!v.done;v=n.next())if(v=v.value.split(":"),2===v.length){var x=v[1];switch(v[0]){case "line":v=x.split(",");v[0].endsWith("%")&&(p=v[0],h.Yn=Number.parseInt(p,10),2===v.length&&(q=v[1].trim()));break;case "position":v=
x.split(",");r=v[0];h.dk=Number.parseInt(r,10);2===v.length&&(t=v[1].trim());break;case "align":switch(x){case "start":h.textAlign=0;break;case "middle":h.textAlign=2;break;case "end":h.textAlign=1}}}p||q||(q="end");if(!r)switch(h.textAlign){case 0:h.dk=0;break;case 1:h.dk=100;break;case 2:h.dk=50}if(null!=h.textAlign){p=0;switch(q){case "center":p+=3;break;case "end":p+=6;break;default:p+=0}switch(t){case "line-left":p+=0;break;case "center":p+=1;break;case "line-right":p+=2;break;default:switch(h.textAlign){case 0:p+=
0;break;case 2:p+=1;break;case 1:p+=2}}q=0>p||8<p?7:p;h.Ul=q}e=e.substring(Ilb.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");t=h;h=e;e={};if(0>h.indexOf("<")&&0>h.indexOf("&"))f=glb(l,m,5,t),m=new N4(l,m,5,f.id,h,!1,g.kd(e)?void 0:e),c.push(f),c.push(m),f.j.push(m);else for(q=h.split(Jlb),1===q.length?(h=5,t=glb(l,m,h,t)):(p=h=6,t=Object.assign({Cs:32},t),t=new P4(l,m,p,"_"+Q4++,t)),c.push(t),p=l,r=0;r<q.length;r++)n=q[r],0===r%2?(v=g.r2("<html>"+n+"</html>"),v.getElementsByTagName("parsererror").length?
(x=v.createElement("span"),x.appendChild(v.createTextNode(n))):x=v.firstChild,elb(this,p,m-(p-l),h,t,0<r,x,e,c)):p=flb(n)+f}Ilb.lastIndex=0}}return c};
var Hlb=/^NOTE/,Glb=/(?:\r\n|\r|\n){2,}/,Ilb=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),Jlb=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");g.kY.mI(f5,{B:"wvppt"});g.w(g5,g.J);g5.prototype.clear=function(){this.j&&this.j.dispose();this.j=null};
g5.prototype.reset=function(){this.j&&this.j.reset()};
g5.prototype.ya=function(){g.J.prototype.ya.call(this);this.clear()};var p5={windowColor:"#080808",windowOpacity:0,textAlign:2,Ul:7,dk:50,Yn:100,isDefault:!0,We:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.w(h5,g.yV);g.k=h5.prototype;g.k.ya=function(){if(this.D||this.Ea){var a=this.J.yf();a&&!a.isDisposed()&&a.Jy()}else Dlb(this,!1);g.yV.prototype.ya.call(this)};
g.k.sR=function(){return this.X.L("html5_honor_caption_availabilities_in_audio_track")&&!this.ib};
g.k.Vt=function(){if(this.Za)return this.D||this.Ea;var a=this.getAudioTrack();if(this.sR()){if(!a.captionTracks.length)return!1;if(!this.j)return!0}a=akb(a,g.sS(this.X));return"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===a?!0:"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===a?i5(this):slb(this)||i5(this)?!0:tlb(this)};
g.k.load=function(){var a=this;g.yV.prototype.load.call(this);this.N=this.getAudioTrack();this.j?this.B&&(this.fb.clear(),this.D?xlb(this,!0):3!==this.player.getPresentingPlayerType()&&this.j.Bt(this.B,"json3",function(b,c,d,e){if(b){var f;ylb(a,null!=(f=a.B)?f:void 0);a.j.sQ()&&(a.Da=[],a.J.jf("captions"),g.ru(a.Ka),a.fb.reset());if(a.videoData.Im){var h;d=(null!=(h=d)?h:0)+a.videoData.Im}b=mlb(a.fb,b,c,d,e);if(a.jb)for(c=g.u(b),e=c.next();!e.done;e=c.next())e=e.value,e.C=a.videoData.clientPlaybackNonce,
e.tm=a.videoData.Im;c=!a.X.L("html5_keep_caption_data_after_seek")&&a.ib;a.player.wf(b,void 0,c);!a.Y||a.Ea||l5(a)||g.LJ(a.X)||g.hS(a.X)||g.iH(a.X)||"shortspage"===a.X.Va||a.player.isInline()||(g.wu(a.Na),b=Vkb({Ul:0,dk:5,Yn:5,Ar:2,textAlign:0,Di:0,lang:"fr"}),a.Ra=[b],c=["Cliquez sur "," pour acc\u00e9der aux param\u00e8tres."],a.wb||(e=new g.hG(g.kva()),g.L(a,e),a.wb=e.element),e=b.end-b.start,(f=g.HS(a.B))&&a.Ra.push(new N4(b.start,e,0,b.id,f)),a.Ra.push(new N4(b.start,e,0,b.id,c[0]),new N4(b.start,
e,0,b.id,a.wb,!0),new N4(b.start,e,0,b.id,c[1],!0)),a.player.wf(a.Ra),g.uu(a.Na));!a.Y||a.Ea||l5(a)||(g.sS(a.X)?n5(a,!0):o5(a,!0),a.N&&(a.N.D=a.B),a.player.qo());a.Y=!1}}),this.D||this.Ea||l5(this)||this.player.Qa("captionschanged",g.IS(this.B))):(this.j=ulb(this),g.L(this,this.j),this.j.Sz(function(){wlb(a)}))};
g.k.unload=function(){this.D&&this.B?xlb(this,!1):(this.Na&&g.wu(this.Na),this.player.jf("captions"),this.Da=[],this.j&&this.j.Qr(),this.fb.clear(),this.Z&&this.player.wf(this.Z),this.WR());g.yV.prototype.unload.call(this);this.player.qo();this.player.Qa("captionschanged",{})};
g.k.create=function(){this.Vt()&&this.load();var a;a:{var b,c,d;if(this.X.L("suggest_caption_correction_menu_item")&&this.X.L("web_player_nitrate_promo_tooltip")&&(null==(b=this.videoData.getPlayerResponse())?0:null==(c=b.captions)?0:null==(d=c.playerCaptionsTracklistRenderer)?0:d.openTranscriptCommand)){var e,f;if(b=null==(a=this.videoData.getPlayerResponse())?void 0:null==(e=a.captions)?void 0:null==(f=e.playerCaptionsTracklistRenderer)?void 0:f.captionTracks)for(a=g.u(b),e=a.next();!e.done;e=a.next())if(e=
e.value,"asr"===e.kind&&"en"===e.languageCode){a=!0;break a}}a=!1}a&&this.J.oa("showpromotooltip",this.K.element)};
g.k.K9=function(){for(var a=this.J.yf().Db().textTracks,b=null,c=0;c<a.length;c++)if("showing"===a[c].mode)a:{b=g.zV(this.j.B,!0);for(var d=0;d<b.length;d++)if(b[d].toString()===a[c].id){b=b[d];break a}b=null}(this.loaded?this.B:null)!==b&&m5(this,b,!0)};
g.k.Uaa=function(){!this.B&&this.D||this.unload()};
g.k.onCueRangeEnter=function(a){this.Da.push(a);g.ru(this.Ka)};
g.k.onCueRangeExit=function(a){g.Ib(this.Da,a);this.j instanceof D4&&this.j.K&&this.player.Np([a]);g.ru(this.Ka)};
g.k.getCaptionWindowContainerId=function(){return this.K.element.id};
g.k.C$=function(){Clb(this,this.Ra);this.Ra=null};
g.k.UR=function(){var a=this;if(!this.Hb||!this.D){this.Ka.stop();g.dba(this.Va);this.Da.sort(g.uza);var b=this.Da;if(this.Z){var c=g.Rs(b,function(f){return-1===this.Z.indexOf(f)},this);
c.length&&(b=c)}b=g.u(b);for(c=b.next();!c.done;c=b.next())Alb(this,c.value);b=g.u(Object.entries(this.qa));var d=b.next();for(c={};!d.done;c={Kv:c.Kv,Vm:c.Vm},d=b.next()){var e=g.u(d.value);d=e.next().value;e=e.next().value;c.Kv=d;c.Vm=e;this.Va[c.Kv]?(c.Vm.element.parentNode||(c.Vm instanceof e5||c.Vm instanceof $4||g.bd(this.qa,function(f){return function(h,l){l!==f.Kv&&h.B.params.Ul===f.Vm.B.params.Ul&&h.B.params.dk===f.Vm.B.params.dk&&h.B.params.Yn===f.Vm.B.params.Yn&&(h.dispose(),delete a.qa[l]);
return l===f.Kv}}(c),this),this.K.element.appendChild(c.Vm.element)),c.Vm.bB(this.Va[c.Kv])):(c.Vm.dispose(),delete this.qa[c.Kv])}}};
g.k.I$=function(){qlb(this,{},!0);this.player.Qa("captionssettingschanged")};
g.k.u5=function(){var a=p5.We;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.italic?3:a.bold?1:a.italic?2:0,textOpacity:a.textOpacity,windowColor:p5.windowColor,windowOpacity:p5.windowOpacity};var b=hkb()||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&(a.backgroundOpacity=
b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&(a.fontSizeIncrement=
b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);null!=b.windowOpacity&&
(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.k.H_=function(a,b){var c={};Object.assign(c,hkb());Object.assign(c,a);qlb(this,c,b);this.player.Qa("captionssettingschanged")};
g.k.WR=function(){!this.D&&this.loaded&&(g.Vc(this.qa,function(a,b){a.dispose();delete this.qa[b]},this),this.UR())};
g.k.Gh=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.re(b,-2,4);this.H_({fontSizeIncrement:c});return c;case "reload":b&&!this.D&&m5(this,this.B,!0);break;case "stickyLoading":void 0!==b&&this.X.K&&(g.sS(this.X)?n5(this,!!b):o5(this,!!b));break;case "track":if(!this.j)return{};if(b){if(this.D)break;if(!g.ab(b))break;if(g.kd(b)){m5(this,null,!0);break}a=g.zV(this.j.B,!0);for(var d=0;d<a.length;d++){var e=a[d];e.languageCode!==b.languageCode||c&&(e.languageName!==b.languageName||
(e.captionId||"")!==(b.captionId||""))||(c=b.translationLanguage?bkb(e,b.translationLanguage):e)}this.DK(b.position);!c||c===this.B&&this.loaded||(b=g.WKa(),a=g.JS(c),b.length&&a===b[b.length-1]||(b.push(a),g.YC("yt-player-caption-language-preferences",b)),g.sS(this.X)&&!this.J.isInline()&&g.YC("yt-player-caption-sticky-language",a,2592E3),m5(this,c,!0))}else return this.loaded&&this.B&&!l5(this)?g.IS(this.B):{};return"";case "tracklist":return this.j?g.dq(g.zV(this.j.B,!(!b||!b.includeAsr)),function(f){return g.IS(f)}):
[];
case "translationLanguages":return this.j?this.j.D.map(function(f){return Object.assign({},f)}):[];
case "sampleSubtitles":this.D||void 0===b||Dlb(this,!!b);break;case "sampleSubtitlesCustomized":this.D||Dlb(this,!!b,b);break;case "recommendedTranslationLanguages":return g.WKa();case "defaultTranslationSourceTrackIndices":return this.j?this.j.N:[]}};
g.k.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.X.K&&a.push("stickyLoading");return a};
g.k.Eq=function(){var a=this.B;if(this.X.L("html5_modify_caption_vss_logging")){var b;return(a=null!=(b=this.videoData.CB)?b:null)?{cc:g.tPa(a)}:{}}return a?(b=a.vssId,a.translationLanguage&&b&&(b="t"+b+"."+g.JS(a)),{cc:b}):{}};
g.k.Iaa=function(){this.isSubtitlesOn()?(g.sS(this.X)?n5(this,!1):o5(this,!1),ylb(this),this.unload(),i5(this,!0)&&m5(this,j5(this),!1)):this.o_()};
g.k.o_=function(){this.isSubtitlesOn()||m5(this,l5(this)||!this.B?k5(this,!0):this.B,!0)};
g.k.isSubtitlesOn=function(){return!!this.loaded&&!!this.B&&!l5(this)};
g.k.A7=function(){var a=l5(this);i5(this,a)?m5(this,this.getAudioTrack().j,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.sR()&&(this.Y=!1,this.B=null,this.j&&(this.j.dispose(),this.j=null)),this.Vt()&&(a?m5(this,k5(this),!1):this.load()))};
g.k.DK=function(a){a&&(this.ma={top:a.top,right:a.right,bottom:a.bottom,left:a.left,width:1-a.left-a.right,height:1-a.top-a.bottom},this.K.element.style.top=100*this.ma.top+"%",this.K.element.style.left=100*this.ma.left+"%",this.K.element.style.width=100*this.ma.width+"%",this.K.element.style.height=100*this.ma.height+"%",this.K.element.style.position="absolute",a=Blb(this))&&(this.K.element.style.width=a.width+"px",this.K.element.style.height=a.height+"px")};
g.k.onVideoDataChange=function(a,b){"newdata"===a&&(this.videoData=b,this.loaded&&this.unload(),this.Y=!1,this.B=null,this.j&&(this.j.dispose(),this.j=null,this.player.Qa("captionschanged",{})),this.Vt()&&this.load())};
g.k.getAudioTrack=function(){return this.jb&&2===this.player.getPresentingPlayerType()?this.videoData.jl:this.player.getAudioTrack()};
g.k.k8=function(){var a=this.J.yf();a&&!a.isDisposed()&&a.Jy();this.J.isFullscreen()?(this.D=this.Za=!0,this.loaded&&wlb(this)):(this.Za="3"===this.X.controlsType,this.D=plb(this));m5(this,this.B)};
g.k.XK=function(){var a,b,c,d=null==(a=this.videoData.getPlayerResponse())?void 0:null==(b=a.captions)?void 0:null==(c=b.playerCaptionsTracklistRenderer)?void 0:c.openTranscriptCommand;d&&this.player.Qa("innertubeCommand",d)};
g.kY.mI(h5,{UR:"smucd"});g.xV("captions",h5);})(_yt_player);
