(function(g){var window=this;'use strict';var Ynb=function(a,b){a.Qa("onAutonavCoundownStarted",b)},i6=function(a,b,c){g.Fu(a.element,"ytp-suggestion-set",!!b.videoId);
var d=b.playlistId;c=b.Tg(c?c:"mqdefault.jpg");var e=null,f=null;b instanceof g.QS&&(b.lengthText?(e=b.lengthText||null,f=b.Xv||null):b.lengthSeconds&&(e=g.bH(b.lengthSeconds),f=g.bH(b.lengthSeconds,!0)));var h=!!d;d=h&&"RD"===g.IPa(d).type;var l=b instanceof g.QS?b.isLivePlayback:null,m=b instanceof g.QS?b.isUpcoming:null,n=b.author,p=b.shortViewCount,q=b.publishedTimeText,r=[],t=[];n&&r.push(n);p&&(r.push(p),t.push(p));q&&t.push(q);c={title:b.title,author:n,author_and_views:r.join(" \u2022 "),aria_label:b.ariaLabel||
g.mK("Regarder $TITLE",{TITLE:b.title}),duration:e,timestamp:f,url:b.Pk(),is_live:l,is_upcoming:m,is_list:h,is_mix:d,background:c?"background-image: url("+c+")":"",views_and_publish_time:t.join(" \u2022 "),autoplayAlternativeHeader:b.ws};b instanceof g.PS&&(c.playlist_length=b.playlistLength);a.update(c)},j6=function(a){var b=a.U(),c=b.D;
g.U.call(this,{I:"a",S:"ytp-autonav-suggestion-card",W:{href:"{{url}}",target:c?b.Y:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},V:[{I:"div",Ma:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],W:{style:"{{background}}"},V:[{I:"div",W:{"aria-label":"{{timestamp}}"},Ma:["ytp-autonav-timestamp"],xa:"{{duration}}"},{I:"div",Ma:["ytp-autonav-live-stamp"],xa:"En direct"},
{I:"div",Ma:["ytp-autonav-upcoming-stamp"],xa:"\u00c0 venir"},{I:"div",S:"ytp-autonav-list-overlay",V:[{I:"div",S:"ytp-autonav-mix-text",xa:"Mix"},{I:"div",S:"ytp-autonav-mix-icon"}]}]},{I:"div",Ma:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],xa:"{{title}}"},{I:"div",Ma:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],xa:"{{author}}"},{I:"div",Ma:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],xa:"{{views_and_publish_time}}"}]});this.J=
a;this.suggestion=null;this.j=c;this.Sa("click",this.onClick);this.Sa("keypress",this.onKeyPress)},k6=function(a,b){b=void 0===b?!1:b;
g.U.call(this,{I:"div",S:"ytp-autonav-endscreen-countdown-overlay"});var c=this;this.N=b;this.G=this.K=void 0;this.C=0;this.container=new g.U({I:"div",S:"ytp-autonav-endscreen-countdown-container"});g.L(this,this.container);this.container.Fa(this.element);b=a.U();var d=b.D;this.J=a;this.suggestion=null;this.onVideoDataChange("newdata",this.J.getVideoData());this.T(a,"videodatachange",this.onVideoDataChange);this.j=new g.U({I:"div",S:"ytp-autonav-endscreen-upnext-container",W:{"aria-label":"{{aria_label}}",
"data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},V:[{I:"div",S:"ytp-autonav-endscreen-upnext-header"},{I:"div",S:"ytp-autonav-endscreen-upnext-alternative-header",xa:"{{autoplayAlternativeHeader}}"},{I:"a",S:"ytp-autonav-endscreen-link-container",W:{href:"{{url}}",target:d?b.Y:""},V:[{I:"div",S:"ytp-autonav-endscreen-upnext-thumbnail",W:{style:"{{background}}"},V:[{I:"div",W:{"aria-label":"{{timestamp}}"},Ma:["ytp-autonav-timestamp"],
xa:"{{duration}}"},{I:"div",Ma:["ytp-autonav-live-stamp"],xa:"En direct"},{I:"div",Ma:["ytp-autonav-upcoming-stamp"],xa:"\u00c0 venir"}]},{I:"div",S:"ytp-autonav-endscreen-video-info",V:[{I:"div",S:"ytp-autonav-endscreen-premium-badge"},{I:"div",S:"ytp-autonav-endscreen-upnext-title",xa:"{{title}}"},{I:"div",S:"ytp-autonav-endscreen-upnext-author",xa:"{{author}}"},{I:"div",S:"ytp-autonav-view-and-date",xa:"{{views_and_publish_time}}"},{I:"div",S:"ytp-autonav-author-and-view",xa:"{{author_and_views}}"}]}]}]});
g.L(this,this.j);this.j.Fa(this.container.element);d||this.T(this.j.Ga("ytp-autonav-endscreen-link-container"),"click",this.yS);this.J.xb(this.container.element,this,115127);this.J.xb(this.j.Ga("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.U({I:"div",S:"ytp-autonav-overlay"});g.L(this,this.overlay);this.overlay.Fa(this.container.element);this.B=new g.U({I:"div",S:"ytp-autonav-endscreen-button-container"});g.L(this,this.B);this.B.Fa(this.container.element);this.cancelButton=
new g.U({I:"button",Ma:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button",b.L("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],W:{"aria-label":"Annuler la lecture automatique"},xa:"Annuler"});g.L(this,this.cancelButton);this.cancelButton.Fa(this.B.element);this.cancelButton.Sa("click",this.V0,this);this.J.xb(this.cancelButton.element,this,115129);this.playButton=new g.U({I:"a",Ma:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button",
b.L("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],W:{href:"{{url}}",role:"button","aria-label":"Lire la vid\u00e9o suivante"},xa:"Regarder"});g.L(this,this.playButton);this.playButton.Fa(this.B.element);this.playButton.Sa("click",this.yS,this);this.J.L("web_player_autonav_next_button_renderer")?this.J.Xf(this.playButton.element,this.playButton,!0):this.J.xb(this.playButton.element,this,115130);this.D=new g.tu(function(){Znb(c)},500);
g.L(this,this.D);this.xS();this.T(a,"autonavvisibility",this.xS);this.J.L("web_autonav_color_transition")&&(this.T(a,"autonavchange",this.U0),this.T(a,"onAutonavCoundownStarted",this.B7))},l6=function(a){var b=a.J.Ok(!0,a.J.isFullscreen());
g.Fu(a.container.element,"ytp-autonav-endscreen-small-mode",a.wg(b));g.Fu(a.container.element,"ytp-autonav-endscreen-is-premium",!!a.suggestion&&!!a.suggestion.oK);g.Fu(a.J.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!a.J.Af());g.Fu(a.J.getRootNode(),"countdown-running",a.Sk());g.Fu(a.container.element,"ytp-player-content",a.J.Af());g.Qr(a.overlay.element,{width:b.width+"px"});if(!a.Sk()){a.J.Af()?$nb(a,Math.round(aob(a)/1E3)):$nb(a);b=!!a.suggestion&&!!a.suggestion.ws;var c=a.J.Af()||!b;
g.Fu(a.container.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!c&&b);g.Fu(a.container.element,"ytp-autonav-endscreen-upnext-no-alternative-header",c&&!b);g.kG(a.B,a.J.Af());g.Fu(a.element,"ytp-enable-w2w-color-transitions",bob(a))}},Znb=function(a){var b=aob(a),c=Math,d=c.min;
var e=a.C?Date.now()-a.C:0;c=d.call(c,e,b);$nb(a,Math.ceil((b-c)/1E3));500>=b-c&&a.Sk()?a.select(!0):a.Sk()&&a.D.start()},aob=function(a){if(a.J.isFullscreen()){var b;
a=null==(b=a.J.getVideoData())?void 0:b.yB;return-1===a||void 0===a?8E3:a}return 0<=a.J.Os()?a.J.Os():g.AJ(a.J.U().experiments,"autoplay_time")||1E4},bob=function(a){var b;
return!(null==(b=a.J.getVideoData())||!b.watchToWatchTransitionRenderer)},$nb=function(a,b){b=void 0===b?-1:b;
a=a.j.Ga("ytp-autonav-endscreen-upnext-header");g.yf(a);if(0<=b){b=String(b);var c="Prochaine vid\u00e9o dans $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],d="Prochaine vid\u00e9o dans $SECONDS".indexOf(c);if(0<=d){a.appendChild(g.wf("Prochaine vid\u00e9o dans $SECONDS".slice(0,d)));var e=g.vf("span");g.zu(e,"ytp-autonav-endscreen-upnext-header-countdown-number");g.Gf(e,b);a.appendChild(e);a.appendChild(g.wf("Prochaine vid\u00e9o dans $SECONDS".slice(d+c.length)));return}}g.Gf(a,"\u00c0 suivre")},
m6=function(a,b){g.U.call(this,{I:"div",
Ma:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.created=!1;this.player=a},n6=function(a){g.U.call(this,{I:"div",
Ma:["ytp-upnext","ytp-player-content"],W:{"aria-label":"{{aria_label}}"},V:[{I:"div",S:"ytp-cued-thumbnail-overlay-image",W:{style:"{{background}}"}},{I:"span",S:"ytp-upnext-top",V:[{I:"span",S:"ytp-upnext-header",xa:"\u00c0 suivre"},{I:"span",S:"ytp-upnext-title",xa:"{{title}}"},{I:"span",S:"ytp-upnext-author",xa:"{{author}}"}]},{I:"a",S:"ytp-upnext-autoplay-icon",W:{role:"button",href:"{{url}}","aria-label":"Lire la vid\u00e9o suivante"},V:[{I:"svg",W:{height:"100%",version:"1.1",viewBox:"0 0 72 72",
width:"100%"},V:[{I:"circle",S:"ytp-svg-autoplay-circle",W:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{I:"circle",S:"ytp-svg-autoplay-ring",W:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{I:"path",S:"ytp-svg-fill",W:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{I:"span",S:"ytp-upnext-bottom",V:[{I:"span",S:"ytp-upnext-cancel"},{I:"span",S:"ytp-upnext-paused",
xa:"La lecture automatique est d\u00e9sactiv\u00e9e"}]}]});this.api=a;this.cancelButton=null;this.G=this.Ga("ytp-svg-autoplay-ring");this.C=this.notification=this.j=this.suggestion=null;this.D=new g.tu(this.OG,5E3,this);this.B=0;var b=this.Ga("ytp-upnext-cancel");this.cancelButton=new g.U({I:"button",Ma:["ytp-upnext-cancel-button","ytp-button"],W:{tabindex:"0","aria-label":"Annuler la lecture automatique"},xa:"Annuler"});g.L(this,this.cancelButton);this.cancelButton.Sa("click",this.W0,this);this.cancelButton.Fa(b);
this.cancelButton&&this.api.xb(this.cancelButton.element,this,115129);g.L(this,this.D);this.api.xb(this.element,this,18788);b=this.Ga("ytp-upnext-autoplay-icon");this.T(b,"click",this.X0);this.api.xb(b,this,115130);this.zS();this.T(a,"autonavvisibility",this.zS);this.T(a,"mdxnowautoplaying",this.m8);this.T(a,"mdxautoplaycanceled",this.n8);g.Fu(this.element,"ytp-upnext-mobile",this.api.U().B)},cob=function(a,b){if(b)return b;
if(a.api.isFullscreen()){var c;a=null==(c=a.api.getVideoData())?void 0:c.yB;return-1===a||void 0===a?8E3:a}return 0<=a.api.Os()?a.api.Os():g.AJ(a.api.U().experiments,"autoplay_time")||1E4},dob=function(a,b){b=cob(a,b);
var c=Math,d=c.min;var e=(0,g.GD)()-a.B;c=d.call(c,e,b);b=0===b?1:Math.min(c/b,1);a.G.setAttribute("stroke-dashoffset",""+-211*(b+1));1<=b&&a.Sk()&&3!==a.api.getPresentingPlayerType()?a.select(!0):a.Sk()&&a.j.start()},o6=function(a){m6.call(this,a,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.U({I:"div",S:"ytp-suggestion-panel",V:[{I:"div",Ma:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],xa:"Plus de vid\u00e9os"}]});this.N=new g.U({I:"div",S:"ytp-suggestions-container"});this.videos=[];this.C=null;this.G=this.K=!1;this.B=new k6(this.player);g.L(this,this.B);this.B.Fa(this.element);a.getVideoData().Qf?this.j=this.B:(this.j=new n6(a),g.rU(this.player,this.j.element,4),g.L(this,this.j));this.overlay=new g.U({I:"div",
S:"ytp-autonav-overlay-cancelled-state"});g.L(this,this.overlay);this.overlay.Fa(this.element);this.D=new g.QK(this);g.L(this,this.D);g.L(this,this.table);this.table.Fa(this.element);this.table.show();g.L(this,this.N);this.N.Fa(this.table.element);this.hide()},p6=function(a){var b=a.Af();
b!==a.G&&(a.G=b,a.player.oa("autonavvisibility"),a.G?(a.B!==a.j&&a.B.hide(),a.table.hide()):(a.B!==a.j&&a.B.show(),a.table.show()))},q6=function(a,b){g.U.call(this,{I:"button",
Ma:["ytp-watch-on-youtube-button","ytp-button"],xa:"{{content}}"});this.J=a;this.buttonType=this.buttonType=b;this.JZ();2===this.buttonType&&g.Bu(this.element,"ytp-continue-watching-button");this.Sa("click",this.onClick);this.Sa("videodatachange",this.JZ);g.kG(this,!0)},r6=function(a,b){m6.call(this,a,"embeds-lite-endscreen");
this.J=a;this.rb=b;this.J.xb(this.element,this,156943);this.watchButton=new q6(a,2);g.L(this,this.watchButton);this.watchButton.Fa(this.element);this.hide()},eob=function(a){m6.call(this,a,"subscribecard-endscreen");
this.j=new g.U({I:"div",S:"ytp-subscribe-card",V:[{I:"img",S:"ytp-author-image",W:{src:"{{profilePicture}}"}},{I:"div",S:"ytp-subscribe-card-right",V:[{I:"div",S:"ytp-author-name",xa:"{{author}}"},{I:"div",S:"html5-subscribe-button-container"}]}]});g.L(this,this.j);this.j.Fa(this.element);var b=a.getVideoData();this.subscribeButton=new g.jW("S'abonner",null,"Se d\u00e9sabonner",null,!0,!1,b.Fl,b.subscribed,"trailer-endscreen",null,a);g.L(this,this.subscribeButton);this.subscribeButton.Fa(this.j.Ga("html5-subscribe-button-container"));
this.T(a,"videodatachange",this.Ta);this.Ta();this.hide()},s6=function(a){var b=a.U(),c=g.jL||g.aS?{style:"will-change: opacity"}:void 0,d=b.D,e=["ytp-videowall-still"];
b.B&&e.push("ytp-videowall-show-text");g.U.call(this,{I:"a",Ma:e,W:{href:"{{url}}",target:d?b.Y:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},V:[{I:"div",S:"ytp-videowall-still-image",W:{style:"{{background}}"}},{I:"span",S:"ytp-videowall-still-info",W:{"aria-hidden":"true"},V:[{I:"span",S:"ytp-videowall-still-info-bg",V:[{I:"span",S:"ytp-videowall-still-info-content",W:c,V:[{I:"span",S:"ytp-videowall-still-info-title",xa:"{{title}}"},
{I:"span",S:"ytp-videowall-still-info-author",xa:"{{author_and_views}}"},{I:"span",S:"ytp-videowall-still-info-live",xa:"En direct"},{I:"span",S:"ytp-videowall-still-info-duration",xa:"{{duration}}"}]}]}]},{I:"span",Ma:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],W:{"aria-hidden":"true"},V:[{I:"span",S:"ytp-videowall-still-listlabel-icon"},"Playlist",{I:"span",S:"ytp-videowall-still-listlabel-length",V:[" (",{I:"span",xa:"{{playlist_length}}"},")"]}]},{I:"span",Ma:["ytp-videowall-still-listlabel-mix",
"ytp-videowall-still-listlabel"],W:{"aria-hidden":"true"},V:[{I:"span",S:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{I:"span",S:"ytp-videowall-still-listlabel-length",xa:" (50+)"}]}]});this.suggestion=null;this.B=d;this.api=a;this.j=new g.QK(this);g.L(this,this.j);this.Sa("click",this.onClick);this.Sa("keypress",this.onKeyPress);this.j.T(a,"videodatachange",this.onVideoDataChange);a.Xf(this.element,this);this.onVideoDataChange()},t6=function(a){m6.call(this,a,"videowall-endscreen");
var b=this;this.J=a;this.C=0;this.stills=[];this.D=this.videoData=null;this.G=this.N=!1;this.Y=null;this.B=new g.QK(this);g.L(this,this.B);this.K=new g.tu(function(){g.Bu(b.element,"ytp-show-tiles")},0);
g.L(this,this.K);var c=new g.U({I:"button",Ma:["ytp-button","ytp-endscreen-previous"],W:{"aria-label":"Pr\u00e9c\u00e9dente"},V:[g.qG()]});g.L(this,c);c.Fa(this.element);c.Sa("click",this.d1,this);this.table=new g.hG({I:"div",S:"ytp-endscreen-content"});g.L(this,this.table);this.table.Fa(this.element);c=new g.U({I:"button",Ma:["ytp-button","ytp-endscreen-next"],W:{"aria-label":"Suivante"},V:[g.rG()]});g.L(this,c);c.Fa(this.element);c.Sa("click",this.b1,this);a.getVideoData().Qf?this.j=new k6(a,!0):
this.j=new n6(a);g.L(this,this.j);g.rU(this.player,this.j.element,4);a.xb(this.element,this,158789);this.hide()},u6=function(a){return g.sU(a.player)&&a.kC()&&!a.D},v6=function(a){var b=a.Af();
b!==a.N&&(a.N=b,a.player.oa("autonavvisibility"))},w6=function(a){m6.call(this,a,"watch-again-on-youtube-endscreen");
this.watchButton=new q6(a,1);g.L(this,this.watchButton);this.watchButton.Fa(this.element);g.Bcb(a)&&(this.j=new g.t2(a,g.eU(a)),g.L(this,this.j),this.B=new g.U({I:"div",Ma:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],W:{tabIndex:"-1"},V:[this.j]}),g.L(this,this.B),this.j.Fa(this.B.element),this.B.Fa(this.element));a.xb(this.element,this,156914);this.hide()},iob=function(a){g.yV.call(this,a);
var b=this;this.endScreen=null;this.B=this.j=this.C=this.D=!1;this.listeners=new g.QK(this);g.L(this,this.listeners);var c=a.U(),d=a.getVideoData();d=d&&0!==d.limitedPlaybackDurationInSeconds;g.GC(g.kS(c))&&d&&!g.nU(a)?(this.B=!0,this.endScreen=new r6(a,g.eU(a))):g.oU(a)?this.endScreen=new w6(a):fob(a)?(this.D=!0,gob(this),this.j?this.endScreen=new o6(a):this.endScreen=new t6(a)):c.Xg?this.endScreen=new eob(a):this.endScreen=new m6(a);g.L(this,this.endScreen);g.rU(a,this.endScreen.element,4);hob(this);
this.listeners.T(a,"videodatachange",this.onVideoDataChange,this);this.listeners.T(a,g.gK("endscreen"),function(e){b.onCueRangeEnter(e)});
this.listeners.T(a,g.hK("endscreen"),function(e){b.onCueRangeExit(e)})},gob=function(a){var b=a.player.getVideoData();
if(!b||a.j===b.Hl&&a.C===b.Qf)return!1;a.j=b.Hl;a.C=b.Qf;return!0},fob=function(a){a=a.U();
return a.Kd&&!a.Xg},hob=function(a){a.player.jf("endscreen");
var b=a.player.getVideoData();b=new g.fK(Math.max(1E3*(b.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});var c=new g.fK(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});a.player.wf([b,c])};
g.VX.prototype.XA=g.ca(37,function(a){this.eQ!==a&&(this.eQ=a,this.El())});
g.NW.prototype.Fr=g.ca(36,function(a){this.j!==a&&(this.j=a,this.Ta())});
g.VX.prototype.Fr=g.ca(35,function(a){this.shareButton&&this.shareButton.Fr(a)});
g.IW.prototype.Er=g.ca(34,function(a){this.j!==a&&(this.j=a,this.Ta())});
g.VX.prototype.Er=g.ca(33,function(a){this.overflowButton&&this.overflowButton.Er(a)});
g.bW.prototype.rF=g.ca(32,function(a){this.fQ!==a&&(this.fQ=a,this.Yp())});
g.jU.prototype.Os=g.ca(6,function(){return this.app.Os()});
g.V0.prototype.Os=g.ca(5,function(){return this.getVideoData().lU});g.w(j6,g.U);j6.prototype.select=function(){this.J.zo(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.HC||void 0)&&this.J.tb(this.element)};
j6.prototype.onClick=function(a){g.JU(a,this.J,this.j,this.suggestion.sessionData||void 0)&&this.select()};
j6.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:a.defaultPrevented||(this.select(),a.preventDefault())}};g.w(k6,g.U);g.k=k6.prototype;g.k.YF=function(a){this.suggestion!==a&&(this.suggestion=a,i6(this.j,a),this.playButton.updateValue("url",this.suggestion.Pk()),l6(this))};
g.k.Sk=function(){return 0<this.C};
g.k.dB=function(){this.Sk()||(this.C=Date.now(),Znb(this),Ynb(this.J,aob(this)),g.Fu(this.J.getRootNode(),"countdown-running",this.Sk()))};
g.k.Bw=function(){this.Tp();Znb(this);var a=this.j.Ga("ytp-autonav-endscreen-upnext-header");a&&g.Gf(a,"\u00c0 suivre")};
g.k.Tp=function(){this.Sk()&&(this.D.stop(),this.C=0)};
g.k.select=function(a){this.J.nextVideo(!1,void 0===a?!1:a);this.Tp()};
g.k.yS=function(a){g.JU(a,this.J)&&(a.currentTarget===this.playButton.element?this.J.tb(this.playButton.element):a.currentTarget===this.j.Ga("ytp-autonav-endscreen-link-container")&&(a=this.j.Ga("ytp-autonav-endscreen-link-container"),this.J.Wa(a,!0),this.J.tb(a)),this.J.L("web_player_autonav_next_button_renderer")&&this.K?(this.J.Qa("innertubeCommand",this.K),this.Tp()):this.select())};
g.k.V0=function(){this.J.tb(this.cancelButton.element);g.lU(this.J,!0);this.G&&this.J.Qa("innertubeCommand",this.G)};
g.k.onVideoDataChange=function(a,b){this.J.L("web_player_autonav_next_button_renderer")&&(a=b.b4,this.K=null==a?void 0:a.navigationEndpoint,(a=null==a?void 0:a.trackingParams)&&this.J.eg(this.playButton.element,a));var c;this.G=null==(c=b.T3)?void 0:c.command};
g.k.B7=function(a){if(bob(this)){var b=this.J.getVideoData().watchToWatchTransitionRenderer,c=null==b?void 0:b.fromColorPaletteDark;b=null==b?void 0:b.toColorPaletteDark;if(c&&b){var d=this.element;d.style.setProperty("--w2w-start-background-color",g.jH(c.surgeColor));d.style.setProperty("--w2w-start-primary-text-color",g.jH(c.primaryTitleColor));d.style.setProperty("--w2w-start-secondary-text-color",g.jH(c.secondaryTitleColor));d.style.setProperty("--w2w-end-background-color",g.jH(b.surgeColor));
d.style.setProperty("--w2w-end-primary-text-color",g.jH(b.primaryTitleColor));d.style.setProperty("--w2w-end-secondary-text-color",g.jH(b.secondaryTitleColor));d.style.setProperty("--w2w-animation-duration",a+"ms")}g.Fu(this.element,"ytp-w2w-animate",!0)}};
g.k.U0=function(a){this.J.L("web_autonav_color_transition")&&2!==a&&g.Fu(this.element,"ytp-w2w-animate",!1)};
g.k.xS=function(){var a=this.J.Af();this.N&&this.Gb!==a&&g.kG(this,a);l6(this);this.J.Wa(this.container.element,a);this.J.Wa(this.cancelButton.element,a);this.J.Wa(this.j.Ga("ytp-autonav-endscreen-link-container"),a);this.J.Wa(this.playButton.element,a)};
g.k.wg=function(a){return 400>a.width||459>a.height};g.w(m6,g.U);g.k=m6.prototype;g.k.create=function(){this.created=!0};
g.k.destroy=function(){this.created=!1};
g.k.kC=function(){return!1};
g.k.Af=function(){return!1};
g.k.hX=function(){return!1};g.w(n6,g.U);g.k=n6.prototype;g.k.OG=function(){this.notification&&(this.D.stop(),this.Pc(this.C),this.C=null,this.notification.close(),this.notification=null)};
g.k.YF=function(a){this.suggestion=a;i6(this,a,"hqdefault.jpg")};
g.k.zS=function(){g.kG(this,this.api.Af());this.api.Wa(this.element,this.api.Af());this.api.Wa(this.Ga("ytp-upnext-autoplay-icon"),this.api.Af());this.cancelButton&&this.api.Wa(this.cancelButton.element,this.api.Af())};
g.k.v8=function(){window.focus();this.OG()};
g.k.dB=function(a){var b=this;this.Sk()||(g.PE("a11y-announce","\u00c0 suivre "+this.suggestion.title),this.B=(0,g.GD)(),this.j=new g.tu(function(){dob(b,a)},25),dob(this,a),Ynb(this.api,cob(this,a)));
g.Du(this.element,"ytp-upnext-autoplay-paused")};
g.k.hide=function(){g.U.prototype.hide.call(this)};
g.k.Sk=function(){return!!this.j};
g.k.Bw=function(){this.Tp();this.B=(0,g.GD)();dob(this);g.Bu(this.element,"ytp-upnext-autoplay-paused")};
g.k.Tp=function(){this.Sk()&&(this.j.dispose(),this.j=null)};
g.k.select=function(a){a=void 0===a?!1:a;if(this.api.U().L("autonav_notifications")&&a&&window.Notification&&"function"===typeof document.hasFocus){var b=Notification.permission;"default"===b?Notification.requestPermission():"granted"!==b||document.hasFocus()||(this.OG(),this.notification=new Notification("\u00c0 suivre",{body:this.suggestion.title,icon:this.suggestion.Tg()}),this.C=this.T(this.notification,"click",this.v8),this.D.start())}this.Tp();this.api.nextVideo(!1,a)};
g.k.X0=function(a){!g.Ff(this.cancelButton.element,a.target)&&g.JU(a,this.api)&&(this.api.Af()&&this.api.tb(this.Ga("ytp-upnext-autoplay-icon")),this.select())};
g.k.W0=function(){this.api.Af()&&this.cancelButton&&this.api.tb(this.cancelButton.element);g.lU(this.api,!0)};
g.k.m8=function(a){this.api.getPresentingPlayerType();this.show();this.dB(a)};
g.k.n8=function(){this.api.getPresentingPlayerType();this.Tp();this.hide()};
g.k.ya=function(){this.Tp();this.OG();g.U.prototype.ya.call(this)};g.w(o6,m6);g.k=o6.prototype;g.k.create=function(){m6.prototype.create.call(this);this.D.T(this.player,"appresize",this.GB);this.D.T(this.player,"onVideoAreaChange",this.GB);this.D.T(this.player,"videodatachange",this.onVideoDataChange);this.D.T(this.player,"autonavchange",this.AS);this.D.T(this.player,"onAutonavCancelled",this.Y0);this.onVideoDataChange()};
g.k.show=function(){m6.prototype.show.call(this);(this.K||this.C&&this.C!==this.videoData.clientPlaybackNonce)&&g.lU(this.player,!1);g.sU(this.player)&&this.kC()&&!this.C?(p6(this),2===this.videoData.autonavState?3===this.player.getVisibilityState()?this.j.select(!0):this.j.dB():3===this.videoData.autonavState&&this.j.Bw()):(g.lU(this.player,!0),p6(this));this.GB()};
g.k.hide=function(){m6.prototype.hide.call(this);this.j.Bw();p6(this)};
g.k.GB=function(){var a=this.player.Ok(!0,this.player.isFullscreen());p6(this);l6(this.B);g.Fu(this.element,"ytp-autonav-cancelled-small-mode",this.wg(a));g.Fu(this.element,"ytp-autonav-cancelled-tiny-mode",this.tI(a));g.Fu(this.element,"ytp-autonav-cancelled-mini-mode",400>=a.width||360>=a.height);this.overlay&&g.Qr(this.overlay.element,{width:a.width+"px"});if(!this.G)for(a=0;a<this.videos.length;a++)g.Fu(this.videos[a].element,"ytp-suggestion-card-with-margin",1===a%2)};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData();if(this.videoData!==a&&a){this.videoData=a;if((a=this.videoData.suggestions)&&a.length||this.player.L("web_player_autonav_empty_suggestions_fix")){var b=g.qT(this.videoData);b&&(this.j.YF(b),this.j!==this.B&&this.B.YF(b))}if(a&&a.length)for(b=0;b<job.length;++b){var c=job[b];if(a&&a[c]){this.videos[b]=new j6(this.player);var d=this.videos[b];c=a[c];d.suggestion!==c&&(d.suggestion=c,i6(d,c));g.L(this,this.videos[b]);this.videos[b].Fa(this.N.element)}}this.GB()}};
g.k.AS=function(a){1===a?(this.K=!1,this.C=this.videoData.clientPlaybackNonce,this.j.Tp(),this.Gb&&this.GB()):(this.K=!0,this.Af()&&(2===a?this.j.dB():3===a&&this.j.Bw()))};
g.k.Y0=function(a){a?this.AS(1):(this.C=null,this.K=!1)};
g.k.kC=function(){return 1!==this.videoData.autonavState};
g.k.wg=function(a){return(910>a.width||459>a.height)&&!this.tI(a)&&!(400>=a.width||360>=a.height)};
g.k.tI=function(a){return 800>a.width&&!(400>=a.width||360>=a.height)};
g.k.Af=function(){return this.Gb&&g.sU(this.player)&&this.kC()&&!this.C};
var job=[1,3,2,4];g.w(q6,g.U);g.k=q6.prototype;g.k.JZ=function(){switch(this.buttonType){case 1:var a="Regarder \u00e0 nouveau sur YouTube";var b=156915;break;case 2:a="Continuer \u00e0 regarder sur YouTube";b=156942;break;default:a="Continuer \u00e0 regarder sur YouTube",b=156942}this.update({content:a});this.J.Xj(this.element)&&this.J.xC(this.element);this.J.xb(this.element,this,b)};
g.k.onClick=function(a){this.J.L("web_player_log_click_before_generating_ve_conversion_params")&&this.J.tb(this.element);g.KU(this.getVideoUrl(),this.J,a);this.J.L("web_player_log_click_before_generating_ve_conversion_params")||this.J.tb(this.element)};
g.k.getVideoUrl=function(){var a=!0;switch(this.buttonType){case 1:a=!0;break;case 2:a=!1}a=this.J.getVideoUrl(a,!1,!1,!0);var b=this.J.U();if(g.bS(b)||g.jS(b)){var c={};g.bS(b)&&g.bU(this.J,"addEmbedsConversionTrackingParams",[c]);a:{switch(this.buttonType){case 2:b="emb_ytp_continue_watching";break a}b="emb_ytp_watch_again"}g.BP(c,b);a=g.Bl(a,c)}return a};
g.k.Wa=function(){this.J.Wa(this.element,this.Gb&&this.Z)};
g.k.show=function(){g.U.prototype.show.call(this);this.Wa()};
g.k.hide=function(){g.U.prototype.hide.call(this);this.Wa()};
g.k.lc=function(a){g.U.prototype.lc.call(this,a);this.Wa()};g.w(r6,m6);r6.prototype.show=function(){3!==this.player.getPlayerState()&&(m6.prototype.show.call(this),this.rb.XA(!0),this.rb.Fr(!0),this.J.U().Td||this.rb.Er(!0),this.J.Wa(this.element,!0),this.watchButton.lc(!0))};
r6.prototype.hide=function(){m6.prototype.hide.call(this);this.rb.XA(!1);this.rb.Fr(!1);this.rb.Er(!1);this.J.Wa(this.element,!1);this.watchButton.lc(!1)};g.w(eob,m6);eob.prototype.Ta=function(){var a=this.player.getVideoData();this.j.update({profilePicture:a.profilePicture,author:a.author});this.subscribeButton.channelId=a.Fl;var b=this.subscribeButton;a.subscribed?b.j():b.B()};g.w(s6,g.U);s6.prototype.select=function(){this.api.zo(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.HC||void 0)&&this.api.tb(this.element)};
s6.prototype.onClick=function(a){if(g.bS(this.api.U())&&this.api.L("web_player_log_click_before_generating_ve_conversion_params")){this.api.tb(this.element);var b=this.suggestion.Pk(),c={};g.dSa(this.api,c,"emb_rel_end");b=g.Bl(b,c);g.KU(b,this.api,a)}else g.JU(a,this.api,this.B,this.suggestion.sessionData||void 0)&&this.select()};
s6.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:a.defaultPrevented||(this.select(),a.preventDefault())}};
s6.prototype.onVideoDataChange=function(){var a=this.api.getVideoData(),b=this.api.U();this.B=a.Pd?!1:b.D};g.w(t6,m6);g.k=t6.prototype;g.k.create=function(){m6.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.videoData=a);this.bq();this.B.T(this.player,"appresize",this.bq);this.B.T(this.player,"onVideoAreaChange",this.bq);this.B.T(this.player,"videodatachange",this.onVideoDataChange);this.B.T(this.player,"autonavchange",this.ZK);this.B.T(this.player,"onAutonavCancelled",this.Z0);a=this.videoData.autonavState;a!==this.Y&&this.ZK(a);this.B.T(this.element,"transitionend",this.L9)};
g.k.destroy=function(){g.VC(this.B);g.vb(this.stills);this.stills=[];m6.prototype.destroy.call(this);g.Du(this.element,"ytp-show-tiles");this.K.stop();this.Y=this.videoData.autonavState};
g.k.kC=function(){return 1!==this.videoData.autonavState};
g.k.show=function(){var a=this.Gb;m6.prototype.show.call(this);g.Du(this.element,"ytp-show-tiles");this.player.U().B?g.vu(this.K):this.K.start();(this.G||this.D&&this.D!==this.videoData.clientPlaybackNonce)&&g.lU(this.player,!1);u6(this)?(v6(this),2===this.videoData.autonavState?3===this.player.getVisibilityState()?this.j.select(!0):this.j.dB():3===this.videoData.autonavState&&this.j.Bw()):(g.lU(this.player,!0),v6(this));a!==this.Gb&&this.player.Wa(this.element,!0)};
g.k.hide=function(){var a=this.Gb;m6.prototype.hide.call(this);this.j.Bw();v6(this);a!==this.Gb&&this.player.Wa(this.element,!1)};
g.k.L9=function(a){a.target===this.element&&this.bq()};
g.k.bq=function(){var a,b,c,d;var e=(null==(a=this.videoData)?0:null==(b=a.suggestions)?0:b.length)?null==(c=this.videoData)?void 0:c.suggestions:[null==(d=this.videoData)?void 0:g.qT(d)];if(e.length){g.Bu(this.element,"ytp-endscreen-paginate");var f=this.J.Ok(!0,this.J.isFullscreen());if(a=g.eU(this.J))a=a.Kg()?48:32,f.width-=2*a;var h=f.width/f.height;d=96/54;b=a=2;var l=Math.max(f.width/96,2),m=Math.max(f.height/54,2);c=e.length;var n=Math.pow(2,2);var p=c*n+(Math.pow(2,2)-n);p+=Math.pow(2,2)-
n;for(p-=n;0<p&&(a<l||b<m);){var q=a/2,r=b/2,t=a<=l-2&&p>=r*n,v=b<=m-2&&p>=q*n;if((q+1)/r*d/h>h/(q/(r+1)*d)&&v)p-=q*n,b+=2;else if(t)p-=r*n,a+=2;else if(v)p-=q*n,b+=2;else break}d=!1;p>=3*n&&6>=c*n-p&&(4<=b||4<=a)&&(d=!0);n=96*a;p=54*b;h=n/p<h?f.height/p:f.width/n;h=Math.min(h,2);n=Math.floor(Math.min(f.width,n*h));p=Math.floor(Math.min(f.height,p*h));f=this.table.element;f.ariaLive="polite";g.$r(f,n,p);g.Qr(f,{marginLeft:n/-2+"px",marginTop:p/-2+"px"});this.j.YF(g.qT(this.videoData));this.j instanceof
k6&&l6(this.j);g.Fu(this.element,"ytp-endscreen-takeover",u6(this));v6(this);n+=4;p+=4;h=0;f.ariaBusy="true";for(l=0;l<a;l++)for(m=0;m<b;m++)if(q=h,t=0,d&&l>=a-2&&m>=b-2?t=1:0===m%2&&0===l%2&&(2>m&&2>l?0===m&&0===l&&(t=2):t=2),q=g.se(q+this.C,c),0!==t){r=this.stills[h];r||(r=new s6(this.player),this.stills[h]=r,f.appendChild(r.element));v=Math.floor(p*m/b);var x=Math.floor(n*l/a),C=Math.floor(p*(m+t)/b)-v-4,F=Math.floor(n*(l+t)/a)-x-4;g.Wr(r.element,x,v);g.$r(r.element,F,C);g.Qr(r.element,"transitionDelay",
(m+l)/20+"s");g.Fu(r.element,"ytp-videowall-still-mini",1===t);g.Fu(r.element,"ytp-videowall-still-large",2<t);t=Math.max(F,C);g.Fu(r.element,"ytp-videowall-still-round-large",256<=t);g.Fu(r.element,"ytp-videowall-still-round-medium",96<t&&256>t);g.Fu(r.element,"ytp-videowall-still-round-small",96>=t);q=e[q];r.suggestion!==q&&(r.suggestion=q,t=r.api.U(),v=g.Au(r.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",i6(r,q,v),g.bS(t)&&!r.api.L("web_player_log_click_before_generating_ve_conversion_params")&&
(t=q.Pk(),v={},g.bU(r.api,"addEmbedsConversionTrackingParams",[v]),t=g.Bl(t,g.BP(v,"emb_rel_end")),r.updateValue("url",t)),(q=(q=q.sessionData)&&q.itct)&&r.api.eg(r.element,q));h++}f.ariaBusy="false";g.Fu(this.element,"ytp-endscreen-paginate",h<c);for(e=this.stills.length-1;e>=h;e--)a=this.stills[e],g.Af(a.element),g.ub(a);this.stills.length=h}};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData();this.videoData!==a&&(this.C=0,this.videoData=a,this.bq())};
g.k.b1=function(){this.C+=this.stills.length;this.bq()};
g.k.d1=function(){this.C-=this.stills.length;this.bq()};
g.k.hX=function(){return this.j.Sk()};
g.k.ZK=function(a){1===a?(this.G=!1,this.D=this.videoData.clientPlaybackNonce,this.j.Tp(),this.Gb&&this.bq()):(this.G=!0,this.Gb&&u6(this)&&(2===a?this.j.dB():3===a&&this.j.Bw()))};
g.k.Z0=function(a){if(a){for(a=0;a<this.stills.length;a++)this.J.Wa(this.stills[a].element,!0);this.ZK(1)}else this.D=null,this.G=!1;this.bq()};
g.k.Af=function(){return this.Gb&&u6(this)};g.w(w6,m6);w6.prototype.tD=function(){var a;return null==(a=this.j)?void 0:a.tD()};
w6.prototype.show=function(){if(3!==this.player.getPlayerState()){m6.prototype.show.call(this);var a=this.B;if(a){var b=this.j.tD();g.Fu(this.element,"ytp-shorts-branded-ui",b);b?a.show():a.hide()}var c;null==(c=g.eU(this.player))||c.rF(!0);this.player.Wa(this.element,!0);this.watchButton.lc(!0)}};
w6.prototype.hide=function(){m6.prototype.hide.call(this);var a;null==(a=g.eU(this.player))||a.rF(!1);this.player.Wa(this.element,!1);this.watchButton.lc(!1)};g.w(iob,g.yV);g.k=iob.prototype;g.k.Vt=function(){var a=this.player.getVideoData(),b=a.mutedAutoplay;if((g.oU(this.player)||this.B)&&!b)return!0;var c;var d=!!((null==a?0:g.qT(a))||(null==a?0:null==(c=a.suggestions)?0:c.length));d=!fob(this.player)||d;a=a.pj||g.jS(a.Ia);c=this.player.TC();return d&&!a&&!c&&!b};
g.k.Af=function(){return this.endScreen.Af()};
g.k.s6=function(){return this.Af()?this.endScreen.hX():!1};
g.k.ya=function(){this.player.jf("endscreen");g.yV.prototype.ya.call(this)};
g.k.load=function(){var a=this.player.getVideoData();var b=a.transitionEndpointAtEndOfStream;if(b&&b.videoId){var c=this.player.Eb().Re.get("heartbeat"),d=g.qT(a);!d||b.videoId!==d.videoId||a.lS?(this.player.zo(b.videoId,void 0,void 0,!0,!0,b),c&&c.CI("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),a=!0):a=!1}else a=!1;a||(g.yV.prototype.load.call(this),this.endScreen.show())};
g.k.unload=function(){g.yV.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.k.onCueRangeEnter=function(a){this.Vt()&&(this.endScreen.created||this.endScreen.create(),"load"===a.getId()&&this.load())};
g.k.onCueRangeExit=function(a){"load"===a.getId()&&this.loaded&&this.unload()};
g.k.onVideoDataChange=function(){hob(this);this.D&&gob(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.j?this.endScreen=new o6(this.player):this.endScreen=new t6(this.player),g.L(this,this.endScreen),g.rU(this.player,this.endScreen.element,4))};g.xV("endscreen",iob);})(_yt_player);
