(function(g){var window=this;'use strict';var Xob=function(a){g.U.call(this,{I:"div",S:"ytp-inline-preview-ui"});this.pg=!1;this.player=a;this.T(a,"onStateChange",this.BR);this.T(a,"videodatachange",this.kx);this.T(a,"onInlinePreviewModeChange",this.n6);this.zf=new g.qu(this.ow,null,this);g.L(this,this.zf)},G6=function(a){g.yV.call(this,a);
this.j=new Xob(this.player);g.L(this,this.j);this.j.hide();g.rU(this.player,this.j.element,4);a.isInline()&&(this.load(),a=a.getRootNode(),g.Cu(a,["ytp-inline-preview-mode","ytp-no-contextmenu"]))};
g.w(Xob,g.U);g.k=Xob.prototype;
g.k.kO=function(){this.tooltip=new g.TX(this.player,this);g.L(this,this.tooltip);g.rU(this.player,this.tooltip.element,4);this.tooltip.scale=.6;this.fd=new g.eW(this.player);g.L(this,this.fd);this.vk=new g.U({I:"div",Ma:["ytp-inline-preview-scrim"]});g.L(this,this.vk);this.vk.Fa(this.element);this.T(this.vk.element,"click",this.kJ);this.Fj=new g.MX(this.player,this,300);g.L(this,this.Fj);this.Fj.Fa(this.vk.element);this.controls=new g.U({I:"div",S:"ytp-inline-preview-controls"});g.L(this,this.controls);
this.controls.Fa(this.element);var a=new g.dX(this.player,this,!1);g.L(this,a);a.Fa(this.controls.element);a=new g.KX(this.player,this);g.L(this,a);a.Fa(this.controls.element);this.Sc=new g.kX(this.player,this);g.L(this,this.Sc);g.rU(this.player,this.Sc.element,4);this.T(this.player,"appresize",this.Kb);this.T(this.player,"fullscreentoggled",this.Kb);this.Kb()};
g.k.show=function(){g.ru(this.zf);this.pg||(this.kO(),this.pg=!0);0!==this.player.getPlayerState()&&g.U.prototype.show.call(this);this.Sc.show();this.player.Qa("onInlinePreviewUiReady")};
g.k.hide=function(){this.zf.stop();g.U.prototype.hide.call(this);this.player.isInline()||this.pg&&this.Sc.hide()};
g.k.ya=function(){g.U.prototype.ya.call(this)};
g.k.kJ=function(a){a.target===this.vk.element&&this.player.Qa("onExpandInlinePreview",a)};
g.k.n6=function(){g.Fu(this.player.getRootNode(),"ytp-inline-preview-mode",this.player.isInline())};
g.k.Ye=function(){this.Sc.Kc();this.Fj.Kc()};
g.k.ow=function(){this.Ye();g.ru(this.zf)};
g.k.Kb=function(){g.wX(this.Sc,0,this.player.qb().getPlayerSize().width,!1);g.lX(this.Sc)};
g.k.BR=function(a){this.player.isInline()&&(0===a?this.hide():this.show())};
g.k.kx=function(a,b){if(this.player.isInline()){g.Fu(this.player.getRootNode(),"ytp-show-inline-preview-audio-controls",b.VB);var c,d,e;a=!(null==(e=null==(c=b.getPlayerResponse())?void 0:null==(d=c.playerConfig)?void 0:d.inlinePlaybackConfig)||!e.showScrubbingControls);g.Fu(this.player.getRootNode(),"ytp-hide-inline-preview-progress-bar",!a)}};
g.k.Ec=function(){return this.tooltip};
g.k.Kg=function(){return!1};
g.k.wg=function(){return!1};
g.k.nm=function(){return!1};
g.k.hK=function(){};
g.k.Is=function(){};
g.k.Xy=function(){};
g.k.pn=function(){return null};
g.k.zH=function(){return null};
g.k.CN=function(){return new g.Ce(0,0)};
g.k.Ok=function(){return new g.Nr(0,0,0,0)};
g.k.handleGlobalKeyDown=function(){return!1};
g.k.handleGlobalKeyUp=function(){return!1};
g.k.Gw=function(a,b,c,d,e){var f=d=0,h=0,l=g.as(a);if(b){c=g.Au(b,"ytp-mute-button");var m=g.Au(b,"ytp-subtitles-button"),n=g.Zr(b,this.element);b=g.as(b);d=n.y+40;if(m||c)h=n.x-l.width+b.width}else h=c-l.width/2,f=35;b=this.player.qb().getPlayerSize().width;h=g.re(h,0,b-l.width);d?(a.style.top=d+(e||0)+"px",a.style.bottom=""):(a.style.top="",a.style.bottom=f+"px");a.style.left=h+"px"};
g.k.showControls=function(){};
g.k.Wp=function(){};
g.k.Zl=function(){return!1};
g.k.rF=function(){};
g.k.XA=function(){};
g.k.Fr=function(){};
g.k.Er=function(){};
g.k.Hu=function(){};
g.k.Ks=function(){};
g.k.XE=function(){};g.w(G6,g.yV);G6.prototype.wl=function(){return!1};
G6.prototype.load=function(){this.player.hideControls();this.j.show()};
G6.prototype.unload=function(){this.player.showControls();this.j.hide()};g.xV("inline_preview",G6);})(_yt_player);
