"use strict";this.default_IdentityRotateCookiesHttp=this.default_IdentityRotateCookiesHttp||{};(function(_){var window=this;
try{
/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var aa=function(a){p.setTimeout(function(){throw a;},0)},t=function(a){return ba?r?r.brands.some(function(b){return(b=b.brand)&&-1!=b.indexOf(a)}):!1:!1},u=function(a){var b;a:{if(b=p.navigator)if(b=b.userAgent)break a;b=""}return-1!=b.indexOf(a)},v=function(){return ba?!!r&&0<r.brands.length:!1},w=function(){return v()?t("Chromium"):(u("Chrome")||u("CriOS"))&&!(v()?0:u("Edge"))||u("Silk")},ca=function(a){var b=x(a);1!==(b&1)&&(Object.isFrozen(a)&&(a=Array.prototype.slice.call(a)),z(a,b|1))},ea=function(){var a=
[];da(a,1);return a},A=function(a){a=a>>12&1023;return 0===a?536870912:a},B=function(a){return null!==a&&"object"===typeof a&&!Array.isArray(a)&&a.constructor===Object},ha=function(a){a=Error(a);fa(a,"warning");return a},ja=function(a){var b=typeof a;return"number"===b?Number.isFinite(a):"string"!==b?!1:ia.test(a)},E=function(a,b,c){null==a&&(a=C);C=void 0;if(null==a){var e=96;c?(a=[c],e|=512):a=[];b&&(e=e&-4190209|(b&1023)<<12)}else{if(!Array.isArray(a))throw Error();e=x(a);if(e&64)return a;e|=64;
if(c&&(e|=512,c!==a[0]))throw Error();a:{c=a;var f=c.length;if(f){var h=f-1,d=c[h];if(B(d)){e|=256;b=+!!(e&512)-1;f=h-b;1024<=f&&(ka(c,b,d),f=1023);e=e&-4190209|(f&1023)<<12;break a}}b&&(d=+!!(e&512)-1,b=Math.max(b,f-d),1024<b&&(ka(c,d,{}),e|=256,b=1023),e=e&-4190209|(b&1023)<<12)}}z(a,e);return a},ka=function(a,b,c){for(var e=1023+b,f=a.length,h=e;h<f;h++){var d=a[h];null!=d&&d!==c&&(c[h-b]=d)}a.length=e+1;a[e]=c},ma=function(a,b){return la(b)},la=function(a){switch(typeof a){case "number":return isFinite(a)?
a:String(a);case "boolean":return a?1:0;case "object":if(a&&!Array.isArray(a)&&na&&null!=a&&a instanceof Uint8Array){if(oa){for(var b="",c=0,e=a.length-10240;c<e;)b+=String.fromCharCode.apply(null,a.subarray(c,c+=10240));b+=String.fromCharCode.apply(null,c?a.subarray(c):a);a=btoa(b)}else{void 0===b&&(b=0);if(!F){F={};c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split("");e=["+/=","+/","-_=","-_.","-_"];for(var f=0;5>f;f++){var h=c.concat(e[f].split(""));pa[f]=h;for(var d=0;d<
h.length;d++){var g=h[d];void 0===F[g]&&(F[g]=d)}}}b=pa[b];c=Array(Math.floor(a.length/3));e=b[64]||"";for(f=h=0;h<a.length-2;h+=3){var k=a[h],l=a[h+1];g=a[h+2];d=b[k>>2];k=b[(k&3)<<4|l>>4];l=b[(l&15)<<2|g>>6];g=b[g&63];c[f++]=d+k+l+g}d=0;g=e;switch(a.length-h){case 2:d=a[h+1],g=b[(d&15)<<2]||e;case 1:a=a[h],c[f]=b[a>>2]+b[(a&3)<<4|d>>4]+g+e}a=c.join("")}return a}}return a},ra=function(a,b,c,e,f,h){if(null!=a){if(Array.isArray(a))a=f&&0==a.length&&x(a)&1?void 0:h&&x(a)&2?a:qa(a,b,c,void 0!==e,f,h);
else if(B(a)){var d={},g;for(g in a)d[g]=ra(a[g],b,c,e,f,h);a=d}else a=b(a,e);return a}},qa=function(a,b,c,e,f,h){var d=e||c?x(a):0;e=e?!!(d&32):void 0;a=Array.prototype.slice.call(a);for(var g=0;g<a.length;g++)a[g]=ra(a[g],b,c,e,f,h);c&&c(d,a);return a},ta=function(a){return a.H===sa?a.toJSON():la(a)},I=function(a,b,c){var e=a.constructor.K,f=A(G(c?a.j:b)),h=!1;if(e){if(!c){b=Array.prototype.slice.call(b);var d;if(b.length&&B(d=b[b.length-1]))for(h=0;h<e.length;h++)if(e[h]>=f){Object.assign(b[b.length-
1]={},d);break}h=!0}f=b;c=!c;d=G(a.j);a=A(d);d=+!!(d&512)-1;for(var g,k,l=0;l<e.length;l++)if(k=e[l],k<a){k+=d;var m=f[k];null==m?f[k]=c?H:ea():c&&m!==H&&ca(m)}else g||(m=void 0,f.length&&B(m=f[f.length-1])?g=m:f.push(g={})),m=g[k],null==g[k]?g[k]=c?H:ea():c&&m!==H&&ca(m)}e=b.length;if(!e)return b;var y;if(B(g=b[e-1])){a:{var n=g;f={};c=!1;for(var q in n)a=n[q],Array.isArray(a)&&a!=a&&(c=!0),null!=a?f[q]=a:c=!0;if(c){for(var L in f){n=f;break a}n=null}}n!=g&&(y=!0);e--}for(;0<e;e--){g=b[e-1];if(null!=
g)break;var D=!0}if(!y&&!D)return b;var T;h?T=b:T=Array.prototype.slice.call(b,0,e);b=T;h&&(b.length=e);n&&b.push(n);return b},ua=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}},va="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a},wa=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==
typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("a");},J=wa(this),K=function(a,b){if(b)a:{var c=J;a=a.split(".");for(var e=0;e<a.length-1;e++){var f=a[e];if(!(f in c))break a;c=c[f]}a=a[a.length-1];e=c[a];b=b(e);b!=e&&null!=b&&va(c,a,{configurable:!0,writable:!0,value:b})}},xa=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if("number"==typeof a.length)return{next:ua(a)};throw Error("b`"+
String(a));},ya="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},M;if("function"==typeof Object.setPrototypeOf)M=Object.setPrototypeOf;else{var N;a:{var za={a:!0},Aa={};try{Aa.__proto__=za;N=Aa.a;break a}catch(a){}N=!1}M=N?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError("c`"+a);return a}:null}
var Ba=M,Ca=function(a,b){a.prototype=ya(b.prototype);a.prototype.constructor=a;if(Ba)Ba(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(b,c);e&&Object.defineProperty(a,c,e)}else a[c]=b[c];a.L=b.prototype};
K("Promise",function(a){function b(){this.g=null}function c(d){return d instanceof f?d:new f(function(g){g(d)})}if(a)return a;b.prototype.h=function(d){if(null==this.g){this.g=[];var g=this;this.i(function(){g.o()})}this.g.push(d)};var e=J.setTimeout;b.prototype.i=function(d){e(d,0)};b.prototype.o=function(){for(;this.g&&this.g.length;){var d=this.g;this.g=[];for(var g=0;g<d.length;++g){var k=d[g];d[g]=null;try{k()}catch(l){this.m(l)}}}this.g=null};b.prototype.m=function(d){this.i(function(){throw d;
})};var f=function(d){this.h=0;this.i=void 0;this.g=[];this.v=!1;var g=this.m();try{d(g.resolve,g.reject)}catch(k){g.reject(k)}};f.prototype.m=function(){function d(l){return function(m){k||(k=!0,l.call(g,m))}}var g=this,k=!1;return{resolve:d(this.C),reject:d(this.o)}};f.prototype.C=function(d){if(d===this)this.o(new TypeError("d"));else if(d instanceof f)this.F(d);else{a:switch(typeof d){case "object":var g=null!=d;break a;case "function":g=!0;break a;default:g=!1}g?this.B(d):this.u(d)}};f.prototype.B=
function(d){var g=void 0;try{g=d.then}catch(k){this.o(k);return}"function"==typeof g?this.G(g,d):this.u(d)};f.prototype.o=function(d){this.A(2,d)};f.prototype.u=function(d){this.A(1,d)};f.prototype.A=function(d,g){if(0!=this.h)throw Error("e`"+d+"`"+g+"`"+this.h);this.h=d;this.i=g;2===this.h&&this.D();this.I()};f.prototype.D=function(){var d=this;e(function(){if(d.J()){var g=J.console;"undefined"!==typeof g&&g.error(d.i)}},1)};f.prototype.J=function(){if(this.v)return!1;var d=J.CustomEvent,g=J.Event,
k=J.dispatchEvent;if("undefined"===typeof k)return!0;"function"===typeof d?d=new d("unhandledrejection",{cancelable:!0}):"function"===typeof g?d=new g("unhandledrejection",{cancelable:!0}):(d=J.document.createEvent("CustomEvent"),d.initCustomEvent("unhandledrejection",!1,!0,d));d.promise=this;d.reason=this.i;return k(d)};f.prototype.I=function(){if(null!=this.g){for(var d=0;d<this.g.length;++d)h.h(this.g[d]);this.g=null}};var h=new b;f.prototype.F=function(d){var g=this.m();d.s(g.resolve,g.reject)};
f.prototype.G=function(d,g){var k=this.m();try{d.call(g,k.resolve,k.reject)}catch(l){k.reject(l)}};f.prototype.then=function(d,g){function k(n,q){return"function"==typeof n?function(L){try{l(n(L))}catch(D){m(D)}}:q}var l,m,y=new f(function(n,q){l=n;m=q});this.s(k(d,l),k(g,m));return y};f.prototype.catch=function(d){return this.then(void 0,d)};f.prototype.s=function(d,g){function k(){switch(l.h){case 1:d(l.i);break;case 2:g(l.i);break;default:throw Error("f`"+l.h);}}var l=this;null==this.g?h.h(k):
this.g.push(k);this.v=!0};f.resolve=c;f.reject=function(d){return new f(function(g,k){k(d)})};f.race=function(d){return new f(function(g,k){for(var l=xa(d),m=l.next();!m.done;m=l.next())c(m.value).s(g,k)})};f.all=function(d){var g=xa(d),k=g.next();return k.done?c([]):new f(function(l,m){function y(L){return function(D){n[L]=D;q--;0==q&&l(n)}}var n=[],q=0;do n.push(void 0),q++,c(k.value).s(y(n.length-1),m),k=g.next();while(!k.done)})};return f});
var Da="function"==typeof Object.assign?Object.assign:function(a,b){for(var c=1;c<arguments.length;c++){var e=arguments[c];if(e)for(var f in e)Object.prototype.hasOwnProperty.call(e,f)&&(a[f]=e[f])}return a};K("Object.assign",function(a){return a||Da});K("Number.isFinite",function(a){return a?a:function(b){return"number"!==typeof b?!1:!isNaN(b)&&Infinity!==b&&-Infinity!==b}});K("Number.isNaN",function(a){return a?a:function(b){return"number"===typeof b&&isNaN(b)}});var p=this||self,Ea=p._F_toggles||[];var Fa=!!(Ea[0]&1024);var O;if(Ea[0]&512)O=Fa;else{var P;a:{for(var Ga=["WIZ_global_data","oxN3nb"],Q=p,R=0;R<Ga.length;R++)if(Q=Q[Ga[R]],null==Q){P=null;break a}P=Q}var Ha=P&&P[610401301];O=null!=Ha?Ha:!1}var ba=O;var r,Ia=p.navigator;r=Ia?Ia.userAgentData||null:null;var Ja=v()?!1:u("Trident")||u("MSIE");!u("Android")||w();w();u("Safari")&&(w()||(v()?0:u("Coast"))||(v()?0:u("Opera"))||(v()?0:u("Edge"))||(v()?t("Microsoft Edge"):u("Edg/"))||v()&&t("Opera"));var pa={},F=null;var na="undefined"!==typeof Uint8Array,oa=!Ja&&"function"===typeof btoa;var S="function"===typeof Symbol&&"symbol"===typeof Symbol()?Symbol():void 0,da=S?function(a,b){a[S]|=b}:function(a,b){void 0!==a.l?a.l|=b:Object.defineProperties(a,{l:{value:b,configurable:!0,writable:!0,enumerable:!1}})},x=S?function(a){return a[S]|0}:function(a){return a.l|0},G=S?function(a){return a[S]}:function(a){return a.l},z=S?function(a,b){a[S]=b}:function(a,b){void 0!==a.l?a.l=b:Object.defineProperties(a,{l:{value:b,configurable:!0,writable:!0,enumerable:!1}})};var sa={},U,H,Ka=[];z(Ka,55);H=Object.freeze(Ka);var fa=function(a,b){a.__closure__error__context__984382||(a.__closure__error__context__984382={});a.__closure__error__context__984382.severity=b};var ia=/^-?([1-9][0-9]*|0)(\.[0-9]+)?$/;var C;Object.freeze({});var La=function(a,b,c){var e=a.j,f=G(e);if(f&2)throw Error();a:{var h=A(f);if(b>=h){var d=f;if(f&256)h=e[e.length-1];else{if(null==c)break a;h=e[h+(+!!(f&512)-1)]={};d|=256}h[b]=c;d!==f&&z(e,d)}else e[b+(+!!(f&512)-1)]=c,f&256&&(c=e[e.length-1],b in c&&delete c[b])}return a},Ma=function(a){var b=void 0===b?0:b;a=a.j;a:{var c=G(a);if(1>=A(c)){if(c&256){a=a[a.length-1][1];break a}}else if(c=1+(+!!(c&512)-1),c<a.length){a=a[c];break a}a=void 0}a=null==a?a:ja(a)?"number"===typeof a?a:a:void 0;return null!=
a?a:b},Na=function(a,b,c){if(null!=c){if("number"!==typeof c)throw ha("int32");if(!Number.isFinite(c)){var e=Error();fa(e,"incident");aa(e)}}La(a,b,c)};var V=function(a,b,c){this.j=E(a,b,c)};V.prototype.toJSON=function(){if(U)var a=I(this,this.j,!1);else a=qa(this.j,ta,void 0,void 0,!1,!1),a=I(this,a,!0);return a};var Oa=function(a){U=!0;try{return JSON.stringify(a.toJSON(),ma)}finally{U=!1}};V.prototype.H=sa;V.prototype.toString=function(){return I(this,this.j,!1).toString()};var Pa=function(a){this.j=E(a)};Ca(Pa,V);var Qa=function(a){this.j=E(a,0,"identity.hfcr")};Ca(Qa,V);var Ra=function(a){return function(b){if(null==b||""==b)b=new a;else{b=JSON.parse(b);if(!Array.isArray(b))throw Error(void 0);da(b,32);C=b;b=new a(b);C=void 0}return b}}(Qa);var Sa=function(a,b,c,e,f,h){this.u=a;this.i=b;this.o=c;this.h=e;this.g=f;this.m=h};Sa.prototype.start=function(){var a=this;if("undefined"!==typeof fetch)if(Ta()){var b=Ua(),c=Date.now();b&&b>c+1E3*this.g&&(b=Date.now()+1E3*this.g,W(b));var e=function(){Va(a).then(function(){a.m||setTimeout(e,1E3*a.g)})};setTimeout(function(){e()},b&&b>c?b-c:0)}else Wa(this)};
var Wa=function(a){var b=Xa(a);a.m||b.then(function(){var c=function(){Xa(a).then(function(){setTimeout(c,1E3*a.g)})};setTimeout(function(){c()},1E3*a.g)})},Xa=function(a){var b=Ya(a);return Za(b).then(function(c){c=$a(Ma(c));c!==a.g&&(a.g=c)}).catch(function(){a.g*=2})},Va=function(a){var b=Ua();if(!b||Date.now()>=b){var c=Math.floor(1E3*Math.random());return new Promise(function(e){setTimeout(function(){var f=Ua();!f||Date.now()>=f?e(ab(a)):e()},c)})}return Promise.resolve()},Za=function(a){a={method:"POST",
credentials:"same-origin",cache:"no-store",mode:"same-origin",headers:{"Content-Type":"application/json"},body:Oa(a)};if("undefined"!==typeof AbortController){var b=new AbortController;setTimeout(function(){b.abort()},3E4);a.signal=b.signal}return fetch(new Request("/RotateCookies",a)).then(function(c){return c.text()}).then(function(c){return Ra(JSON.stringify(JSON.parse(c.substring(5))[0]))})},Ya=function(a){var b=new Pa;var c=a.u;if(null!=c){if(!ja(c))throw ha("int64");c="string"===typeof c?c:
c}b=La(b,2,c);0!==a.i&&Na(b,1,a.i);0!==a.o&&Na(b,3,a.o);0!==a.h&&Na(b,4,a.h);return b},ab=function(a){W(Date.now()+1E3*a.g);var b=Ya(a);return Za(b).then(function(c){c=$a(Ma(c));c!==a.g&&(W(Date.now()+1E3*c),a.g=c)}).catch(function(){a.g*=2;W(Date.now()+1E3*a.g)})},Ta=function(){try{var a=window.localStorage;if(!a)return!1;a.setItem("cookieRotationStorageAccessTest","1");a.removeItem("cookieRotationStorageAccessTest");return!0}catch(b){return!1}},$a=function(a){60>a&&(a=60);return a},Ua=function(){try{var a=
window.localStorage.getItem("nextRotationAttemptTs");if(!a)return null;var b=Math.floor(Number(a));return Number.isNaN(b)?null:b}catch(c){return null}},W=function(a){try{window.localStorage.setItem("nextRotationAttemptTs",a.toString())}catch(b){}};var bb=function(a,b,c,e,f,h){(new Sa(a,b,c,e,f,h)).start()},X=["init"],Y=p;X[0]in Y||"undefined"==typeof Y.execScript||Y.execScript("var "+X[0]);for(var Z;X.length&&(Z=X.shift());)X.length||void 0===bb?Y[Z]&&Y[Z]!==Object.prototype[Z]?Y=Y[Z]:Y=Y[Z]={}:Y[Z]=bb;
}catch(e){_._DumpException(e)}
}).call(this,this.default_IdentityRotateCookiesHttp);
// Google Inc.
